import {test,expect} from '@playwright/test'
const headers={'X-Pr0former':'1'}
test('console header is a single compact line with its controls on the right, and Shift+` toggles the modal',async({page})=>{
 const status=await(await page.request.get('/api/status')).json()
 await page.request.post(`/api/${status.bootstrap?'register':'login'}`,{headers,data:{username:'browser-test',password:'test1234'}})
 const p=await(await page.request.post('/api/projects',{headers,data:{name:'Console layout',mode:'freeform'}})).json()
 await page.goto('/')
 await page.getByRole('button',{name:'Enable audio engine',exact:true}).click()
 const dialog=page.getByRole('dialog',{name:'Console',exact:true})
 await page.locator('.graph-canvas').click({position:{x:20,y:400}})
 await page.keyboard.press('Shift+Backquote')
 await expect(dialog).toBeVisible()
 await expect(dialog.getByRole('log')).toContainText('Project engine prepared')
 await expect(dialog.getByText('Recent server activity',{exact:true})).toHaveCount(0)
 await expect(dialog.getByText('PROJECT ENGINE',{exact:true})).toHaveCount(0)
 const header=dialog.locator('.console-header'),title=dialog.getByRole('heading',{name:'Console',exact:true}),follow=dialog.getByLabel('Autoscroll',{exact:true}),clear=dialog.getByRole('button',{name:'Clear console',exact:true})
 const headerBox=(await header.boundingBox())!,titleBox=(await title.boundingBox())!,followBox=(await follow.boundingBox())!,clearBox=(await clear.boundingBox())!,dialogBox=(await dialog.boundingBox())!
 expect(headerBox.height,'compact header').toBeLessThan(56)
 expect(Math.abs(titleBox.y+titleBox.height/2-(followBox.y+followBox.height/2))).toBeLessThan(6)
 expect(Math.abs(titleBox.y+titleBox.height/2-(clearBox.y+clearBox.height/2))).toBeLessThan(6)
 expect(followBox.x).toBeGreaterThan(dialogBox.x+dialogBox.width/2)
 expect(clearBox.x).toBeGreaterThan(followBox.x)
 await page.screenshot({path:'test-results/console-modal.png'})
 await page.keyboard.press('Shift+Backquote')
 await expect(dialog).toHaveCount(0)
 // The plain backtick still toggles the engine and Shift+` is ignored while typing.
 await page.getByLabel('Search nodes',{exact:true}).focus().catch(()=>{})
 await page.goto(`/?console=${p.id}`)
 await expect(page.getByRole('log')).toBeVisible()
 await expect(page.getByText('Recent server activity',{exact:true})).toHaveCount(0)
 await expect(page.getByText('PROJECT ENGINE',{exact:true})).toHaveCount(0)
 expect((await page.locator('.console-header').boundingBox())!.height).toBeLessThan(56)
 await page.screenshot({path:'test-results/console-standalone.png'})
})
