import { test, expect, type Page } from '@playwright/test'
const headers = { 'X-Pr0former': '1' }
async function setup(page: Page) {
  const status = await (await page.request.get('/api/status')).json()
  const auth = await page.request.post(`/api/${status.bootstrap ? 'register' : 'login'}`, { headers, data: { username: 'browser-test', password: 'test1234' } })
  expect(auth.ok()).toBeTruthy()
  const project = await (await page.request.post('/api/projects', { headers, data: { name: 'Documentation review', mode: 'freeform' } })).json()
  project.parts = []
  project.graph = { nodes: [{ id: 'envelope', kind: 'adsr', label: 'Envelope', x: 0, y: 0, channels: 2, parameters: {} }], edges: [] }
  expect((await page.request.put(`/api/projects/${project.id}`, { headers, data: project })).ok()).toBeTruthy()
  await page.addInitScript(() => { if (!localStorage.getItem('pr0former.help')) localStorage.setItem('pr0former.help', 'hidden') })
  await page.goto('/')
  return project.id
}
async function docs(page: Page) {
  await page.getByRole('button', { name: 'Settings menu', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Help & documentation', exact: true }).click()
  return page.getByRole('dialog', { name: 'Documentation', exact: true })
}
test('descriptions expand in place while info hovers remain available in both toggle states', async ({ page }) => {
  await setup(page)
  await page.getByRole('button', { name: 'Explanations', exact: true }).click()
  await page.getByRole('button', { name: 'Edit Envelope', exact: true }).click()
  const modal = page.getByRole('dialog', { name: /^Envelope/ })
  const info = modal.getByRole('button', { name: 'About ADSR envelope', exact: true })
  await expect(info).toBeVisible()
  const description = modal.locator('.help-inline').filter({ hasText: 'Sample-timed linear ADSR' })
  await expect(description).toBeVisible()
  expect((await description.boundingBox())!.y).toBeGreaterThan((await modal.locator('.modal-header').boundingBox())!.y)
  const heading = await modal.locator('#node-modal-title').boundingBox(), icon = await info.boundingBox()
  expect(Math.abs(heading!.y - icon!.y)).toBeLessThan(35)
  await info.hover()
  const tip = page.getByRole('tooltip')
  await expect(tip).toContainText('Sample-timed linear ADSR')
  expect(await tip.evaluate(el => {
    const r = el.getBoundingClientRect()
    return el.matches(':popover-open') && el.contains(document.elementFromPoint(r.left + 12, r.top + 12)) && !!el.closest('dialog')
  })).toBeTruthy()
  await page.screenshot({ path: '/tmp/pr0-info-modal.png' })
  await info.focus()
  await page.keyboard.press('Escape')
  await expect(tip).toHaveCount(0)
  await expect(modal).toBeVisible()
  await page.keyboard.press('i')
  await expect(modal.locator('.help-inline')).toHaveCount(0)
  await expect(info).toBeVisible()
  await page.mouse.move(0, 0)
  await info.hover()
  await expect(tip).toContainText('Sample-timed linear ADSR')
  await page.keyboard.press('i')
  await expect(info).toBeVisible()
  await expect(description).toBeVisible()
  await modal.getByLabel('Node name', { exact: true }).fill('i')
  await expect(description).toBeVisible()
  await expect(info).toBeVisible()
  await page.getByRole('button', { name: 'Close parameters' }).click()
  await page.getByRole('button', { name: 'Explanations', exact: true }).click()
  await expect(page.locator('.help-inline')).toHaveCount(0)
  await expect(page.locator('.patch-node .help-icon')).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('button', { name: 'Explanations', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await page.getByRole('button', { name: 'Explanations', exact: true }).click()
  await page.getByRole('button', { name: 'Settings menu', exact: true }).click()
  await page.getByRole('menuitem', { name: 'System settings', exact: true }).click()
  await expect(page.getByLabel('Global sample rate (Hz)', { exact: true })).toBeVisible()
  await expect(page.getByLabel('DSP block size', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'About DSP block size', exact: true }).focus()
  await expect(page.getByRole('tooltip')).toContainText('driver chooses its callback')
})
test('every authored node example renders real graph components without engine requests', async ({ page }) => {
  test.setTimeout(240000)
  page.setDefaultTimeout(10000)
  const projectId = await setup(page)
  const errors: string[] = [], mutations: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const catalog = await (await page.request.get('/api/catalog')).json()
  const guide = await docs(page)
  for (const [button, heading] of [['Architecture', 'Architecture: server and clients'], ['init.sh · Server setup', 'init.sh: set up a server'], ['build.sh · Desktop build', 'build.sh: build the desktop app']]) {
    await guide.getByRole('button', { name: button, exact: true }).click()
    await expect(guide.getByRole('heading', { name: heading, exact: true })).toBeVisible()
  }
  await guide.getByRole('button', { name: 'Quick start', exact: true }).click()
  await guide.screenshot({ path: '/tmp/pr0-quick-start.png' })
  await guide.getByRole('button', { name: /^All nodes/ }).click()
  page.on('request', request => { if (request.method() !== 'GET' || request.url().includes('/preview?')) mutations.push(request.url()) })
  for (const node of catalog) {
    expect(node.documentation, node.kind).toBeTruthy()
    await guide.getByLabel('Search node documentation').fill(node.label)
    const card = guide.locator('.node-doc-card').filter({ has: page.getByRole('heading', { name: node.label, exact: true }) })
    await card.getByRole('button', { name: 'Show example graph' }).click()
    const example = page.getByRole('dialog', { name: `${node.label} example graph`, exact: true })
    await expect(example.locator('.vue-flow__node')).toHaveCount(node.documentation.graph.nodes.filter((n: any) => n.kind !== 'subgraph').length)
    await expect(example.locator('.vue-flow__edge')).toHaveCount(node.documentation.graph.edges.length)
    if (['adsr', 'spectral_curve', 'channel_split', 'midi_to_control'].includes(node.kind)) {
      await example.locator('.vue-flow__node').first().waitFor()
      await example.screenshot({ path: `/tmp/pr0-example-${node.kind}.png` })
    }
    if (node.kind === 'adsr') {
      await example.getByRole('button', { name: 'Edit Plucked envelope', exact: true }).click()
      const settings = example.getByRole('region', { name: 'Plucked envelope example settings' })
      await expect(settings).toContainText('5 ms')
      await expect(settings).toContainText('Sample-timed linear ADSR')
      await expect(example.locator('.patch-node .help-icon')).toHaveCount(0)
    }
    await example.getByRole('button', { name: 'Close example graph', exact: true }).click()
  }
  expect(errors).toEqual([])
  expect(mutations).toEqual([])
  const project = (await (await page.request.get(`/api/projects/${projectId}`)).json()).project
  expect(project.graph.nodes).toHaveLength(1)
})
test('standalone documentation and touch info work on a narrow viewport', async ({ page }) => {
  await setup(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/?help=1')
  await expect(page.getByRole('heading', { name: 'Quick start', exact: true })).toBeVisible()
  await page.getByRole('button', { name: /^All nodes/ }).click()
  await page.getByLabel('Search node documentation').fill('ADSR envelope')
  await page.locator('.node-doc-card').filter({ has: page.getByRole('heading', { name: 'ADSR envelope', exact: true }) }).getByRole('button', { name: 'Show example graph' }).click()
  const example = page.getByRole('dialog', { name: 'ADSR envelope example graph', exact: true })
  await expect(example.locator('.vue-flow__node').first()).toBeVisible()
  await expect(example.locator('.patch-node .help-icon')).toHaveCount(0)
  await example.getByRole('button', { name: 'Close example graph', exact: true }).click()
  // Descriptions live in Options: touch the info button in the node modal on a phone-width viewport.
  await page.goto('/')
  await page.getByRole('button', { name: 'Edit Envelope', exact: true }).click()
  const modal = page.getByRole('dialog', { name: /^Envelope/ })
  const info = modal.getByRole('button', { name: 'About ADSR envelope', exact: true })
  await info.dispatchEvent('pointerenter', { pointerType: 'touch' })
  await info.click()
  const tip = page.getByRole('tooltip')
  await expect(tip).toBeVisible()
  const box = await tip.boundingBox()
  expect(box!.x).toBeGreaterThanOrEqual(0)
  expect(box!.x + box!.width).toBeLessThanOrEqual(390)
  expect(box!.y + box!.height).toBeLessThanOrEqual(844)
  await page.screenshot({ path: '/tmp/pr0-docs-phone.png' })
  await modal.locator('#node-modal-title').click()
  await expect(tip).toHaveCount(0)
})

test('graph nodes keep descriptions off the canvas in both toggle states; Options carries them', async ({ page }) => {
  await setup(page)
  const node = page.locator('.patch-node').first()
  const before = await node.evaluate(el => (el as HTMLElement).offsetHeight)
  await expect(node.locator('button[aria-label^="About "]')).toHaveCount(0)
  await page.getByRole('button', { name: 'Explanations', exact: true }).click()
  await expect(node.locator('.help-inline')).toHaveCount(0)
  expect(await node.evaluate(el => (el as HTMLElement).offsetHeight)).toBe(before)
  await node.getByRole('button', { name: 'Edit Envelope', exact: true }).click()
  const modal = page.getByRole('dialog')
  await expect(modal.locator('.help-inline').filter({ hasText: 'Sample-timed linear ADSR' })).toBeVisible()
  await page.getByRole('button', { name: 'Close parameters' }).click()
  await page.getByRole('button', { name: 'Explanations', exact: true }).click()
})
test('sample credits are readable from the documentation', async ({ page }) => {
  await setup(page)
  const guide = await docs(page)
  await guide.getByRole('button', { name: 'Sample credits', exact: true }).click()
  await expect(guide.getByRole('heading', { name: 'Bundled sample credits', exact: true })).toBeVisible()
  await expect(guide.locator('.credits-guide')).toContainText('menegass')
  await expect(guide.locator('.credits-guide')).toContainText('VSCO 2 Community Edition')
  await page.goto('/?help=1&topic=credits')
  await expect(page.getByRole('heading', { name: 'Bundled sample credits', exact: true })).toBeVisible()
})
