import {test,expect} from '@playwright/test'
test('polyphonic synth MIDI inputs, FM waveforms, driven frequencies and multichannel output',async({page})=>{
  const headers={'X-Pr0former':'1'},status=await(await page.request.get('/api/status')).json()
  await page.request.post(`/api/${status.bootstrap?'register':'login'}`,{headers,data:{username:'browser-test',password:'test1234'}})
  let p=await(await page.request.post('/api/projects',{headers,data:{name:'FM instrument',mode:'freeform'}})).json()
  const part=structuredClone(p.parts[0]);p.parts=[];p.graph={nodes:[],edges:[]}
  expect((await page.request.put(`/api/projects/${p.id}`,{headers,data:p})).ok()).toBe(true)
  const load=async()=>(await(await page.request.get(`/api/projects/${p.id}`)).json()).project
  await page.goto('/')
  await page.getByLabel('Search nodes').fill('Polyphonic FM synth')
  await page.locator('.node-library-content .library-node').filter({hasText:'Polyphonic FM synth'}).click()
  await expect.poll(async()=>(await load()).graph.nodes.length).toBe(1)
  p=await load();const fm=p.graph.nodes[0];expect(fm.channels).toBe(1)
  await page.getByRole('button',{name:'Edit Polyphonic FM synth',exact:true}).click()
  await page.getByLabel('Carrier waveform',{exact:true}).selectOption('2')
  await expect.poll(async()=>(await load()).graph.nodes[0].parameters.carrier_waveform).toBe(2)
  await page.getByLabel('Modulator waveform',{exact:true}).selectOption('1')
  await expect.poll(async()=>(await load()).graph.nodes[0].parameters.modulator_waveform).toBe(1)
  await page.getByLabel('Audio channels',{exact:true}).selectOption('4')
  await expect.poll(async()=>(await load()).graph.nodes[0].channels).toBe(4)
  await page.getByRole('button',{name:'Close parameters'}).click()
  p=await load();p.graph.nodes[0].parameters.release=1
  const node=(id:string,kind:string,channels:number,parameters={})=>({id,kind,label:id,x:0,y:0,channels,parameters})
  p.graph.nodes.push(node('Keys','piano',1),node('Carrier','value',1,{value:440}),node('Modulator','value',1,{value:880}),node('FM meter','audio_visualizer',4,{size:256}),node('Sine','synth',1,{release:1}),node('Sine meter','audio_visualizer',1,{size:256}))
  for(const target of [fm.id,'Sine'])for(const port of ['pitch','velocity','gate','trigger','note_off'])p.graph.edges.push({id:`${target}-${port}`,source:'Keys',source_port:port,target,target_port:port})
  for(const [source,source_port,target,target_port] of [['Carrier','out',fm.id,'carrier_frequency'],['Modulator','out',fm.id,'modulator_frequency'],[fm.id,'out','FM meter','in'],['Sine','out','Sine meter','in']])p.graph.edges.push({id:`${source}-${target}`,source,source_port,target,target_port})
  part.instrument_node=fm.id;p.parts=[part]
  expect((await page.request.put(`/api/projects/${p.id}`,{headers,data:p})).ok()).toBe(true)
  p=await load();const invalid=structuredClone(p);invalid.graph.nodes[0].parameters.modulator_waveform=.5
  expect((await page.request.put(`/api/projects/${p.id}`,{headers,data:invalid})).status()).toBe(400)
  let latest:any
  page.on('websocket',s=>s.on('framereceived',({payload})=>{const m=JSON.parse(String(payload));if(m.type==='telemetry')latest=m}))
  await page.reload()
  await page.getByRole('button',{name:'Enable audio engine',exact:true}).click()
  const note=async(pitch:number,velocity:number)=>expect((await page.request.put(`/api/projects/${p.id}/piano`,{headers,data:{node:'Keys',pitch,velocity}})).ok()).toBe(true)
  const peak=(id:string)=>Math.max(...(latest?.visualizations?.[id]?.channels?.[0]?.magnitude||[0]))
  await note(60,100);await note(64,100)
  await expect.poll(()=>peak('FM meter')).toBeGreaterThan(.01)
  await expect.poll(()=>peak('Sine meter')).toBeGreaterThan(.01)
  expect(latest.running).toBe(false)
  expect(latest.visualizations['FM meter'].channels).toHaveLength(4)
  expect(latest.visualizations['FM meter'].channels[0].magnitude).toEqual(latest.visualizations['FM meter'].channels[3].magnitude)
  await page.getByRole('button',{name:'Edit Polyphonic FM synth',exact:true}).click()
  await expect(page.getByRole('dialog').getByText('Carrier / out',{exact:true})).toBeVisible()
  await expect(page.getByRole('dialog').getByText('Modulator / out',{exact:true})).toBeVisible()
  await page.screenshot({path:'test-results/fm-synth.png'})
  await page.getByRole('button',{name:'Close parameters'}).click()
  await note(60,0)
  await expect.poll(()=>peak('FM meter')).toBeGreaterThan(.01)
  await note(64,0)
  await expect.poll(()=>peak('FM meter')).toBeLessThan(.001)
  await expect.poll(()=>peak('Sine meter')).toBeLessThan(.001)
  await page.getByRole('button',{name:'Disable audio engine',exact:true}).click()
  await page.getByRole('button',{name:'Score & parts',exact:true}).click()
  await expect(page.getByLabel('Instrument / input').locator('option',{hasText:'Polyphonic FM synth'})).toHaveCount(1)
})
