import {test,expect} from '@playwright/test'
function wave(){const rate=48000,frames=rate,channels=2,b=Buffer.alloc(44+frames*channels*2);b.write('RIFF',0);b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(channels,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*channels*2,28);b.writeUInt16LE(channels*2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(frames*channels*2,40);for(let i=0;i<frames;i++)for(let ch=0;ch<channels;ch++)b.writeInt16LE(Math.round(Math.sin(2*Math.PI*440*i/rate)*12000),44+(i*channels+ch)*2);return b}
test('granular sample MIDI feeds live convolution and pitch shifting with modal controls',async({page})=>{
  const headers={'X-Pr0former':'1'},status=await(await page.request.get('/api/status')).json()
  await page.request.post(`/api/${status.bootstrap?'register':'login'}`,{headers,data:{username:'browser-test',password:'test1234'}})
  const p=await(await page.request.post('/api/projects',{headers,data:{name:'Granular processing',mode:'freeform'}})).json()
  const upload=await page.request.post(`/api/projects/${p.id}/samples`,{headers,multipart:{sample:{name:'Grain.wav',mimeType:'audio/wav',buffer:wave()}}});expect(upload.ok()).toBe(true)
  const sample=await upload.json();expect((await page.request.put(`/api/projects/${p.id}/samples/${sample.id}`,{headers,data:{...sample,root_note:69}})).ok()).toBe(true)
  const n=(id:string,kind:string,x:number,y=0,parameters={})=>({id,kind,label:id,x,y,channels:2,parameters})
  const edge=(id:string,source:string,source_port:string,target:string,target_port:string)=>({id,source,source_port,target,target_port})
  p.parts=[];p.graph={nodes:[n('Keys','piano',0),n('Grains','granular_synth',350),n('Response','oscillator',350,650,{frequency:440,amplitude:.5}),n('Convolve','convolution',700),n('Shift','granular_pitch_shift',1000),n('Meter','audio_visualizer',1300,0,{size:1024})],edges:[edge('a','Grains','out','Convolve','a'),edge('b','Response','out','Convolve','b'),edge('shift','Convolve','out','Shift','in'),edge('meter','Shift','out','Meter','in')]}
  for(const port of ['pitch','velocity','gate','trigger','note_off'])p.graph.edges.push(edge(port,'Keys',port,'Grains',port))
  expect((await page.request.put(`/api/projects/${p.id}`,{headers,data:p})).ok()).toBe(true)
  const load=async()=>(await(await page.request.get(`/api/projects/${p.id}`)).json()).project
  let latest:any;page.on('websocket',s=>s.on('framereceived',({payload})=>{const m=JSON.parse(String(payload));if(m.type==='telemetry')latest=m}))
  await page.goto('/');await page.getByRole('button',{name:'Edit Grains',exact:true}).click()
  await page.getByLabel('Project sample',{exact:true}).selectOption(String(sample.asset))
  await expect.poll(async()=>(await load()).graph.nodes.find((n:any)=>n.id==='Grains').parameters.root_note).toBe(69)
  await expect(page.locator('#param-root_note')).toHaveValue('69')
  await expect(page.locator('#param-density')).toBeVisible();await expect(page.locator('#param-grain_ms')).toBeVisible()
  await page.getByRole('button',{name:'Close parameters',exact:true}).click()
  await page.getByRole('button',{name:'Enable audio engine',exact:true}).click()
  const note=async(velocity:number)=>expect((await page.request.put(`/api/projects/${p.id}/piano`,{headers,data:{node:'Keys',pitch:69,velocity}})).ok()).toBe(true)
  const energy=()=>Math.max(...(latest?.visualizations.Meter.channels[0].magnitude||[0]))
  await note(100);await expect.poll(energy).toBeGreaterThan(.001)
  expect(latest.running).toBe(false)
  await page.getByRole('button',{name:'Edit Shift',exact:true}).click()
  await page.locator('#param-semitones').fill('12');await page.locator('#param-semitones').press('Tab')
  await expect.poll(()=>latest?.values.Shift.semitones).toBe(12)
  await page.getByRole('button',{name:'Close parameters',exact:true}).click()
  await expect.poll(energy).toBeGreaterThan(.001)
  await page.getByRole('button',{name:'Edit Convolve',exact:true}).click()
  await page.getByLabel('Window size',{exact:true}).selectOption('512')
  await page.getByRole('button',{name:'Close parameters',exact:true}).click()
  await expect.poll(energy).toBeGreaterThan(.001)
  const invalid=await load();invalid.graph.nodes.find((n:any)=>n.id==='Convolve').parameters.window=300
  expect((await page.request.put(`/api/projects/${p.id}`,{headers,data:invalid})).status()).toBe(400)
  await note(0);await expect.poll(energy).toBeLessThan(.00001)
  await page.screenshot({path:'test-results/granular-processing.png'})
  await page.getByRole('button',{name:'Disable audio engine',exact:true}).click()
})
