import {test,expect} from '@playwright/test'
test('Granular Cloud preserves numeric/sample controls, scans a live source and plays without MIDI',async({page})=>{
 const headers={'X-Pr0former':'1'},status=await(await page.request.get('/api/status')).json()
 await page.request.post(`/api/${status.bootstrap?'register':'login'}`,{headers,data:{username:'browser-test',password:'test1234'}})
 let p=await(await page.request.post('/api/projects',{headers,data:{name:'Granular cloud',mode:'freeform'}})).json(),url=`/api/projects/${p.id}`
 const sample=await(await page.request.post(`${url}/samples/bundled-kick/add`,{headers,data:{}})).json()
 const n=(id:string,kind:string,x:number,y:number,parameters={})=>({id,kind,label:id,x,y,channels:2,parameters})
 const edge=(source:string,source_port:string,target:string,target_port:string)=>({id:`${source}-${target}-${target_port}`,source,source_port,target,target_port})
 p.parts=[];p.graph={nodes:[n('Center','value',0,0,{value:0.25}),n('Cloud','granular_cloud',300,0,{asset:sample.asset}),n('Listen','monitor_output',820,0),n('Keys','piano',0,500)],edges:[edge('Center','out','Cloud','position'),edge('Cloud','out','Listen','in')]}
 expect((await page.request.put(url,{headers,data:p})).ok()).toBe(true)
 const read=async()=>(await(await page.request.get(url)).json()).project
 let latest:any,peak=0
 page.on('websocket',socket=>socket.on('framereceived',({payload})=>{const event=JSON.parse(String(payload));if(event.type==='telemetry'){latest=event;peak=Math.max(peak,event.values?.Cloud?._peak||0)}}))
 await page.addInitScript(()=>localStorage.setItem('pr0former.help','hidden'))
 await page.goto('/');const cloud=page.locator('.vue-flow__node[data-id="Cloud"]')
 await expect(cloud.locator('[data-handleid="midi"]')).toHaveCount(0)
 await expect(cloud.getByText('Cloud center',{exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Enable audio engine',exact:true}).click()
 await expect.poll(()=>peak).toBeGreaterThan(0.0001);expect(latest.running).toBe(false)
 await expect.poll(()=>latest?.values?.Cloud?.position).toBe(0.25)
 p=await read();expect((await page.request.put(`${url}/parameter`,{headers,data:{node:'Center',parameter:'value',value:0.8,revision:p.revision}})).ok()).toBe(true)
 await expect.poll(()=>latest?.values?.Cloud?.position).toBe(0.8)
 await page.getByRole('button',{name:'Edit Cloud',exact:true}).click()
 const modal=page.getByRole('dialog',{name:/^Cloud/})
 await expect(modal.getByLabel('Project sample',{exact:true})).toHaveValue(sample.name)
 await expect(modal.getByText('Center / out',{exact:true})).toBeVisible()
 for(const name of ['Spray','Grain duration','Density','Amplitude','Release','Root MIDI note'])await expect(modal.getByRole('spinbutton',{name,exact:true})).toBeVisible()
 const amp=modal.getByRole('spinbutton',{name:'Amplitude',exact:true});await amp.fill('0');await amp.press('Tab')
 await expect.poll(()=>latest?.values?.Cloud?._peak).toBe(0)
 await page.screenshot({path:'/tmp/pr0-granular-cloud-options.png'})
 await page.getByRole('button',{name:'Close parameters'}).click()
 const invalid=await read();invalid.graph.edges.push(edge('Keys','midi','Cloud','midi'));expect((await page.request.put(url,{headers,data:invalid})).status()).toBe(400)
 p=await read();p.graph.edges=p.graph.edges.filter((e:any)=>e.target_port!=='position');expect((await page.request.put(url,{headers,data:p})).ok()).toBe(true)
 p=await read();expect((await page.request.put(`${url}/parameter`,{headers,data:{node:'Cloud',parameter:'position',value:1.1,revision:p.revision}})).status()).toBe(400)
 const catalog=await(await page.request.get('/api/catalog')).json(),a=catalog.find((d:any)=>d.kind==='granular_synth'),b=catalog.find((d:any)=>d.kind==='granular_cloud')
 expect(b.inputs.map((p:any)=>p.id)).toEqual(a.inputs.filter((p:any)=>p.signal!=='midi').map((p:any)=>p.id))
 expect(b.parameters.map((p:any)=>p.id)).toEqual(a.parameters.map((p:any)=>p.id))
 expect(b.documentation.explanation).toContain('continuous')
 await page.getByRole('button',{name:'Disable audio engine',exact:true}).click()
})
