import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { join } from 'node:path'

test('private/public library permissions, immutable versions, forks and bundled samples',async({request,playwright})=>{
  const headers={'X-Pr0former':'1'},status=await(await request.get('/api/status')).json()
  await request.post(`/api/${status.bootstrap?'register':'login'}`,{headers,data:{username:'browser-test',password:'test1234'}})
  let p=await(await request.post('/api/projects',{headers,data:{name:'Library origin',mode:'freeform'}})).json()
  const guest=await playwright.request.newContext({baseURL:'http://127.0.0.1:3101'})
  const invitation=await(await request.post(`/api/projects/${p.id}/invite`,{headers,data:{role:'performer'}})).json()
  await guest.post('/api/register',{headers,data:{username:'library-guest',password:'test5678',invite:invitation.token}})
  await guest.post('/api/join',{headers,data:{token:invitation.token}})
  const pcm=Buffer.alloc(44+480*2);pcm.write('RIFF');pcm.writeUInt32LE(pcm.length-8,4);pcm.write('WAVEfmt ',8);pcm.writeUInt32LE(16,16);pcm.writeUInt16LE(1,20);pcm.writeUInt16LE(1,22);pcm.writeUInt32LE(48000,24);pcm.writeUInt32LE(96000,28);pcm.writeUInt16LE(2,32);pcm.writeUInt16LE(16,34);pcm.write('data',36);pcm.writeUInt32LE(960,40)
  const sample=await(await request.post(`/api/projects/${p.id}/samples`,{headers,multipart:{sample:{name:'sample.wav',mimeType:'audio/wav',buffer:pcm}}})).json()
  const n=(id:string,kind:string,parent:string|null,parameters={})=>({id,kind,parent,label:id,x:0,y:0,channels:1,parameters})
  p.parts=[];p.graph={nodes:[n('Pack','subgraph',null),n('Value','value','Pack',{value:1}),n('Sample','sample','Pack',{asset:sample.asset}),n('Grains','granular_synth','Pack',{asset:sample.asset})],edges:[]}
  p=await(await request.put(`/api/projects/${p.id}`,{headers,data:p})).json()
  const save=(who:any,options={})=>who.post(`/api/projects/${p.id}/subgraphs`,{headers,data:{node:'Pack',revision:p.revision,name:'Shared patch',public:false,...options}})
  const first=await(await save(request)).json()
  expect(first.version).toBe(1)
  expect((await guest.get(`/api/subgraphs/${first.id}/versions/1`)).status()).toBe(404)
  expect((await(await guest.get('/api/subgraphs')).json()).some((e:any)=>e.id===first.id)).toBe(false)
  expect((await save(guest)).status()).toBe(403)
  p.graph.nodes.find((n:any)=>n.id==='Value').parameters.value=2
  p=await(await request.put(`/api/projects/${p.id}`,{headers,data:p})).json()
  const second=await(await save(request,{library_id:first.id,public:true})).json()
  expect(second.version).toBe(2)
  expect((await guest.get(`/api/subgraphs/${first.id}/versions/1`)).status()).toBe(404)
  const exposed=(await(await guest.get('/api/subgraphs')).json()).find((e:any)=>e.id===first.id)
  expect(exposed.versions.map((v:any)=>v.version)).toEqual([2])
  expect((await save(request,{library_id:first.id,public:false})).status()).toBe(400)
  let dest=await(await guest.post('/api/projects',{headers,data:{name:'Library consumer',mode:'freeform'}})).json()
  dest=await(await guest.post(`/api/projects/${dest.id}/subgraphs/insert`,{headers,data:{library_id:first.id,version:2,revision:dest.revision,parent:null,x:150,y:250}})).json()
  const root=dest.graph.nodes.find((n:any)=>n.library?.id===first.id)
  expect(root.library.version).toBe(2);expect(root.x).toBe(150)
  const imported=dest.graph.nodes.find((n:any)=>n.kind==='sample')
  expect(imported.parameters.asset).not.toBe(sample.asset)
  expect(dest.graph.nodes.find((n:any)=>n.kind==='granular_synth').parameters.asset).toBe(imported.parameters.asset)
  expect(await readFile(join(process.env.PR0_TEST_DATA!,'samples',dest.id,`${imported.parameters.asset}.wav`))).toEqual(await readFile(join(process.env.PR0_TEST_DATA!,'samples',p.id,`${sample.asset}.wav`)))
  p.graph.nodes.find((n:any)=>n.id==='Value').parameters.value=3
  p=await(await request.put(`/api/projects/${p.id}`,{headers,data:p})).json()
  expect((await(await save(request,{library_id:first.id,public:true})).json()).version).toBe(3)
  const old=await(await guest.get(`/api/subgraphs/${first.id}/versions/2`)).json()
  expect(old.nodes.find((n:any)=>n.id==='Value').parameters.value).toBe(2)
  const stored=(await(await guest.get(`/api/projects/${dest.id}`)).json()).project
  expect(stored.graph.nodes.find((n:any)=>n.kind==='value'&&n.parent===root.id).parameters.value).toBe(2)
  expect((await guest.post(`/api/projects/${dest.id}/subgraphs`,{headers,data:{node:root.id,revision:dest.revision,name:'Hijack',public:true,library_id:first.id}})).status()).toBe(403)
  const fork=await(await guest.post(`/api/projects/${dest.id}/subgraphs`,{headers,data:{node:root.id,revision:dest.revision,name:'My private variant',public:false}})).json()
  expect(fork.id).not.toBe(first.id)
  expect((await request.get(`/api/subgraphs/${fork.id}/versions/1`)).status()).toBe(404)
  await guest.dispose()
})

test('library panel save, version selection, drag placement and multiple-node selection',async({page})=>{
  // LAN HTTP exposes getRandomValues but may not expose randomUUID.
  await page.addInitScript(() => Object.defineProperty(crypto, 'randomUUID', { configurable: true, value: undefined }))
  const headers={'X-Pr0former':'1'}, status=await(await page.request.get('/api/status')).json()
  await page.request.post(`/api/${status.bootstrap?'register':'login'}`,{headers,data:{username:'browser-test',password:'test1234'}})
  let p=await(await page.request.post('/api/projects',{headers,data:{name:'Library UI',mode:'freeform'}})).json()
  p.parts=[];p.graph={nodes:[{id:'Group',kind:'subgraph',label:'UI pack',parent:null,x:0,y:0,channels:2,parameters:{}},{id:'Leaf',kind:'value',label:'Leaf',parent:'Group',x:0,y:0,channels:2,parameters:{value:5}}],edges:[]}
  p=await(await page.request.put(`/api/projects/${p.id}`,{headers,data:p})).json()
  const load=async()=>(await(await page.request.get(`/api/projects/${p.id}`)).json()).project
  await page.goto('/')
  await expect(page.getByText('Click to add. Connect to explore.',{exact:false})).toHaveCount(0)
  await expect(page.getByRole('button',{name:'Node library',exact:true})).toHaveAttribute('aria-expanded','true')
  await page.locator('.vue-flow__node[data-id="Group"] .patch-node').click({button:'right'})
  await page.getByRole('menuitem',{name:'Save to subgraph library',exact:true}).click()
  await page.getByLabel('Library name').fill('UI reusable')
  await page.getByLabel('Make public for all users').check()
  await page.getByRole('button',{name:'Save to library',exact:true}).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('button',{name:'Insert UI reusable',exact:true})).toBeVisible()
  await expect.poll(async()=>(await load()).graph.nodes.find((n:any)=>n.id==='Group').library?.version).toBe(1)
  await page.locator('.vue-flow__node[data-id="Group"] .patch-node').click({button:'right'})
  await page.getByRole('menuitem',{name:'Save to subgraph library',exact:true}).click()
  await expect(page.getByLabel('Make public for all users')).toBeChecked()
  await expect(page.getByLabel('Make public for all users')).toBeDisabled()
  await page.getByRole('button',{name:'Save new version',exact:true}).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByLabel('Version of UI reusable').locator('option')).toHaveCount(2)
  await page.getByLabel('Version of UI reusable').selectOption('1')
  const canvas=page.locator('.graph-canvas'), rect=(await canvas.boundingBox())!
  await page.getByRole('button',{name:'Insert UI reusable',exact:true}).dragTo(canvas,{targetPosition:{x:rect.width*0.75,y:rect.height*0.55}})
  await expect.poll(async()=>(await load()).graph.nodes.length).toBe(4)
  const copy=(await load()).graph.nodes.find((n:any)=>n.kind==='subgraph'&&n.id!=='Group')
  expect(copy.library.version).toBe(1)
  await page.getByRole('button',{name:'Node library',exact:true}).click()
  await expect(page.getByRole('button',{name:'Subgraph library',exact:true})).toHaveAttribute('aria-expanded','false')
  await page.getByLabel('Search nodes').fill('Value')
  await page.locator('.node-library-content>.library-list .library-node').filter({hasText:'Value'}).first().dragTo(canvas,{targetPosition:{x:rect.width*0.3,y:rect.height*0.93}})
  await expect.poll(async()=>(await load()).graph.nodes.length).toBe(5)
  const placed=(await load()).graph.nodes.find((n:any)=>n.kind==='value'&&!n.parent)
  // Both drops use graph coordinates derived from the requested canvas location.
  const box=(await page.locator(`.vue-flow__node[data-id="${placed.id}"]`).boundingBox())!
  expect(Math.abs(box.x-(rect.x+rect.width*0.3))).toBeLessThan(4)
  expect(Math.abs(box.y-(rect.y+rect.height*0.93))).toBeLessThan(4)
  await page.getByRole('button',{name:'Hide node library',exact:true}).click()
  await expect(page.getByRole('region',{name:'Subgraph library'})).toHaveCount(0)
  await page.getByRole('button',{name:'Library',exact:true}).click()
  await expect(page.getByRole('region',{name:'Subgraph library'})).toBeVisible()
  await page.locator('.vue-flow__controls-fitview').click()
  await page.screenshot({path:'../docs/subgraph-library.png'})
  const a=page.locator('.vue-flow__node[data-id="Group"]'),b=page.locator(`.vue-flow__node[data-id="${copy.id}"]`)
  await a.locator('.patch-node').click({position:{x:30,y:45}})
  await page.keyboard.down('Control');await b.locator('.patch-node').click({position:{x:30,y:45}});await page.keyboard.up('Control')
  await expect(page.locator('.vue-flow__node.selected')).toHaveCount(2)
  const before=await load(), ar=(await a.boundingBox())!
  await page.mouse.move(ar.x+30,ar.y+45);await page.mouse.down();await page.mouse.move(ar.x+65,ar.y+70,{steps:6});await page.mouse.up()
  await expect.poll(async()=>(await load()).graph.nodes.find((n:any)=>n.id==='Group').x).not.toBe(before.graph.nodes.find((n:any)=>n.id==='Group').x)
  const after=await load(),dx=after.graph.nodes.find((n:any)=>n.id==='Group').x-before.graph.nodes.find((n:any)=>n.id==='Group').x
  expect(after.graph.nodes.find((n:any)=>n.id===copy.id).x-before.graph.nodes.find((n:any)=>n.id===copy.id).x).toBeCloseTo(dx)
  // A drag on empty canvas selects a box; then Backspace removes all selected subtrees.
  await page.locator('.vue-flow__controls-fitview').click()
  // Leave room around the nodes so the marquee starts clear of floating canvas controls.
  await page.locator('.vue-flow__controls-zoomout').click()
  const boxes=await page.locator('.vue-flow__node').evaluateAll(nodes=>nodes.map(n=>{const r=n.getBoundingClientRect();return{x:r.x,y:r.y,right:r.right,bottom:r.bottom}}))
  const left=Math.min(...boxes.map(r=>r.x))-10,top=Math.min(...boxes.map(r=>r.y))-10,right=Math.max(...boxes.map(r=>r.right))+10,bottom=Math.max(...boxes.map(r=>r.bottom))+10
  await expect.poll(()=>page.evaluate(({left,bottom})=>document.elementFromPoint(left,bottom)?.classList.contains('vue-flow__pane'),{left,bottom})).toBe(true)
  await page.mouse.move(left,bottom);await page.mouse.down();await page.mouse.move(right,top,{steps:10});await page.mouse.up()
  await expect(page.locator('.vue-flow__node.selected')).toHaveCount(3)
  await a.locator('.patch-node').focus()
  await page.keyboard.press('Backspace')
  await expect.poll(async()=>(await load()).graph.nodes.length).toBe(0)
  await page.getByLabel('Search nodes').fill('Value')
  await page.locator('.library-node').filter({hasText:'Value'}).first().click()
  await expect.poll(async()=>(await load()).graph.nodes.length).toBe(1)
  await expect(page.locator('.library-node').first()).toBeEnabled()
  const malformed = await page.evaluateHandle(() => { const data = new DataTransfer(); data.setData('application/pr0former', '{broken'); return data })
  await canvas.locator('.vue-flow').dispatchEvent('drop', { dataTransfer: malformed })
  await expect(page.getByRole('alert')).toContainText('Invalid library drag data')
  expect((await load()).graph.nodes.length).toBe(1)

})
