import { test, expect } from '@playwright/test'
test('footer tempo editing and compact graphical slider previews, overrides and layout', async ({ page }) => {
  const headers={'X-Pr0former':'1'}, status=await(await page.request.get('/api/status')).json()
  await page.request.post(`/api/${status.bootstrap?'register':'login'}`,{headers,data:{username:'browser-test',password:'test1234'}})
  if(status.active_project)await page.request.post(`/api/projects/${status.active_project}/transport`,{headers,data:{action:'deactivate'}})
  const p=await(await page.request.post('/api/projects',{headers,data:{name:'Live controls',mode:'freeform'}})).json()
  const n=(id:string,kind:string,x:number,y:number,parameters={},control_value?:number)=>({id,kind,label:id,x,y,channels:1,parameters,control_value})
  p.parts=[];p.graph={nodes:[n('Input','control_input',0,0,{mode:3,min:0,max:100,changes_only:1},20),n('Sliders','sliders',300,0,{count:4,orientation:1,min:0,max:100}),n('Source','value',0,260,{value:20}),n('Clock','clock',650,0)],edges:[{id:'panel',source:'Input',source_port:'out',target:'Sliders',target_port:'slider_1'},{id:'input',source:'Source',source_port:'out',target:'Input',target_port:'in'}]}
  const url=`/api/projects/${p.id}`,read=async()=>(await(await page.request.get(url)).json()).project
  expect((await page.request.put(url,{headers,data:p})).ok()).toBe(true)
  let latest:any;let previewCount=0;let controlRequests=0
  page.on('websocket',socket=>{socket.on('framereceived',({payload})=>{const m=JSON.parse(String(payload));if(m.type==='telemetry')latest=m});socket.on('framesent',({payload})=>{if(JSON.parse(String(payload)).type==='graph_control')previewCount++})})
  page.on('request',r=>{if(r.url().endsWith('/control')&&r.method()==='PUT')controlRequests++})
  await page.goto('/');await page.getByRole('button',{name:'Enable audio engine',exact:true}).click()
  await expect.poll(()=>latest?.values?.Sliders?._control_1).toBe(20)
  const tempo=page.locator('#tempo')
  await tempo.focus();await tempo.fill('137');await page.waitForTimeout(250)
  await expect(tempo).toHaveValue('137');await tempo.press('Enter')
  await expect.poll(()=>latest?.bpm).toBe(137)
  const input=page.getByLabel('Input value',{exact:true}), fader=page.getByRole('slider',{name:'Input slider',exact:true})
  await expect(input).toBeEnabled();await expect(fader).toBeVisible()
  await page.waitForTimeout(400)
  const revision=(await read()).revision,box=(await fader.boundingBox())!
  await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down()
  await page.mouse.move(box.x+box.width/2+40,box.y+box.height/2,{steps:8})
  await expect.poll(()=>latest?.values?.Sliders?._control_1).toBeGreaterThan(40)
  expect(previewCount).toBeGreaterThan(0);expect(controlRequests).toBe(0)
  expect((await read()).revision).toBe(revision)
  await expect(page.locator('.library-node').first()).toBeEnabled()
  await page.mouse.up()
  await expect.poll(async()=>(await read()).graph.nodes.find((n:any)=>n.id==='Input').control_value).toBeGreaterThan(40)
  expect(controlRequests).toBe(1)
  await input.fill('7.5');await input.press('Tab')
  await expect.poll(()=>latest?.values?.Sliders?._control_1).toBe(7.5)
  await page.waitForTimeout(150);await expect(input).toHaveValue('7.50')
  const current=await read()
  expect((await page.request.put(`${url}/parameter`,{headers,data:{node:'Source',parameter:'value',value:30,revision:current.revision}})).ok()).toBe(true)
  await expect.poll(()=>latest?.values?.Sliders?._control_1).toBe(30)
  await expect(input).toHaveValue('30')
  await page.getByRole('button',{name:'Edit Input',exact:true}).click()
  await page.getByLabel('Hide title, header and footer',{exact:true}).check()
  await expect.poll(async()=>(await read()).graph.nodes.find((n:any)=>n.id==='Input').parameters.hide_chrome).toBe(1)
  await page.getByLabel('Control type',{exact:true}).selectOption('2')
  await expect.poll(async()=>(await read()).graph.nodes.find((n:any)=>n.id==='Input').parameters.mode).toBe(2)
  await page.getByRole('button',{name:'Close parameters'}).click()
  const compact=page.locator('[data-id="Input"] .compact-control')
  await expect(compact.locator('header')).toHaveCount(0)
  expect((await compact.boundingBox())!.height).toBeLessThan(75)
  await page.getByRole('button',{name:'Increase Input by 1',exact:true}).click()
  await expect.poll(()=>latest?.values?.Sliders?._control_1).toBe(31)
  await page.screenshot({path:'/tmp/pr0former-live-controls.png'})
  const panel=page.locator('[data-id="Sliders"]')
  async function checkFooter(){const footer=(await panel.locator('.node-foot').boundingBox())!;for(const label of await panel.locator('.controller output,.controller small').all())expect((await label.boundingBox())!.y+(await label.boundingBox())!.height).toBeLessThan(footer.y)}
  await checkFooter()
  await page.getByRole('button',{name:'Edit Sliders',exact:true}).click()
  await page.getByLabel('Slider orientation',{exact:true}).selectOption('0')
  await expect.poll(async()=>(await read()).graph.nodes.find((n:any)=>n.id==='Sliders').parameters.orientation).toBe(0)
  await page.getByRole('button',{name:'Close parameters'}).click()
  await checkFooter()
  await page.screenshot({path:'/tmp/pr0former-vertical-sliders.png'})
  await expect(page.getByRole('alert')).toHaveCount(0)
})
