import {test,expect} from '@playwright/test'

test('monitor sidebar, process stats and one peak meter per input/output node',async({page})=>{
  const headers={'X-Pr0former':'1'},status=await(await page.request.get('/api/status')).json()
  await page.request.post(`/api/${status.bootstrap?'register':'login'}`,{headers,data:{username:'browser-test',password:'test1234'}})
  let p=await(await page.request.post('/api/projects',{headers,data:{name:'Monitor layout',mode:'freeform'}})).json()
  p.parts=[]
  const node=(id:string,kind:string,parameters={})=>({id,kind,label:id,x:0,y:0,channels:2,parameters})
  p.graph={nodes:[node('Native input','input'),node('Browser input','browser_input'),node('Tone','oscillator',{frequency:440,amplitude:0.8}),node('Main output','output',{gain:-24}),node('Headphones','monitor_output',{gain:-12})],edges:[{id:'main',source:'Tone',source_port:'out',target:'Main output',target_port:'in'},{id:'phones',source:'Tone',source_port:'out',target:'Headphones',target_port:'in'}]}
  p=await(await page.request.put(`/api/projects/${p.id}`,{headers,data:p})).json()
  expect((await page.request.put(`/api/projects/${p.id}/system/audio`,{headers,data:{sample_rate:48000,block_size:128,interfaces:[],input_interfaces:[]}})).ok()).toBeTruthy()
  await page.goto('/')
  await page.getByRole('button',{name:'Choose project'}).click()
  await page.getByRole('button',{name:'Monitor layout',exact:true}).click()
  await expect(page.locator('.workspace-actions').getByRole('button',{name:'Ensemble'})).toHaveCount(0)
  await expect(page.locator('.project-heading .revision')).toBeVisible()
  const name=await page.locator('.project-title').boundingBox(),revision=await page.locator('.project-heading .revision').boundingBox()
  expect(revision!.y).toBeGreaterThan(name!.y)
  await page.getByRole('button',{name:'Monitor',exact:true}).click()
  const sidebar=page.getByRole('complementary',{name:'Monitor controls and statistics'})
  await expect(sidebar.getByRole('heading',{name:'Clock sync'})).toBeVisible()
  await expect(sidebar.getByRole('heading',{name:'Server process'})).toBeVisible()
  await expect(sidebar.getByLabel('Monitor feed')).toBeVisible()
  await expect(page.getByRole('region',{name:'Inputs VU meters'}).getByRole('meter')).toHaveCount(2)
  await expect(page.getByRole('region',{name:'Outputs VU meters'}).getByRole('meter')).toHaveCount(2)
  const left=await sidebar.boundingBox(),right=await page.locator('.meter-banks').boundingBox()
  expect(right!.x).toBeGreaterThanOrEqual(left!.x+left!.width)
  expect(right!.width).toBeGreaterThan(left!.width*2)
  const input=await page.getByRole('region',{name:'Inputs VU meters'}).boundingBox(),output=await page.getByRole('region',{name:'Outputs VU meters'}).boundingBox()
  expect(output!.y).toBeGreaterThan(input!.y+input!.height)
  const resource=await(await page.request.get('/api/system/stats')).json()
  expect(resource.resident_bytes).toBeGreaterThan(0)
  await expect.poll(async()=> (await(await page.request.get('/api/system/stats')).json()).cpu_percent).toBeGreaterThanOrEqual(0)
  await page.getByRole('button',{name:'Play',exact:true}).click()
  const main=page.locator('.vu-strip[data-node="Main output"]')
  await expect(main).toHaveAttribute('data-zone','normal')
  await expect(main.getByRole('meter')).not.toHaveAttribute('aria-valuenow','-60')
  const setGain=async(value:number)=>{
    p=(await(await page.request.get(`/api/projects/${p.id}`)).json()).project
    const response=await page.request.put(`/api/projects/${p.id}/parameter`,{headers,data:{node:'Main output',parameter:'gain',value,revision:p.revision}})
    expect(response.ok()).toBeTruthy()
  }
  await setGain(-3)
  await expect(main).toHaveAttribute('data-zone','warning')
  await setGain(6)
  await expect(main).toHaveAttribute('data-zone','clip')
  await expect(main.getByText('CLIP',{exact:true})).toBeVisible()
  await expect(main.locator('.vu-fill')).toHaveCSS('background-color','rgb(241, 109, 105)')
  await expect(main.getByRole('meter')).toHaveAttribute('aria-valuetext',/clipping/)
  await page.screenshot({path:'test-results/monitor-desktop.png'})
  await page.setViewportSize({width:768,height:1024})
  await expect(sidebar).toBeVisible()
  await expect(page.locator('.project-heading .revision')).toBeVisible()
  await page.screenshot({path:'test-results/monitor-tablet.png'})
  await page.getByRole('button',{name:'Pause',exact:true}).click()
  await expect(main.getByRole('meter')).toHaveAttribute('aria-valuenow','-60')
  await page.context().setOffline(true)
  await expect(main).toHaveClass(/stale/)
  await expect(main.getByRole('meter')).toHaveAttribute('aria-valuetext','No current engine data')
  await page.context().setOffline(false)
  await page.getByRole('button',{name:'Deactivate show',exact:true}).click()
})
