import { test, expect } from '@playwright/test'
test.use({hasTouch:true})
test('piano plays notes, forwards polyphony, highlights received keys and selects octaves', async ({page,context}) => {
  const headers={'X-Pr0former':'1'},status=await(await page.request.get('/api/status')).json()
  await page.request.post(`/api/${status.bootstrap?'register':'login'}`,{headers,data:{username:'browser-test',password:'test1234'}})
  let p=await(await page.request.post('/api/projects',{headers,data:{name:'Piano test',mode:'freeform'}})).json()
  const n=(id:string,kind:string,x:number)=>({id,kind,label:id,x,y:0,channels:1,parameters:{}})
  p.parts=[];p.graph={nodes:[n('Play keys','piano',0),n('Receive keys','piano',390),n('On count','counter',900),n('Off count','counter',1150)],edges:[]}
  for(const port of ['pitch','velocity','gate','trigger','note_off'])p.graph.edges.push({id:port,source:'Play keys',source_port:port,target:'Receive keys',target_port:port})
  for(const [port,target] of [['trigger','On count'],['note_off','Off count']])p.graph.edges.push({id:target,source:'Receive keys',source_port:port,target,target_port:'trigger'})
  const saved=await page.request.put(`/api/projects/${p.id}`,{headers,data:p});expect(saved.ok()).toBe(true);p=await saved.json()
  const note=(pitch:number,velocity:number,node='Play keys')=>page.request.put(`/api/projects/${p.id}/piano`,{headers,data:{node,pitch,velocity}})
  expect((await note(60,100)).status()).toBe(400)
  let latest:any
  page.on('websocket',socket=>socket.on('framereceived',({payload})=>{const m=JSON.parse(String(payload));if(m.type==='telemetry')latest=m}))
  await page.goto('/')
  const source=page.locator('.vue-flow__node[data-id="Play keys"]'),receiver=page.locator('.vue-flow__node[data-id="Receive keys"]')
  const c=source.getByRole('button',{name:'C4 MIDI 60',exact:true}), receivedC=receiver.getByRole('button',{name:'C4 MIDI 60',exact:true})
  await expect(c).toBeDisabled()
  await page.getByLabel('Count in',{exact:true}).selectOption('0')
  await page.getByRole('button',{name:'Enable audio engine',exact:true}).click()
  await expect.poll(()=>latest?.running).toBe(false)
  expect(latest.beat).toBe(0)
  await expect(c).toBeEnabled()
  const invalid=structuredClone(p);invalid.graph.nodes[0].parameters.octave=4.5
  expect((await page.request.put(`/api/projects/${p.id}`,{headers,data:invalid})).status()).toBe(400)
  const initial=(await(await page.request.get(`/api/projects/${p.id}`)).json()).project.revision
  const normalColor=await c.evaluate(el=>getComputedStyle(el).backgroundColor)
  let allowNote!:()=>void
  const delayedNote=new Promise<void>(resolve=>{allowNote=resolve})
  await page.route(`**/api/projects/${p.id}/piano`,async route=>{await delayedNote;await route.continue()},{times:1})
  const box=(await c.boundingBox())!
  await page.mouse.move(box.x+box.width/2,box.y+box.height-10);await page.mouse.down()
  // Local feedback must appear even before the server receives the press.
  await expect(c).toHaveAttribute('aria-pressed','true')
  expect(await c.evaluate(el=>getComputedStyle(el).backgroundColor)).not.toBe(normalColor)
  await expect(receivedC).toHaveAttribute('aria-pressed','false')
  allowNote()
  await expect(receivedC).toHaveAttribute('aria-pressed','true')
  expect(await receivedC.evaluate(el=>getComputedStyle(el).backgroundColor)).not.toBe(normalColor)
  await page.mouse.move(box.x+box.width/2,box.y-80);await page.mouse.up()
  await expect(receivedC).toHaveAttribute('aria-pressed','false')
  await expect.poll(()=>latest?.values?.['Off count']?._out).toBe(1)
  expect((await(await page.request.get(`/api/projects/${p.id}`)).json()).project.revision).toBe(initial)
  expect((await note(128,100)).status()).toBe(400)
  expect((await note(60,100,'On count')).status()).toBe(400)
  expect((await page.request.put(`/api/projects/${p.id}/piano`,{data:{node:'Play keys',pitch:60,velocity:100}})).status()).toBe(403)
  // Two simultaneous touch keys produce independent note-off events.
  const e=source.getByRole('button',{name:'E4 MIDI 64',exact:true}), eb=(await e.boundingBox())!
  const cdp=await context.newCDPSession(page)
  const touchBox=(await c.boundingBox())!
  const points=[{id:1,x:touchBox.x+touchBox.width/2,y:touchBox.y+touchBox.height-10},{id:2,x:eb.x+eb.width/2,y:eb.y+eb.height-10}]
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:points})
  await expect(receivedC).toHaveAttribute('aria-pressed','true')
  await expect(receiver.getByRole('button',{name:'E4 MIDI 64',exact:true})).toHaveAttribute('aria-pressed','true')
  await page.screenshot({path:'test-results/piano.png'})
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[points[0]]})
  await expect(receivedC).toHaveAttribute('aria-pressed','false')
  await expect(receiver.getByRole('button',{name:'E4 MIDI 64',exact:true})).toHaveAttribute('aria-pressed','true')
  await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]})
  await expect.poll(()=>latest?.values?.['Off count']?._out).toBe(3)
  await expect(receiver.getByRole('button',{name:'E4 MIDI 64',exact:true})).toHaveAttribute('aria-pressed','false')
  // Octave limits affect display only; out-of-range notes still forward.
  await note(48,100)
  await expect.poll(()=>latest?.values?.['On count']?._out).toBe(4)
  await expect(receiver.locator('.piano-key.lit')).toHaveCount(0)
  await page.getByRole('button',{name:'Edit Receive keys',exact:true}).click()
  await page.getByLabel('Octave',{exact:true}).selectOption('3')
  await page.getByRole('button',{name:'Close parameters',exact:true}).click()
  await expect(receiver.getByRole('button',{name:'C3 MIDI 48',exact:true})).toHaveAttribute('aria-pressed','true')
  await note(48,0)
  await expect(receiver.locator('.piano-key.lit')).toHaveCount(0)
  const black=receiver.getByRole('button',{name:'C♯3 MIDI 49',exact:true})
  const dark=await black.evaluate(el=>getComputedStyle(el).backgroundColor)
  await note(49,100)
  await expect(black).toHaveAttribute('aria-pressed','true')
  expect(await black.evaluate(el=>getComputedStyle(el).backgroundColor)).not.toBe(dark)
  await note(49,0)
  await expect(black).toHaveAttribute('aria-pressed','false')
  expect(await black.evaluate(el=>getComputedStyle(el).backgroundColor)).toBe(dark)
  await note(60,100)
  await expect.poll(()=>latest?.values?.['Receive keys']?.gate).toBe(1)
  await page.getByRole('button',{name:'Edit Receive keys',exact:true}).click()
  await page.getByLabel('Octave span',{exact:true}).selectOption('2')
  await page.getByRole('button',{name:'Close parameters',exact:true}).click()
  await expect(receiver.locator('.piano-key')).toHaveCount(24)
  await expect(receiver.getByRole('button',{name:'C4 MIDI 60',exact:true})).toHaveAttribute('aria-pressed','true')
  await page.screenshot({path:'test-results/piano-multiple-octaves.png'})
  for(const span of [0,1.5,9]){
    const invalid=(await(await page.request.get(`/api/projects/${p.id}`)).json()).project
    invalid.graph.nodes[0].parameters.octaves=span
    expect((await page.request.put(`/api/projects/${p.id}`,{headers,data:invalid})).status()).toBe(400)
  }
  await page.getByRole('button',{name:'Play',exact:true}).click()
  await expect.poll(()=>latest?.running).toBe(true)
  await page.getByRole('button',{name:'Pause',exact:true}).click()
  await expect.poll(()=>latest?.running).toBe(false)
  expect(latest.values['Receive keys'].gate).toBe(1)
  await page.getByRole('button',{name:'Stop',exact:true}).click()
  await expect.poll(()=>latest?.beat).toBe(0)
  expect(latest.values['Receive keys'].gate).toBe(1)
  await expect(page.getByRole('button',{name:'Disable audio engine',exact:true})).toBeEnabled()
  expect(latest.values['Receive keys'].gate).toBe(1)
  await note(60,0)
  await expect.poll(()=>latest?.values?.['Receive keys']?.gate).toBe(0)
  await page.getByRole('button',{name:'Disable audio engine',exact:true}).click()
  await expect(c).toBeDisabled()

})
