import {test,expect} from '@playwright/test'
const headers={'X-Pr0former':'1'}
test('per-user recent projects, metadata browsing and user administration',async({page,playwright})=>{
 const status=await(await page.request.get('/api/status')).json()
 await page.request.post(`/api/${status.bootstrap?'register':'login'}`,{headers,data:{username:'browser-test',password:'test1234'}})
 expect((await(await page.request.get('/api/me')).json()).is_admin).toBe(true)
 const projects:any[]=[]
 for(let i=0;i<7;i++){
   let p=await(await page.request.post('/api/projects',{headers,data:{name:`Browser catalogue ${i}`,mode:i===0?'structured':'conducted'}})).json()
   if(i===0){p.bpm=137;p.beats_per_bar=7;p.beat_unit=8;p=await(await page.request.put(`/api/projects/${p.id}`,{headers,data:p})).json()}
   projects.push(p);expect((await page.request.post(`/api/projects/${p.id}/opened`,{headers})).ok()).toBe(true)
 }
 await page.goto('/')
 await page.getByRole('button',{name:'Choose project'}).click()
 const picker=page.locator('.project-popover')
 await expect(picker.locator('button').filter({hasText:'Browser catalogue'})).toHaveCount(5)
 await expect(picker.getByText('Browser catalogue 0',{exact:true})).toHaveCount(0)
 await picker.getByRole('button',{name:'Browse all projects'}).click()
 const browser=page.getByRole('dialog',{name:'Project browser'})
 await browser.getByRole('textbox',{name:'Search project metadata'}).fill('STRUCTURED 137 7/8')
 await expect(browser.getByRole('button',{name:'Browser catalogue 0',exact:true})).toHaveCount(1)
 await browser.getByRole('button',{name:'Icon view'}).click()
 await expect(browser.locator('.browser-card')).toHaveCount(1)
 await browser.locator('.browser-card').focus()
 await expect(browser.locator('.card-details')).toBeVisible()
 await page.screenshot({path:'test-results/project-browser-icons.png'})
 await browser.locator('.browser-card').press('Enter')
 await expect(browser).toHaveCount(0)
 await expect(page.locator('.project-title')).toContainText('Browser catalogue 0')
 await page.getByRole('button',{name:'Settings menu'}).click()
 await page.getByRole('menuitem',{name:'System settings',exact:true}).click()
 const system=page.getByRole('dialog',{name:'System settings'})
 await system.getByRole('tab',{name:'Users',exact:true}).click()
 await system.getByRole('button',{name:'Add user',exact:true}).click()
 const username=`organizer-${Date.now()}`
 const form=system.getByRole('form',{name:'User profile'})
 await form.getByLabel('Username',{exact:true}).fill(username)
 await form.getByLabel('First name',{exact:true}).fill('Ada')
 await form.getByLabel('Middle name',{exact:true}).fill('Augusta')
 await form.getByLabel('Last name',{exact:true}).fill('Lovelace')
 await form.getByLabel('Email',{exact:true}).fill('ada@example.test')
 await form.getByLabel('Initial password',{exact:true}).fill('password123')
 await form.getByRole('button',{name:'Save user'}).click()
 await expect(system.getByRole('status')).toContainText('User saved')
 const guest=await playwright.request.newContext({baseURL:'http://127.0.0.1:3101'})
 expect((await guest.post('/api/login',{headers,data:{username,password:'password123'}})).ok()).toBe(true)
 let u=await(await guest.get('/api/me')).json();expect(u.is_admin).toBe(false);expect(u.middle_name).toBe('Augusta')
 expect((await guest.get('/api/admin/users')).status()).toBe(403)
 expect((await guest.get('/api/system/audio')).status()).toBe(403)
 expect((await guest.get('/api/system/osc')).status()).toBe(403)
 expect((await guest.get('/api/audio/config')).status()).toBe(200)
 await expect((await guest.get('/api/projects')).json()).resolves.toEqual([])
 const own=await(await guest.post('/api/projects',{headers,data:{name:'Guest private project',mode:'freeform'}})).json()
 expect((await guest.put(`/api/projects/${own.id}/system/audio`,{headers,data:{sample_rate:48000,block_size:128,interfaces:[]}})).status()).toBe(403)
 expect((await guest.post(`/api/projects/${projects[0].id}/opened`,{headers})).status()).toBe(403)
 expect((await guest.get(`/api/projects/${projects[0].id}`)).status()).toBe(403)
 const guestContext=await page.context().browser()!.newContext({storageState:await guest.storageState()})
 const guestPage=await guestContext.newPage();await guestPage.goto('http://127.0.0.1:3101/')
 await guestPage.getByRole('button',{name:'Settings menu'}).click()
 await expect(guestPage.getByRole('menuitem',{name:'System settings',exact:true})).toHaveCount(0)
 await guestPage.getByRole('menuitem',{name:'Project settings',exact:true}).click()
 await expect(guestPage.getByRole('dialog',{name:'Project settings'})).toBeVisible()
 await guestContext.close()
 expect((await page.request.delete(`/api/admin/users/${u.id}`,{headers,data:{confirm:u.username,revision:u.revision}})).status()).toBe(400)
 // Resetting a password revokes existing sessions and old credentials.
 await form.getByLabel('New password',{exact:true}).fill('replacement123')
 await form.getByRole('button',{name:'Save user'}).click()
 await expect.poll(async()=>(await guest.get('/api/me')).status()).toBe(401)
 expect((await guest.post('/api/login',{headers,data:{username,password:'password123'}})).status()).toBe(401)
 expect((await guest.post('/api/login',{headers,data:{username,password:'replacement123'}})).ok()).toBe(true)
 await form.getByLabel('Account enabled',{exact:true}).uncheck()
 await form.getByRole('button',{name:'Save user'}).click()
 await expect.poll(async()=>(await guest.get('/api/me')).status()).toBe(401)
 expect((await guest.post('/api/login',{headers,data:{username,password:'replacement123'}})).status()).toBe(401)
 await form.getByLabel('Account enabled',{exact:true}).check()
 await form.getByRole('button',{name:'Save user'}).click()
 await expect(system.getByRole('status')).toContainText('User saved')
 const owner=await(await page.request.get('/api/me')).json()
 const denied=await page.request.put(`/api/admin/users/${owner.id}`,{headers,data:{username:owner.username,is_admin:false,enabled:true,revision:owner.revision,fields:{}}})
 expect(denied.status()).toBe(400);expect((await denied.json()).error).toContain('last active administrator')
 await page.screenshot({path:'test-results/user-administration.png'})
 const disposable=await(await page.request.post('/api/admin/users',{headers,data:{username:`disposable-${Date.now()}`,is_admin:false,enabled:true,password:'password123',fields:{}}})).json()
 expect((await page.request.delete(`/api/admin/users/${disposable.id}/sessions`,{headers})).ok()).toBe(true)
 expect((await page.request.delete(`/api/admin/users/${disposable.id}`,{headers,data:{confirm:disposable.username,revision:disposable.revision}})).ok()).toBe(true)
 expect((await guest.post('/api/login',{headers,data:{username:disposable.username,password:'password123'}})).status()).toBe(401)
 await guest.dispose()
})
