import {test,expect} from '@playwright/test'
const headers={'X-Pr0former':'1'}
test('N opens graph-only search with focus, keyboard navigation, insertion and drag placement',async({page})=>{
 const status=await(await page.request.get('/api/status')).json()
 await page.request.post(`/api/${status.bootstrap?'register':'login'}`,{headers,data:{username:'browser-test',password:'test1234'}})
 let p=await(await page.request.post('/api/projects',{headers,data:{name:'Quick insertion',mode:'freeform'}})).json()
 p.parts=[];p.graph={nodes:[],edges:[]};expect((await page.request.put(`/api/projects/${p.id}`,{headers,data:p})).ok()).toBe(true)
 const load=async()=>(await(await page.request.get(`/api/projects/${p.id}`)).json()).project
 await page.goto('/')
 await page.locator('.graph-canvas').click({position:{x:450,y:250}})
 await page.keyboard.press('n')
 const browser=page.getByRole('dialog',{name:'Quick node browser'}),input=browser.getByRole('combobox')
 await expect(input).toBeFocused()
 await input.fill('synth')
 await input.press('ArrowDown')
 await expect(browser.getByRole('option').nth(1)).toHaveAttribute('aria-selected','true')
 await input.press('ArrowUp')
 await expect(browser.getByRole('option').first()).toHaveAttribute('aria-selected','true')
 await input.fill('Polyphonic FM synth')
 await expect(browser.getByRole('option')).toHaveCount(1)
 await input.press('Enter')
 await expect(browser).toHaveCount(0)
 await expect.poll(async()=>(await load()).graph.nodes[0]?.kind).toBe('fm_synth')
 await page.locator('.graph-canvas').click({position:{x:500,y:150}})
 await page.keyboard.press('n');await expect(input).toBeFocused();await input.fill('oscillator')
 await page.screenshot({path:'test-results/quick-node-browser.png',animations:'disabled'})
 const source=(await browser.getByRole('option').first().boundingBox())!,canvas=(await page.locator('.graph-canvas').boundingBox())!
 await page.mouse.move(source.x+35,source.y+source.height/2);await page.mouse.down()
 await page.mouse.move(source.x+50,source.y+source.height/2,{steps:4})
 await expect(page.locator('.quick-node-overlay')).toHaveClass(/dragging/)
 await page.mouse.move(canvas.x+550,canvas.y+350,{steps:8});await page.mouse.up()
 await expect.poll(async()=>(await load()).graph.nodes.length).toBe(2)
 await expect(browser).toHaveCount(0)
 await page.locator('.graph-canvas').click({position:{x:550,y:100}})
 await page.keyboard.press('n');await input.press('Tab');await expect(browser.getByRole('button',{name:'Close quick node browser'})).toBeFocused()
 await page.keyboard.press('Enter');await expect(browser).toHaveCount(0)
 await page.getByRole('button',{name:'Score & Parts',exact:true}).click()
 await page.locator('.workspace-tabs').click({position:{x:800,y:20}})
 await page.keyboard.press('n');await expect(browser).toHaveCount(0)
 await page.getByRole('button',{name:'Signal Graph',exact:true}).click()
 await page.keyboard.press('n');await expect(input).toBeFocused()
 await input.press('Control+End');await expect(browser.getByRole('option').last()).toHaveAttribute('aria-selected','true')
 await input.press('Escape');await expect(browser).toHaveCount(0)
 await page.getByLabel('Search nodes',{exact:true}).fill('n')
 await expect(browser).toHaveCount(0)
})
