import { test, expect } from '@playwright/test'

test('polyphonic sampler reuses the ADSR editor, shows its graph, and keeps note envelopes independent',async({page})=>{
  const headers={'X-Pr0former':'1'},status=await(await page.request.get('/api/status')).json()
  await page.request.post(`/api/${status.bootstrap?'register':'login'}`,{headers,data:{username:'browser-test',password:'test1234'}})
  let p=await(await page.request.post('/api/projects',{headers,data:{name:'Per-note envelopes',mode:'structured'}})).json()
  const url=`/api/projects/${p.id}`
  const sample=await(await page.request.post(`${url}/samples/bundled-kick/add`,{headers,data:{}})).json()
  const n=(id:string,kind:string,x:number,y:number,parameters={})=>({id,kind,label:id,x,y,channels:2,parameters})
  const edge=(source:string,source_port:string,target:string,target_port:string)=>({id:`${source}-${target}-${target_port}`,source,source_port,target,target_port})
  p.parts=[];p.graph={nodes:[n('Keys','piano',0,0),n('Sampler','poly_sampler',500,0,{asset:sample.asset,loop:1}),n('Listen','monitor_output',1000,0),n('Attack source','value',0,400,{value:700})],edges:[edge('Keys','midi','Sampler','midi'),edge('Sampler','out','Listen','in')]}
  expect((await page.request.put(url,{headers,data:p})).ok()).toBe(true)
  const read=async()=>(await(await page.request.get(url)).json()).project
  const sampler=async()=>(await read()).graph.nodes.find((n:any)=>n.id==='Sampler')
  let latest:any,peak=0
  page.on('websocket',socket=>socket.on('framereceived',({payload})=>{const event=JSON.parse(String(payload));if(event.type==='telemetry'){latest=event;peak=Math.max(peak,event.values?.Sampler?._peak||0)}}))
  await page.addInitScript(()=>localStorage.setItem('pr0former.help','hidden'))
  await page.goto('/')
  const node=page.locator('.vue-flow__node[data-id="Sampler"]')
  await expect(node.getByRole('img',{name:'ADSR envelope: attack 0 ms, decay 0 ms, sustain 1, release 80 ms',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Edit Sampler',exact:true}).click()
  const modal=page.getByRole('dialog',{name:/^Sampler/})
  await modal.getByRole('slider',{name:'Attack handle',exact:true}).press('ArrowRight')
  await expect.poll(async()=>(await sampler()).parameters.attack).toBe(1)
  for(const [key,label,value] of [['attack','Attack',200],['decay','Decay',100],['sustain','Sustain',0.5],['release','Release',600]] as const){
    const control=modal.getByRole('spinbutton',{name:label,exact:true});await control.fill(String(value));await control.press('Tab')
    await expect.poll(async()=>(await sampler()).parameters[key]).toBe(value)
  }
  const handle=modal.getByRole('slider',{name:'Release and sustain (drag left to lengthen the release) handle',exact:true})
  await handle.scrollIntoViewIfNeeded()
  const box=(await handle.boundingBox())!;await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2-15,box.y+box.height/2,{steps:5});await page.mouse.up()
  await expect.poll(async()=>(await sampler()).parameters.release).toBeGreaterThan(600)
  const release=modal.getByRole('spinbutton',{name:'Release',exact:true});await release.fill('600');await release.press('Tab');await expect.poll(async()=>(await sampler()).parameters.release).toBe(600)
  await modal.getByRole('slider',{name:'Attack handle',exact:true}).scrollIntoViewIfNeeded()
  await page.screenshot({path:'/tmp/pr0-sampler-envelope-options.png'})
  await page.getByRole('button',{name:'Close parameters'}).click()
  await expect(node.getByRole('img',{name:/ADSR envelope: attack 200 ms, decay 100 ms/})).toBeVisible()
  await page.getByRole('button',{name:'Enable audio engine',exact:true}).click()
  const note=async(pitch:number,velocity:number)=>expect((await page.request.put(`${url}/piano`,{headers,data:{node:'Keys',pitch,velocity}})).ok()).toBe(true)
  await note(60,100);await expect.poll(()=>latest?.values?.Sampler?._voices).toBe(1)
  await note(64,100);await expect.poll(()=>latest?.values?.Sampler?._voices).toBe(2)
  await note(60,0);await expect.poll(()=>latest?.values?.Sampler?._held).toBe(1)
  await expect.poll(()=>latest?.values?.Sampler?._voices).toBe(1)
  await expect.poll(()=>latest?.values?.Sampler?._envelope).toBeCloseTo(0.5,2)
  expect(peak).toBeGreaterThan(0.001)
  await page.screenshot({path:'/tmp/pr0-sampler-envelope-node.png'})
  await note(64,0);await expect.poll(()=>latest?.values?.Sampler?._voices).toBe(0)
  p=await read();p.graph.edges.push(edge('Attack source','out','Sampler','attack'));expect((await page.request.put(url,{headers,data:p})).ok()).toBe(true)
  await expect.poll(()=>latest?.values?.Sampler?.attack).toBe(700)
  await page.getByRole('button',{name:'Edit Sampler',exact:true}).click()
  await expect(modal.getByRole('slider',{name:'Attack handle',exact:true})).toHaveAttribute('aria-disabled','true')
  await expect(modal.getByText('Attack source / out',{exact:true})).toBeVisible()
  await expect(modal.getByRole('img',{name:/ADSR envelope: attack 700 ms/})).toBeVisible()
  const connected=await read();expect((await page.request.put(`${url}/parameter`,{headers,data:{node:'Sampler',parameter:'attack',value:2,revision:connected.revision}})).status()).toBe(400)
  await page.getByRole('button',{name:'Close parameters'}).click()
  await page.reload();expect((await sampler()).parameters.release).toBe(600)
  await expect(node.getByRole('img',{name:/ADSR envelope: attack 700 ms/})).toBeVisible()
  await page.getByRole('button',{name:'Disable audio engine',exact:true}).click()
})
