import {test,expect} from '@playwright/test'
import {spawnSync} from 'node:child_process'
import {mkdtempSync,readFileSync,rmSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
function audio(format:string,channels=2){const dir=mkdtempSync(join(tmpdir(),'pr0-audio-fixture-'));try{const file=join(dir,'audio');const r=spawnSync('ffmpeg',['-hide_banner','-loglevel','error','-f','lavfi','-i','sine=frequency=440:sample_rate=44100','-t','1','-ac',String(channels),'-f',format,file]);if(r.status!==0)throw new Error(String(r.stderr));return readFileSync(file)}finally{rmSync(dir,{recursive:true,force:true})}}

const headers={'X-Pr0former':'1'}
async function login(request:any){const status=await(await request.get('/api/status')).json();await request.post(`/api/${status.bootstrap?'register':'login'}`,{headers,data:{username:'browser-test',password:'test1234'}})}
async function upload(request:any,project:string,buffer:Buffer,name:string){const result=await request.post(`/api/projects/${project}/samples`,{headers,multipart:{sample:{name,mimeType:'application/octet-stream',buffer}}});expect(result.ok(),await result.text()).toBe(true);return result.json()}
test('sample imports preserve channels and project members can use another author’s private sample',async({request,playwright})=>{
  await login(request)
  const p=await(await request.post('/api/projects',{headers,data:{name:'Shared samples',mode:'freeform'}})).json()
  const token=(await(await request.post(`/api/projects/${p.id}/invite`,{headers,data:{role:'editor'}})).json()).token
  const author=await playwright.request.newContext({baseURL:'http://127.0.0.1:3101'})
  expect((await author.post('/api/register',{headers,data:{username:'sample-author',password:'test1234',invite:token}})).ok()).toBe(true)
  expect((await author.post('/api/join',{headers,data:{token}})).ok()).toBe(true)
  const sample=await upload(author,p.id,audio('flac',6),'surround.flac')
  expect(sample.channels).toBe(6);expect(sample.global).toBe(false)
  const projectSamples=await(await request.get(`/api/projects/${p.id}/samples`)).json();expect(projectSamples.some((s:any)=>s.id===sample.id)).toBe(true)
  const ownLibrary=await(await request.get(`/api/projects/${p.id}/sample-library`)).json();expect(ownLibrary.some((s:any)=>s.id===sample.id)).toBe(false)
  expect((await request.get(`/api/projects/${p.id}/samples/${sample.id}/audio`)).ok()).toBe(true)
  expect((await request.put(`/api/projects/${p.id}/samples/${sample.id}`,{headers,data:{...sample,global:true}})).status()).toBe(403)
  const shared=await author.put(`/api/projects/${p.id}/samples/${sample.id}`,{headers,data:{...sample,global:true,tags:'surround, space',category:'Textures'}});expect(shared.ok()).toBe(true)
  let metadata=await shared.json()
  expect((await author.put(`/api/projects/${p.id}/samples/${sample.id}`,{headers,data:{...sample,global:true}})).status()).toBe(409)
  const other=await(await request.post('/api/projects',{headers,data:{name:'Sample destination',mode:'freeform'}})).json()
  expect((await(await request.get(`/api/projects/${other.id}/samples`)).json()).length).toBe(0)
  expect((await(await request.get(`/api/projects/${other.id}/sample-library`)).json()).some((s:any)=>s.id===sample.id)).toBe(true)
  const added=await request.post(`/api/projects/${other.id}/samples/${sample.id}/add`,{headers,data:{}});expect(added.ok()).toBe(true)
  expect((await added.json()).asset).toBeGreaterThan(0)
  metadata=await(await author.put(`/api/projects/${p.id}/samples/${sample.id}`,{headers,data:{...metadata,global:false}})).json()
  expect((await request.get(`/api/projects/${other.id}/samples/${sample.id}/audio`)).ok()).toBe(true)
  const fresh=await(await request.post('/api/projects',{headers,data:{name:'No private access',mode:'freeform'}})).json()
  expect((await request.get(`/api/projects/${fresh.id}/samples/${sample.id}/audio`)).ok()).toBe(false)
  expect((await request.post(`/api/projects/${fresh.id}/samples/${sample.id}/add`,{headers,data:{}})).ok()).toBe(false)
  const mp3=await upload(request,other.id,audio('mp3'),'tone.mp3');expect(mp3.channels).toBe(2)
  const aiff=await upload(request,other.id,audio('aiff',1),'tone.aiff');expect(aiff.channels).toBe(1)
  const m4a=await upload(request,other.id,audio('mp4'),'tone.m4a');expect(m4a.channels).toBe(2)
  const wav=await(await request.get(`/api/projects/${other.id}/samples/${mp3.id}/audio`)).body();expect(wav.subarray(0,4).toString()).toBe('RIFF')
  const fmt=wav.indexOf(Buffer.from('fmt '))+8;expect(wav.readUInt16LE(fmt+14)).toBe(32);expect(wav.readUInt32LE(fmt+4)).toBe(mp3.sample_rate)
  const bad=await request.post(`/api/projects/${other.id}/samples`,{headers,multipart:{sample:{name:'bad.mp3',mimeType:'audio/mpeg',buffer:Buffer.from('not audio')}}});expect(bad.status()).toBe(400)
  const playlist=await request.post(`/api/projects/${other.id}/samples`,{headers,multipart:{sample:{name:'unsafe.ffconcat',mimeType:'text/plain',buffer:Buffer.from("ffconcat version 1.0\nfile '/etc/passwd'\n")}}});expect(playlist.status()).toBe(400)
  await author.dispose()
})
test('sample accordion, metadata search, preview, full waveform scrub and sampler assignment',async({page})=>{
  await login(page.request)
  const source=await(await page.request.post('/api/projects',{headers,data:{name:'Source sample collection',mode:'freeform'}})).json()
  await upload(page.request,source.id,audio('flac'),'Library only.flac')
  const p=await(await page.request.post('/api/projects',{headers,data:{name:'Sample browser UI',mode:'freeform'}})).json()
  await page.goto('/')
  await page.getByRole('button',{name:'Samples',exact:true}).click()
  await page.getByLabel('Import project audio').setInputFiles({name:'felt.flac',mimeType:'audio/flac',buffer:audio('flac')})
  await expect(page.getByRole('button',{name:'Edit sample felt.flac',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Preview felt.flac',exact:true}).click()
  await expect(page.getByRole('button',{name:'Preview felt.flac',exact:true})).toHaveText('■')
  await page.getByRole('button',{name:'Edit sample felt.flac',exact:true}).click()
  const modal=page.getByRole('dialog',{name:'Sample metadata',exact:true})
  await expect(modal.getByRole('button',{name:'Play sample',exact:true})).toBeEnabled()
  await expect(modal.locator('canvas')).toHaveAttribute('width','1000')
  await modal.getByRole('button',{name:'Play sample',exact:true}).click()
  await expect.poll(()=>modal.locator('audio').evaluate((el:HTMLAudioElement)=>el.currentTime)).toBeGreaterThan(0)
  await modal.getByRole('button',{name:'Pause sample',exact:true}).click()
  const wave=modal.locator('.sample-waveform'),box=(await wave.boundingBox())!
  await page.mouse.click(box.x+box.width*.65,box.y+box.height*.5)
  await expect.poll(()=>modal.locator('audio').evaluate((el:HTMLAudioElement)=>el.currentTime)).toBeGreaterThan(.5)
  await modal.getByLabel('Name',{exact:true}).fill('Warm felt piano')
  await modal.getByLabel('Tags',{exact:true}).fill('soft, felt')
  await modal.getByLabel('Category',{exact:true}).fill('Keys')
  await modal.getByLabel('Global — available to every user and project',{exact:true}).check()
  await page.screenshot({path:'test-results/sample-editor.png'})
  await modal.getByRole('button',{name:'Save metadata',exact:true}).click()
  await expect(modal).toHaveCount(0)
  await page.getByLabel('Search project samples').fill('felt')
  await expect(page.getByRole('button',{name:'Edit sample Warm felt piano',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Add sampler for Warm felt piano',exact:true}).click()
  await expect.poll(async()=>(await(await page.request.get(`/api/projects/${p.id}`)).json()).project.graph.nodes.some((n:any)=>n.kind==='poly_sampler'&&n.parameters.asset>0)).toBe(true)
  await page.getByRole('button',{name:'Browse all',exact:true}).click()
  const browser=page.getByRole('dialog',{name:'Full sample browser',exact:true})
  await browser.getByLabel('Search all samples').fill('soft')
  await expect(browser.getByRole('button',{name:'Edit sample Warm felt piano',exact:true})).toBeVisible()
  await expect(browser.getByRole('button',{name:'In project',exact:true})).toBeDisabled()
  await browser.getByLabel('Search all samples').fill('Library only')
  await browser.getByRole('button',{name:'Add to project',exact:true}).click()
  await expect(browser.getByRole('button',{name:'In project',exact:true})).toBeDisabled()
  await page.getByRole('button',{name:'Close sample browser',exact:true}).click()
  await page.getByLabel('Search project samples').fill('Library only')
  await expect(page.getByRole('button',{name:'Edit sample Library only.flac',exact:true})).toBeVisible()
})
