import {test,expect} from '@playwright/test'
import {access} from 'node:fs/promises'
import {join} from 'node:path'
const headers={'X-Pr0former':'1'}
test('sample organizer enforces global deletion, impact review, and removes linked audio',async({page,playwright})=>{
 const status=await(await page.request.get('/api/status')).json()
 await page.request.post(`/api/${status.bootstrap?'register':'login'}`,{headers,data:{username:'browser-test',password:'test1234'}})
 const username=`samples-${Date.now()}`
 const account=await page.request.post('/api/admin/users',{headers,data:{username,is_admin:false,enabled:true,password:'password123',fields:{}}});expect(account.ok()).toBe(true)
 const guest=await playwright.request.newContext({baseURL:'http://127.0.0.1:3101'})
 await guest.post('/api/login',{headers,data:{username,password:'password123'}})
 let p=await(await guest.post('/api/projects',{headers,data:{name:'Sample owner project',mode:'freeform'}})).json()
 const wav=Buffer.alloc(44+4800*2);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(48000,24);wav.writeUInt32LE(96000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(wav.length-44,40)
 const uploaded=await guest.post(`/api/projects/${p.id}/samples`,{headers,multipart:{sample:{name:'Shared deletion test.wav',mimeType:'audio/wav',buffer:wav}}});expect(uploaded.ok()).toBe(true)
 let s=(await(await guest.get(`/api/projects/${p.id}/samples`)).json())[0]
 expect(s.can_delete).toBe(true)
 await expect((await page.request.get('/api/samples')).json()).resolves.not.toContainEqual(expect.objectContaining({id:s.id}))
 s=await(await guest.put(`/api/projects/${p.id}/samples/${s.id}`,{headers,data:{...s,global:true}})).json()
 expect((await guest.get(`/api/samples/${s.id}/impact`)).status()).toBe(403)
 expect((await guest.delete(`/api/samples/${s.id}`,{headers,data:{confirm:s.name,acknowledge:true,revision:s.revision,usage_token:''}})).status()).toBe(403)
 s=await(await guest.put(`/api/projects/${p.id}/samples/${s.id}`,{headers,data:{...s,global:false}})).json()
 expect(s.can_delete).toBe(false)
 expect((await guest.get(`/api/samples/${s.id}/impact`)).status()).toBe(403)
 s=await(await guest.put(`/api/projects/${p.id}/samples/${s.id}`,{headers,data:{...s,global:true}})).json()
 const firstImpact=await(await page.request.get(`/api/samples/${s.id}/impact`)).json()
 const shared=await(await page.request.post('/api/projects',{headers,data:{name:'Sample reuse project',mode:'freeform'}})).json()
 const linked=await(await page.request.post(`/api/projects/${shared.id}/samples/${s.id}/add`,{headers})).json()
 expect((await page.request.delete(`/api/samples/${s.id}`,{headers,data:{confirm:s.name,acknowledge:true,revision:s.revision,usage_token:firstImpact.usage_token}})).status()).toBe(409)
 const impact=await(await page.request.get(`/api/samples/${s.id}/impact`)).json();expect(impact.project_count).toBe(2);expect(impact.projects).toHaveLength(1)
 expect((await page.request.delete(`/api/samples/${s.id}`,{headers,data:{confirm:s.name,acknowledge:false,revision:s.revision,usage_token:impact.usage_token}})).status()).toBe(400)
 // Another project (from an earlier spec) may still own the engine; only its owner can release it.
 const ownership=await(await page.request.get('/api/status')).json()
 if(ownership.graph_project)expect((await page.request.post(`/api/projects/${ownership.graph_project}/engine`,{headers,data:{enabled:false}})).ok()).toBe(true)
 expect((await guest.post(`/api/projects/${p.id}/engine`,{headers,data:{enabled:true}})).ok()).toBe(true)
 expect((await page.request.delete(`/api/samples/${s.id}`,{headers,data:{confirm:s.name,acknowledge:true,revision:s.revision,usage_token:impact.usage_token}})).status()).toBe(400)
 expect((await guest.post(`/api/projects/${p.id}/engine`,{headers,data:{enabled:false}})).ok()).toBe(true)
 await page.goto('/')
 await page.getByRole('button',{name:'Project browser',exact:true}).click()
 const browser=page.getByRole('dialog',{name:'Project browser'})
 await browser.getByRole('tab',{name:'Sample organizer'}).click()
 await browser.getByLabel('Search sample metadata').fill('Shared deletion')
 await browser.getByRole('button',{name:`Delete sample ${s.name}`,exact:true}).click()
 const warning=browser.getByRole('alertdialog',{name:'Confirm sample deletion'})
 await expect(warning).toContainText('2 projects')
 const remove=warning.getByRole('button',{name:'Permanently delete sample',exact:true})
 await expect(remove).toBeDisabled()
 await warning.getByLabel('I understand this can permanently break projects.').check()
 await warning.getByLabel('Type sample name to delete').fill(s.name)
 await page.screenshot({path:'test-results/sample-deletion-review.png'})
 await remove.click()
 await expect(warning).toHaveCount(0)
 await expect(browser.getByRole('button',{name:`Delete sample ${s.name}`,exact:true})).toHaveCount(0)
 expect((await guest.get(`/api/samples/${s.id}/audio`)).status()).toBe(400)
 expect((await(await guest.get(`/api/projects/${p.id}/samples`)).json())).toEqual([])
 await expect(access(join(process.env.PR0_TEST_DATA!,'sample-library',`${s.id}.wav`))).rejects.toThrow()
 await expect(access(join(process.env.PR0_TEST_DATA!,'samples',shared.id,`${linked.asset}.wav`))).rejects.toThrow()
 await guest.dispose()
})
