import {test,expect} from '@playwright/test'
test('scale exposes input and output ranges and maps live values',async({page})=>{
  const headers={'X-Pr0former':'1'},status=await(await page.request.get('/api/status')).json()
  await page.request.post(`/api/${status.bootstrap?'register':'login'}`,{headers,data:{username:'browser-test',password:'test1234'}})
  let p=await(await page.request.post('/api/projects',{headers,data:{name:'Scale ranges',mode:'freeform'}})).json()
  p.parts=[];p.graph={nodes:[{id:'scale',kind:'scale',label:'Scale',x:0,y:0,channels:1,parameters:{}},{id:'db',kind:'atodb',label:'Decibels',x:350,y:0,channels:1,parameters:{a:2}}],edges:[]}
  const saved=await page.request.put(`/api/projects/${p.id}`,{headers,data:p});expect(saved.ok()).toBe(true)
  let latest:any;page.on('websocket',s=>s.on('framereceived',({payload})=>{const m=JSON.parse(String(payload));if(m.type==='telemetry')latest=m}))
  await page.goto('/');await page.getByRole('button',{name:'Enable audio engine',exact:true}).click()
  await expect.poll(()=>latest?.values.scale._out).toBe(-90)
  await page.getByRole('button',{name:'Edit Scale',exact:true}).click()
  for(const [name,value] of [['Input minimum','0'],['Input maximum','1'],['Output minimum','-90'],['Output maximum','6']])await expect(page.getByRole('spinbutton',{name,exact:true})).toHaveValue(value!)
  const maximum=page.getByRole('spinbutton',{name:'Input maximum',exact:true})
  await maximum.fill('127');await maximum.press('Tab')
  await expect.poll(()=>latest?.values.scale.input_max).toBe(127)
  const input=page.getByRole('spinbutton',{name:'Input',exact:true})
  await input.fill('64');await input.press('Tab')
  await expect.poll(()=>latest?.values.scale._out).toBeCloseTo(-90+64/127*96)
  await page.getByRole('button',{name:'Close parameters',exact:true}).click()
  await expect.poll(()=>latest?.values.db._out).toBe(6)
  await page.getByRole('button',{name:'Edit Decibels',exact:true}).click()
  await expect(page.getByRole('spinbutton',{name:'Minimum dB',exact:true})).toHaveValue('-90')
  await expect(page.getByRole('spinbutton',{name:'Maximum dB',exact:true})).toHaveValue('6')
  await expect(page.getByRole('slider',{name:'Minimum dB',exact:true})).toBeVisible()
  await expect(page.getByRole('slider',{name:'Maximum dB',exact:true})).toBeVisible()
  const dbMax=page.getByRole('spinbutton',{name:'Maximum dB',exact:true})
  await dbMax.fill('4');await dbMax.press('Tab')
  await expect.poll(()=>latest?.values.db._out).toBe(4)
  await page.getByRole('button',{name:'Close parameters',exact:true}).click()
  await page.getByRole('button',{name:'Disable audio engine',exact:true}).click()
})
