import { test, expect, type Page } from '@playwright/test'
async function setup(page: Page, partial = false) {
  const headers = { 'X-Pr0former': '1' }, status = await (await page.request.get('/api/status')).json()
  await page.request.post(`/api/${status.bootstrap ? 'register' : 'login'}`, { headers, data: { username: 'browser-test', password: 'test1234' } })
  const p = await (await page.request.post('/api/projects', { headers, data: { name: 'Extend with arrows', mode: 'structured' } })).json()
  p.parts.forEach((part: any) => { part.notes = []; part.loop_beats = partial ? 5 : 4 })
  p.score = { version: 1, length: partial ? 5 : 4, loop_score: false, meters: partial ? [{ beat: 4, beats: 3, unit: 8 }] : [], keys: [], repeats: [] }
  const url = `/api/projects/${p.id}`
  expect((await page.request.put(url, { headers, data: p })).ok()).toBe(true)
  const read = async () => (await (await page.request.get(url)).json()).project
  await page.goto('/')
  await page.getByRole('button', { name: 'Score & Parts', exact: true }).click()
  await page.getByRole('button', { name: 'Write', exact: true }).click()
  await page.locator('[data-score-part="part-1"] [data-staff-id]').first().click({ position: { x: 214, y: 118 } })
  await expect.poll(async () => (await read()).parts[0].notes.length).toBe(1)
  return read
}
test('completing the final bar prompts immediately and remembered consent extends quick entry', async ({ page }) => {
  const read = await setup(page)
  const caret = page.locator('[data-entry-caret]'), prompt = page.getByRole('dialog', { name: 'Add a new bar?', exact: true })
  // Setup entered the first quarter note. Fill the remaining three beats.
  await page.keyboard.press('5')
  await page.keyboard.press('5')
  await expect(prompt).toHaveCount(0)
  await page.keyboard.press('5')
  await expect(prompt).toBeVisible()
  await expect.poll(async () => (await read()).parts[0].notes.length).toBe(4)
  expect((await read()).score.length).toBe(4)
  await prompt.getByRole('checkbox').check()
  await prompt.getByRole('button', { name: 'Add bar', exact: true }).click()
  await expect(caret).toHaveAttribute('data-beat', '4')
  await expect.poll(async () => (await read()).score.length).toBe(8)
  // A whole note fills the newly appended bar and automatically adds the next.
  await page.keyboard.press('7')
  await expect.poll(async () => (await read()).score.length).toBe(12)
  await expect(caret).toHaveAttribute('data-beat', '8')
  await expect(prompt).toHaveCount(0)
  await page.keyboard.press('5')
  await expect.poll(async () => (await read()).parts[0].notes.at(-1).beat).toBe(8)
  await expect(page.getByRole('alert')).toHaveCount(0)
})
test('arrows confirm a new bar, cancel stays in bounds, and session consent survives reload', async ({ page }) => {
  const read = await setup(page)
  const caret = page.locator('[data-entry-caret]'), prompt = page.getByRole('dialog', { name: 'Add a new bar?', exact: true })
  await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('ArrowLeft')
  await expect(caret).toHaveAttribute('data-beat', '0')
  await expect(prompt).toHaveCount(0)
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('ArrowRight')
  await expect(prompt).toBeVisible()
  await prompt.getByRole('checkbox').check()
  await prompt.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(caret).toHaveAttribute('data-beat', '1')
  expect((await read()).score.length).toBe(4)
  await page.keyboard.press('ArrowRight')
  await expect(prompt.getByRole('checkbox')).not.toBeChecked()
  await expect(prompt.getByRole('button', { name: 'Add bar', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect.poll(async () => (await read()).score.length).toBe(8)
  await expect(caret).toHaveAttribute('data-beat', '4')
  expect((await read()).parts.every((p: any) => p.loop_beats === 8)).toBe(true)
  await page.keyboard.press('Shift+ArrowRight')
  await expect(prompt).toBeVisible()
  await prompt.getByRole('checkbox').check()
  await page.screenshot({ path: '/tmp/pr0-append-bar-confirm.png' })
  await prompt.getByRole('button', { name: 'Add bar', exact: true }).click()
  await expect.poll(async () => (await read()).score.length).toBe(12)
  await expect(caret).toHaveAttribute('data-beat', '8')
  await page.keyboard.press('ArrowRight')
  await expect.poll(async () => (await read()).score.length).toBe(16)
  await expect(caret).toHaveAttribute('data-beat', '12')
  await expect(prompt).toHaveCount(0)
  // Holding an arrow must not keep adding bars on key-repeat events.
  await page.locator('.score-workspace').dispatchEvent('keydown', { key: 'ArrowRight', code: 'ArrowRight', repeat: true, bubbles: true })
  expect((await read()).score.length).toBe(16)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect.poll(async () => (await read()).score.length).toBe(12)
  await page.reload()
  await page.getByRole('button', { name: 'Score & Parts', exact: true }).click()
  await page.getByRole('button', { name: 'Write', exact: true }).click()
  await page.locator('[data-score-part="part-1"] [data-staff-id]').first().click({ position: { x: 260, y: 140 } })
  for (let i = 0; i < 3; i++) await page.keyboard.press('Shift+ArrowRight')
  await expect.poll(async () => (await read()).score.length).toBe(16)
  await expect(prompt).toHaveCount(0)
  await expect(page.getByRole('alert')).toHaveCount(0)
})
test('new sessions ask again, completing a partial last bar in its current meter', async ({ page }) => {
  const read = await setup(page, true)
  const prompt = page.getByRole('dialog', { name: 'Add a new bar?', exact: true })
  await page.keyboard.press('Shift+ArrowRight')
  await expect(page.locator('[data-entry-caret]')).toHaveAttribute('data-beat', '4')
  await page.keyboard.press('ArrowRight')
  await expect(prompt).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('[data-entry-caret]')).toHaveAttribute('data-beat', '4')
  await page.keyboard.press('ArrowRight')
  await prompt.getByRole('button', { name: 'Add bar', exact: true }).click()
  await expect.poll(async () => (await read()).score.length).toBe(7)
  await expect(page.locator('[data-entry-caret]')).toHaveAttribute('data-beat', '5.5')
  await page.keyboard.press('4')
  await expect.poll(async () => (await read()).parts[0].notes.at(-1).beat).toBe(5.5)
  await expect(page.getByRole('alert')).toHaveCount(0)
})
