import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'
test('jazz chord tool places, edits and moves symbols, preserves notes, and round-trips MusicXML', async ({ page }) => {
  const headers = { 'X-Pr0former': '1' }, status = await (await page.request.get('/api/status')).json()
  await page.request.post(`/api/${status.bootstrap ? 'register' : 'login'}`, { headers, data: { username: 'browser-test', password: 'test1234' } })
  const p = await (await page.request.post('/api/projects', { headers, data: { name: 'Jazz chord chart', mode: 'structured' } })).json()
  p.parts[0].notes = []
  p.score = { version: 1, length: 8, loop_score: false, meters: [], keys: [], repeats: [] }
  const url = `/api/projects/${p.id}`
  expect((await page.request.put(url, { headers, data: p })).ok()).toBe(true)
  const read = async () => (await (await page.request.get(url)).json()).project
  const chords = async () => ((await read()).parts[0].staves?.[0]?.marks ?? []).filter((m: any) => m.kind === 'chord') as any[]
  await page.goto('/')
  await page.getByRole('button', { name: 'Score & Parts', exact: true }).click()
  const staff = page.locator('[data-score-part="part-1"] [data-staff-id]').first()
  await page.getByRole('button', { name: 'Chord tool', exact: true }).click()
  await staff.click({ position: { x: 240, y: 50 } })
  let modal = page.getByRole('dialog', { name: 'Add chord symbol', exact: true })
  await modal.getByLabel('Chord root', { exact: true }).selectOption('D')
  await modal.getByRole('button', { name: 'Chord quality m7', exact: true }).click()
  await expect(modal.getByLabel('Chord preview', { exact: true })).toHaveText('Dm7')
  await modal.getByRole('spinbutton', { name: 'At quarter beat', exact: true }).fill('0')
  await modal.getByRole('button', { name: 'Add chord', exact: true }).click()
  await expect.poll(async () => (await chords()).map(m => [m.beat, m.text])).toEqual([[0, 'Dm7']])
  for (const [beat, symbol] of [[2, 'G7♭9'], [4, 'Cmaj7/E']] as const) {
    // The chord tool remains active after each placement.
    await staff.click({ position: { x: 450, y: 50 } })
    await modal.getByLabel('Chord symbol', { exact: true }).fill(symbol)
    await modal.getByRole('spinbutton', { name: 'At quarter beat', exact: true }).fill(String(beat))
    await modal.getByLabel('Chord symbol', { exact: true }).press('Enter')
    await expect.poll(async () => (await chords()).length).toBe(beat === 2 ? 2 : 3)
  }
  expect((await read()).parts[0].notes).toEqual([])
  await page.keyboard.press('Escape')
  const firstId = (await chords())[0].id
  const first = page.locator(`[data-score-element*='"mark":"${firstId}"']`).first()
  await expect(first).toContainText('Dm7')
  const chordBox = await first.boundingBox(), staffBox = await staff.boundingBox()
  expect(chordBox!.y).toBeLessThan(staffBox!.y + 78)
  await first.locator('text').dblclick()
  modal = page.getByRole('dialog', { name: 'Edit chord symbol', exact: true })
  await modal.getByLabel('Chord symbol', { exact: true }).fill('Dm9')
  await page.screenshot({ path: '/tmp/pr0-chord-symbol-editor.png' })
  await modal.getByRole('button', { name: 'Save chord', exact: true }).click()
  await expect.poll(async () => (await chords())[0].text).toBe('Dm9')
  const box = (await first.locator('text').boundingBox())!
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down()
  await page.mouse.move(box.x + box.width / 2 + 35, box.y + box.height / 2, { steps: 5 })
  await page.mouse.up()
  await expect.poll(async () => (await chords()).find(m => m.id === firstId).beat).toBeGreaterThan(0)
  await page.screenshot({ path: '/tmp/pr0-jazz-chord-chart.png' })
  await first.locator('text').click()
  await page.keyboard.press('Delete')
  await expect.poll(async () => (await chords()).length).toBe(2)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect.poll(async () => (await chords()).length).toBe(3)
  await page.reload()
  await page.getByRole('button', { name: 'Score & Parts', exact: true }).click()
  await expect(page.locator(`[data-score-element*='"mark":"${firstId}"']`).first()).toContainText('Dm9')
  const before = (await chords()).map(m => [m.beat, m.text])
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'MusicXML', exact: true }).click()
  const xml = await readFile((await (await download).path())!, 'utf8')
  expect(xml).toContain('<harmony placement="above">')
  expect(xml).toContain('<kind text="7♭9">other</kind>')
  expect(xml).toContain('<bass-step>E</bass-step>')
  await page.locator('input[accept=".xml,.musicxml"]').setInputFiles({ name: 'jazz.musicxml', mimeType: 'application/xml', buffer: Buffer.from(xml) })
  await expect.poll(async () => (await chords()).map(m => [m.beat, m.text])).toEqual(before)
  await expect.poll(async () => (await chords()).some(m => m.id === firstId)).toBe(false)
  expect((await read()).parts[0].notes.every((n: any) => n.rest)).toBe(true)
  const invalid = await read()
  invalid.parts[0].staves[0].marks[0].text = 'x'.repeat(65)
  expect((await page.request.put(url, { headers, data: invalid })).status()).toBe(400)
  await expect(page.getByRole('alert')).toHaveCount(0)
  await page.getByRole('button', { name: 'Settings menu', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Help & documentation', exact: true }).click()
  await page.getByRole('button', { name: 'Score entry', exact: true }).click()
  await expect(page.locator('.score-entry-guide')).toContainText('Don’t ask again this session')
  await expect(page.locator('.score-entry-guide')).toContainText('Jazz chord symbols')
  await expect(page.locator('.score-entry-guide')).toContainText('they do not insert or play notes')
})
