import { test, expect } from '@playwright/test'
test('new part presets and percussion notation persist and engrave', async ({ page }) => {
  const headers = { 'X-Pr0former': '1' }, status = await (await page.request.get('/api/status')).json()
  await page.request.post(`/api/${status.bootstrap ? 'register' : 'login'}`, { headers, data: { username: 'browser-test', password: 'test1234' } })
  const p = await (await page.request.post('/api/projects', { headers, data: { name: 'Instrument presets', mode: 'structured' } })).json()
  const url = `/api/projects/${p.id}`, read = async () => (await (await page.request.get(url)).json()).project
  await page.goto('/')
  await page.getByRole('button', { name: 'Score & Parts', exact: true }).click()
  await page.getByRole('button', { name: 'Add part', exact: true }).click()
  const modal = page.getByRole('dialog', { name: 'New part', exact: true })
  await modal.getByRole('button', { name: 'Piano', exact: true }).click()
  await expect(modal.getByLabel('Staff layout')).toHaveValue('grand')
  await modal.getByRole('button', { name: 'Create part', exact: true }).click()
  await expect.poll(async () => (await read()).parts.at(-1).staves?.length).toBe(2)
  await page.getByRole('button', { name: 'Add part', exact: true }).click()
  await modal.getByRole('button', { name: 'Drum kit', exact: true }).click()
  await expect(modal.getByRole('combobox', { name: 'Clef', exact: true })).toHaveValue('percussion')
  await modal.getByRole('button', { name: 'Create part', exact: true }).click()
  await expect.poll(async () => (await read()).parts.at(-1).midi_channel).toBe(10)
  const project = await read(), drum = project.parts.at(-1)
  const heads = ['normal', 'cross', 'circle-cross', 'diamond', 'triangle', 'triangle-open', 'ghost']
  drum.notes = heads.map((head, i) => ({ id: `drum-${i}`, pitch: 64, beat: i, duration: 1, velocity: 100, rest: false, tied: false, notation: { staff: drum.staves[0].id, step: 30, alter: 0, voice: 1, base: 1, dots: 0, tuplet_actual: 1, tuplet_normal: 1, notehead: head, drum_mark: i === 0 ? 'buzz' : i === 1 ? 'roll-2' : 'none' } }))
  expect((await page.request.put(url, { headers, data: project })).ok()).toBe(true)
  await page.reload()
  await page.getByRole('button', { name: 'Score & Parts', exact: true }).click()
  await page.locator(`[data-score-part="${drum.id}"] [data-staff-id]`).first().scrollIntoViewIfNeeded()
  await expect(page.locator('[data-note-id="drum-6"]').first()).toBeVisible()
  await page.screenshot({ path: '/tmp/pr0former-percussion.png' })
  await page.locator('[data-note-id="drum-3"]').first().dblclick()
  const editor = page.getByRole('dialog', { name: 'Edit selected notes', exact: true })
  await editor.getByLabel('Notehead', { exact: true }).selectOption('cross')
  await expect.poll(async () => (await read()).parts.at(-1).notes[3].notation.notehead).toBe('cross')
  await editor.getByLabel('Drum stem mark', { exact: true }).selectOption('roll-3')
  await expect.poll(async () => (await read()).parts.at(-1).notes[3].notation.drum_mark).toBe('roll-3')
  await expect(page.getByRole('alert')).toHaveCount(0)
  const invalid = await read()
  invalid.parts.at(-1).notes[0].notation.notehead = 'invalid'
  expect((await page.request.put(url, { headers, data: invalid })).ok()).toBe(false)
})
