import { test, expect, type Page } from '@playwright/test'
const headers = { 'X-Pr0former': '1' }
async function setup(page: Page, filled: boolean) {
  const status = await (await page.request.get('/api/status')).json()
  await page.request.post(`/api/${status.bootstrap ? 'register' : 'login'}`, { headers, data: { username: 'browser-test', password: 'test1234' } })
  const p = await (await page.request.post('/api/projects', { headers, data: { name: 'Score deletion', mode: 'structured' } })).json()
  const note = (id: string, beat: number, rest = false) => ({ id, pitch: 60, beat, duration: 1, velocity: 90, rest, tied: false })
  p.parts[0].notes = filled ? [note('a', 0), note('b', 1), note('rest', 2, true), note('d', 3), note('next-bar', 4)] : []
  p.score = { version: 1, length: 16, loop_score: false, meters: [], keys: [], repeats: [] }
  const url = `/api/projects/${p.id}`
  expect((await page.request.put(url, { headers, data: p })).ok()).toBe(true)
  const read = async () => (await (await page.request.get(url)).json()).project
  const notes = async () => (await read()).parts[0].notes as any[]
  const beats = async () => Object.fromEntries((await notes()).map(n => [n.id, n.beat]))
  await page.goto('/')
  await page.getByRole('button', { name: 'Score & Parts', exact: true }).click()
  return { url, read, notes, beats }
}
test('note and rest deletion closes a bar, supports multi-select, undo and reload', async ({ page }) => {
  const { url, read, beats } = await setup(page, true)
  await page.getByRole('button', { name: 'Select', exact: true }).click()
  await page.locator('[data-note-id="b"]').first().click()
  await page.keyboard.press('Delete')
  await expect.poll(beats).toEqual({ a: 0, rest: 1, d: 2, 'next-bar': 4 })
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect.poll(beats).toEqual({ a: 0, b: 1, rest: 2, d: 3, 'next-bar': 4 })
  await page.locator('[data-note-id="rest"]').first().click()
  await page.keyboard.press('Backspace')
  await expect.poll(beats).toEqual({ a: 0, b: 1, d: 2, 'next-bar': 4 })
  await page.locator('[data-note-id="a"]').first().click()
  await page.locator('[data-note-id="b"]').first().click({ modifiers: ['ControlOrMeta'] })
  await page.keyboard.press('Delete')
  await expect.poll(beats).toEqual({ d: 0, 'next-bar': 4 })
  await page.reload()
  await page.getByRole('button', { name: 'Score & Parts', exact: true }).click()
  await expect(page.locator('[data-note-id="d"]').first()).toHaveAttribute('data-score-beat', '0')
  // Make an automatic rest between notes, then delete its rendered symbol.
  const p = await read()
  p.parts[0].notes[0].beat = 2
  if (p.parts[0].notes[0].notation) p.parts[0].notes[0].notation.onset = { numerator: 2, denominator: 1 }
  expect((await page.request.put(url, { headers, data: p })).ok()).toBe(true)
  await page.getByRole('button', { name: 'Select', exact: true }).click()
  const rest = page.locator(`[data-score-element*='"kind":"rest"'][data-score-element*='"beat":0,']`).first()
  await rest.click()
  await page.keyboard.press('Delete')
  await expect.poll(beats).toEqual({ d: 0, 'next-bar': 4 })
  await expect(page.getByRole('alert')).toHaveCount(0)
})

test('quick entry chooses rest lengths, dotted notes and ties, then closes a caret deletion', async ({ page }) => {
  const { notes } = await setup(page, false)
  await page.getByRole('button', { name: 'Write', exact: true }).click()
  const staff = page.locator('[data-score-part="part-1"] [data-staff-id]').first()
  await staff.click({ position: { x: 214, y: 118 } })
  await expect.poll(async () => (await notes()).length).toBe(1)
  for (const key of ['r', '4', 'r']) await page.keyboard.press(key)
  await expect.poll(async () => (await notes()).length).toBe(2)
  expect((await notes())[1]).toMatchObject({ beat: 1, duration: 0.5, rest: true })
  for (const key of ['.', '5', '.', '.']) await page.keyboard.press(key)
  await expect.poll(async () => (await notes()).length).toBe(3)
  expect((await notes())[2]).toMatchObject({ beat: 1.5, duration: 1.5, rest: false, notation: { dots: 1 } })
  await page.keyboard.press('t')
  await expect(page.getByText('tie pending', { exact: false })).toBeVisible()
  await page.keyboard.press('5')
  await expect.poll(async () => (await notes()).length).toBe(4)
  let written = await notes()
  expect(written[2].notation.tie_to).toBe(written[3].id)
  expect(written[3]).toMatchObject({ beat: 3, duration: 1, pitch: written[2].pitch })
  await page.keyboard.press('0')
  for (const key of ['r', '6', 'r']) await page.keyboard.press(key)
  await expect.poll(async () => (await notes()).length).toBe(6)
  written = await notes()
  expect(written[4]).toMatchObject({ beat: 4, duration: 1, rest: true })
  expect(written[5]).toMatchObject({ beat: 5, duration: 2, rest: true })
  await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('Backspace')
  await expect.poll(async () => (await notes()).length).toBe(5)
  expect((await notes()).at(-1)).toMatchObject({ beat: 4, duration: 2, rest: true })
  await expect(page.locator('[data-entry-caret]')).toHaveAttribute('data-beat', '4')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect.poll(async () => (await notes()).length).toBe(6)
  await expect(page.getByRole('alert')).toHaveCount(0)
})

test('score entry documentation explains rest lengths, dots, ties and deletion on desktop and mobile', async ({ page }) => {
  await setup(page, false)
  await page.getByRole('button', { name: 'Settings menu', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Help & documentation', exact: true }).click()
  await page.getByRole('button', { name: 'Score entry', exact: true }).click()
  const guide = page.locator('.score-entry-guide')
  await expect(guide.getByRole('heading', { name: 'Score entry', exact: true })).toBeVisible()
  await expect(guide).toContainText('R → 5 → R')
  await expect(guide).toContainText('no dots → one dot → two dots → no dots')
  await expect(guide).toContainText('5 → T → 5')
  await expect(guide).toContainText('same bar, staff and voice')
  await guide.getByRole('heading', { name: 'Quick entry: rests and their lengths' }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: '/tmp/pr0-score-entry-help.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  await guide.getByRole('heading', { name: 'Keyboard reference' }).scrollIntoViewIfNeeded()
  expect(await guide.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: '/tmp/pr0-score-entry-help-phone.png' })
})
