import {test,expect} from '@playwright/test'
const headers={'X-Pr0former':'1'}
test('sliders commit hundredths, keep integers whole and space node labels',async({page})=>{
 const status=await(await page.request.get('/api/status')).json()
 await page.request.post(`/api/${status.bootstrap?'register':'login'}`,{headers,data:{username:'browser-test',password:'test1234'}})
 let p=await(await page.request.post('/api/projects',{headers,data:{name:'Slider precision',mode:'freeform'}})).json()
 const node=(id:string,kind:string,x:number,parameters:any)=>({id,kind,label:id,x,y:0,channels:1,parameters})
 p.parts=[];p.graph={nodes:[node('Tone','oscillator',0,{frequency:440,amplitude:.123456}),{...node('Slider','control_input',400,{mode:3,min:-10,max:10}),control_value:.123456},node('Sampler','poly_sampler',800,{root_note:60})],edges:[]}
 expect((await page.request.put(`/api/projects/${p.id}`,{headers,data:p})).ok()).toBe(true)
 const load=async()=>(await(await page.request.get(`/api/projects/${p.id}`)).json()).project
 await page.goto('/')
 await page.getByRole('button',{name:'Edit Tone',exact:true}).click()
 const modal=page.getByRole('dialog'),amp=modal.locator('#param-amplitude')
 await expect(amp).toHaveValue('0.12');await expect(modal.locator('#param-frequency')).toHaveValue('440')
 await expect(modal.getByRole('slider',{name:'Amplitude',exact:true})).toHaveAttribute('step','0.01')
 await amp.fill('0.45678');await amp.press('Tab')
 await expect.poll(async()=>(await load()).graph.nodes[0].parameters.amplitude).toBe(.46)
 await expect(amp).toHaveValue('0.46')
 await modal.getByRole('slider',{name:'Amplitude',exact:true}).focus();await page.keyboard.press('ArrowRight')
 await expect.poll(async()=>(await load()).graph.nodes[0].parameters.amplitude).toBe(.47)
 const label=await modal.locator('label[for="node-name"]').boundingBox(),field=await modal.locator('#node-name').boundingBox()
 expect(field!.y-(label!.y+label!.height)).toBeGreaterThanOrEqual(10)
 await page.screenshot({path:'test-results/node-parameter-spacing.png'})
 await page.getByRole('button',{name:'Close parameters'}).click()
 const slider=page.getByLabel('Slider slider',{exact:true}),value=page.getByLabel('Slider value',{exact:true})
 await expect(value).toHaveValue('0.12');await expect(slider).toHaveAttribute('step','0.01')
 await value.fill('-1.23456');await value.press('Tab')
 await expect.poll(async()=>(await load()).graph.nodes[1].control_value).toBe(-1.23)
 await expect(value).toHaveValue('-1.23')
 await page.getByRole('button',{name:'Edit Sampler',exact:true}).click()
 await expect(modal.locator('#param-root_note')).toHaveValue('60')
 await expect(modal.getByRole('slider',{name:'Root MIDI note',exact:true})).toHaveAttribute('step','1')
 await page.getByRole('button',{name:'Close parameters'}).click()
 p=await load();p.graph.nodes.push({...node('Source','control_input',1200,{mode:2}),control_value:.123456})
 p.graph.edges.push({id:'drive-slider',source:'Source',source_port:'out',target:'Slider',target_port:'in'})
 expect((await page.request.put(`/api/projects/${p.id}`,{headers,data:p})).ok()).toBe(true)
 await page.getByRole('button',{name:'Enable audio engine',exact:true}).click()
 await expect(page.locator('.vue-flow__node[data-id="Slider"] output')).toHaveText('0.12')
 expect((await load()).graph.nodes.find((n:any)=>n.id==='Source').control_value).toBe(.123456)
 await page.getByRole('button',{name:'Disable audio engine',exact:true}).click()
})
