import {test,expect} from '@playwright/test'
const headers={'X-Pr0former':'1'}
test('subgraph state management, transient recall, exact glow scope, and reduced motion',async({page})=>{
 test.setTimeout(120000)
 const status=await(await page.request.get('/api/status')).json()
 await page.request.post(`/api/${status.bootstrap?'register':'login'}`,{headers,data:{username:'browser-test',password:'test1234'}})
 let p=await(await page.request.post('/api/projects',{headers,data:{name:'Saved states',mode:'freeform'}})).json()
 const node=(id:string,kind:string,parent:string|null,x:number,parameters={})=>({id,kind,parent,label:id,x,y:0,channels:1,parameters})
 p.parts=[];p.graph={nodes:[node('Root','subgraph',null,0),node('Value','value','Root',0,{value:5}),node('Smooth','smooth_change','Root',300,{curve:0,time:400}),node('Nested','subgraph','Root',600),node('Deep','value','Nested',0,{value:3})],edges:[{id:'vs',source:'Value',source_port:'out',target:'Smooth',target_port:'in'}]}
 const saved=await page.request.put(`/api/projects/${p.id}`,{headers,data:p});expect(saved.ok(),await saved.text()).toBe(true);p=await saved.json()
 const load=async()=>(await(await page.request.get(`/api/projects/${p.id}`)).json()).project
 let telemetry:any;const events:any[]=[]
 page.on('websocket',socket=>socket.on('framereceived',({payload})=>{const m=JSON.parse(String(payload));if(m.type==='telemetry')telemetry=m;if(m.type==='state_recalled')events.push(m)}))
 await page.goto('/')
 await expect(page.getByRole('button',{name:'Save state',exact:true})).toHaveCount(0)
 const button=page.getByRole('button',{name:'Open Root',exact:true}),outer=page.locator('.vue-flow__node[data-id="Root"]')
 await expect(button).toBeVisible()
 const b=await button.boundingBox(),r=await outer.boundingBox();expect(Math.abs((b!.x+b!.width/2)-(r!.x+r!.width/2))).toBeLessThan(2)
 await button.click();await page.getByRole('button',{name:'Save state',exact:true}).click()
 await expect.poll(async()=>(await load()).graph.nodes[0].states?.slots.length).toBe(1)
 await page.getByRole('button',{name:'Manage states',exact:true}).click()
 await expect(page.getByRole('button',{name:'Load state 1',exact:true})).toBeDisabled()
 await page.getByLabel('State 1 name',{exact:true}).fill(' Quiet ');await page.getByLabel('State 1 name',{exact:true}).press('Tab')
 await expect.poll(async()=>(await load()).graph.nodes[0].states.slots[0].name).toBe('Quiet')
 await page.getByRole('button',{name:'Close states'}).click()
 p=await load();p.graph.nodes[1].parameters.value=20;p.graph.nodes.push(node('New','value','Root',900,{value:99}))
 expect((await page.request.put(`/api/projects/${p.id}`,{headers,data:p})).ok()).toBe(true)
 await page.getByRole('button',{name:'Enable audio engine',exact:true}).click()
 await expect.poll(()=>telemetry?.values?.Value?.value).toBe(20)
 const revision=(await load()).revision
 await page.getByRole('button',{name:'Manage states',exact:true}).click()
 await page.getByRole('button',{name:'Load state 1',exact:true}).click()
 await expect.poll(()=>events.length).toBe(1)
 await expect(page.locator('.vue-flow__node[data-id="Smooth"]')).toHaveClass(/state-recalled/)
 await expect(page.locator('.vue-flow__node[data-id="Value"]')).toHaveClass(/state-recalled/)
 await expect(page.locator('.vue-flow__node[data-id="New"]')).not.toHaveClass(/state-recalled/)
 expect(events[0].restored).toEqual(['Value','Smooth','Nested','Deep'])
 await expect.poll(()=>telemetry?.values?.Smooth?._out).toBe(5)
 expect((await load()).revision).toBe(revision);expect((await load()).graph.nodes[1].parameters.value).toBe(20)
 await expect(page.locator('.vue-flow__node[data-id="Value"]')).not.toHaveClass(/state-recalled/)
 await page.getByRole('button',{name:'Load state 1',exact:true}).click()
 await expect.poll(()=>events.length).toBe(2)
 expect(events[1].event_id).not.toBe(events[0].event_id)
 await expect(page.locator('.vue-flow__node[data-id="Value"]')).toHaveClass(/state-recalled/)
 const previousGlow=await page.locator('.vue-flow__node[data-id="Value"]').getAttribute('class')
 await page.getByRole('button',{name:'Load state 1',exact:true}).click()
 await expect.poll(()=>events.length).toBe(3)
 await expect(page.locator('.vue-flow__node[data-id="Value"]')).not.toHaveAttribute('class',previousGlow!)
 await page.getByRole('button',{name:'Close states'}).click()
 await page.getByRole('button',{name:'Open Nested',exact:true}).click()
 await expect(page.locator('.vue-flow__node[data-id="Deep"]')).not.toHaveClass(/state-recalled/)
 await page.getByRole('navigation',{name:'Graph path'}).getByRole('button',{name:'Root',exact:true}).click()
 await expect(page.locator('[class*="state-recalled-"]')).toHaveCount(0)
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.getByRole('button',{name:'Light graph theme',exact:true}).click()
 await page.getByRole('button',{name:'Manage states',exact:true}).click()
 await page.getByRole('button',{name:'Load state 1',exact:true}).click()
 await expect.poll(()=>events.length).toBe(4)
 expect(await page.locator('.vue-flow__node[data-id="Value"]').evaluate(el=>getComputedStyle(el,'::after').animationName)).toBe('none')
 await page.screenshot({path:'test-results/state-recall-light-reduced-motion.png'})
 await page.getByRole('button',{name:'Close states'}).click()
 await page.getByRole('button',{name:'Save state',exact:true}).click()
 await expect.poll(async()=>(await load()).graph.nodes[0].states.slots.length).toBe(2)
 expect((await load()).graph.nodes[0].states.slots[1].nodes.find((n:any)=>n.id==='Value').parameters.value).toBe(5)
 await expect(page.locator('[class*="state-recalled-"]')).toHaveCount(0)
 const bad=await page.request.post(`/api/projects/${p.id}/subgraphs/Root/recall`,{headers,data:{selector:'1'}});expect(bad.status()).toBe(400)
 expect(events.length).toBe(4)
 await page.getByRole('button',{name:'Disable audio engine',exact:true}).click()
 await page.reload();await expect(page.locator('[class*="state-recalled-"]')).toHaveCount(0)
})

test('State input recalls repeated numeric events, suppresses held values, and accepts exact text names',async({page})=>{
 test.setTimeout(120000)
 const status=await(await page.request.get('/api/status')).json()
 await page.request.post(`/api/${status.bootstrap?'register':'login'}`,{headers,data:{username:'browser-test',password:'test1234'}})
 let p=await(await page.request.post('/api/projects',{headers,data:{name:'State input',mode:'freeform'}})).json()
 const node=(id:string,kind:string,parent:string|null,parameters={})=>({id,kind,parent,label:id,x:0,y:0,channels:1,parameters})
 p.parts=[];p.graph={nodes:[node('Root','subgraph',null),node('Value','value','Root',{value:5}),node('Selector','value',null,{value:1}),node('Bang','trigger',null)],edges:[{id:'trigger',source:'Bang',source_port:'out',target:'Selector',target_port:'trigger'},{id:'state',source:'Selector',source_port:'out',target:'Root',target_port:'state'}]}
 p=await(await page.request.put(`/api/projects/${p.id}`,{headers,data:p})).json()
 p=await(await page.request.post(`/api/projects/${p.id}/subgraphs/Root/states`,{headers,data:{revision:p.revision,action:'save'}})).json()
 p.graph.nodes[1].parameters.value=20;p=await(await page.request.put(`/api/projects/${p.id}`,{headers,data:p})).json()
 let telemetry:any;const events:any[]=[]
 page.on('websocket',socket=>socket.on('framereceived',({payload})=>{const m=JSON.parse(String(payload));if(m.type==='telemetry')telemetry=m;if(m.type==='state_recalled')events.push(m)}))
 await page.goto('/');await page.getByRole('button',{name:'Enable audio engine',exact:true}).click()
 await expect.poll(()=>telemetry?.values?.Value?.value).toBe(20)
 const bang=async()=>{const response=await page.request.put(`/api/projects/${p.id}/control`,{headers,data:{node:'Bang',revision:p.revision,value:null}});expect(response.ok(),await response.text()).toBe(true)}
 await bang();await expect.poll(()=>events.length).toBe(1);await expect.poll(()=>telemetry?.values?.Value?.value).toBe(5)
 p=await(await page.request.put(`/api/projects/${p.id}/parameter`,{headers,data:{node:'Value',parameter:'value',value:50,revision:p.revision}})).json()
 await bang();await expect.poll(()=>events.length).toBe(2);await expect.poll(()=>telemetry?.values?.Value?.value).toBe(5)
 const sequence=telemetry.sequence;await expect.poll(()=>telemetry?.sequence).toBeGreaterThan(sequence+12);expect(events.length).toBe(2)
 p=await(await page.request.post(`/api/projects/${p.id}/subgraphs/Root/states`,{headers,data:{revision:p.revision,action:'rename',slot:1,name:'1'}})).json()
 p.graph.nodes[2]={...node('Selector','control_input',null,{mode:4}),control_value:'1'};p.graph.edges=p.graph.edges.filter((e:any)=>e.id!=='trigger');p.graph.nodes[1].parameters.value=21
 const response=await page.request.put(`/api/projects/${p.id}`,{headers,data:p});expect(response.ok(),await response.text()).toBe(true)
 await expect.poll(()=>events.length).toBe(3);await expect.poll(()=>telemetry?.values?.Value?.value).toBe(5)
 await page.getByRole('button',{name:'Disable audio engine',exact:true}).click()
})
