import { test, expect } from '@playwright/test'

test('nested subgraph ports, live edits, naming, duplication and subtree undo', async ({ page }) => {
  const headers = {'X-Pr0former':'1'}
  const status = await (await page.request.get('/api/status')).json()
  await page.request.post(`/api/${status.bootstrap?'register':'login'}`,{headers,data:{username:'browser-test',password:'test1234'}})
  const p = await (await page.request.post('/api/projects',{headers,data:{name:'Nested patches',mode:'structured'}})).json()
  const node=(id:string,kind:string,parent:string|null,x:number,parameters={})=>({id,kind,parent,label:id,x,y:100,channels:2,parameters})
  const edge=(id:string,source:string,source_port:string,target:string,target_port:string)=>({id,source,source_port,target,target_port})
  p.parts=[]
  p.graph={nodes:[node('Source','value',null,0,{value:3}),node('Outer','subgraph',null,300),node('Result','value',null,650),node('Outer in','subgraph_input_control','Outer',0),node('Inner','subgraph','Outer',300),node('Outer out','subgraph_output_control','Outer',650),node('Inner in','subgraph_input_control','Inner',0),node('Calculation','add','Inner',300,{b:4}),node('Inner out','subgraph_output_control','Inner',650)],edges:[edge('e1','Source','out','Outer','Outer in'),edge('e2','Outer in','out','Inner','Inner in'),edge('e3','Inner in','out','Calculation','a'),edge('e4','Calculation','out','Inner out','in'),edge('e5','Inner','Inner out','Outer out','in'),edge('e6','Outer','Outer out','Result','value')]}
  expect((await page.request.put(`/api/projects/${p.id}`,{headers,data:p})).ok()).toBe(true)
  const load=async()=>(await (await page.request.get(`/api/projects/${p.id}`)).json()).project
  let latest:any
  page.on('websocket',socket=>socket.on('framereceived',({payload})=>{const m=JSON.parse(String(payload));if(m.type==='telemetry')latest=m}))
  await page.goto('/')
  await page.getByLabel('Count in', { exact: true }).selectOption('0')
  await page.getByRole('button',{name:'Play',exact:true}).click()
  await expect.poll(()=>latest?.values?.Result?.value).toBe(7)
  await expect(page.locator('.vue-flow__node')).toHaveCount(3)
  await page.getByLabel('Search nodes').fill('Subgraph control input')
  await expect(page.getByLabel('Search nodes')).toHaveValue('Subgraph control input')
  await expect(page.locator('.node-library-content>.library-list .library-node')).toHaveCount(0)
  await page.getByRole('button',{name:'Open Outer',exact:true}).click()
  await expect(page.locator('.node-library-content>.library-list .library-node')).toHaveCount(1)
  await expect(page.locator('.vue-flow__node')).toHaveCount(3)
  await page.getByRole('button',{name:'Open Inner',exact:true}).click()
  await expect(page.getByRole('navigation',{name:'Graph path'})).toContainText('Outer / Inner')
  await page.screenshot({path:'../docs/nested-subgraph.png'})
  await page.getByRole('button',{name:'Edit Calculation',exact:true}).click()
  await page.getByRole('spinbutton',{name:'B',exact:true}).fill('9')
  await page.getByRole('spinbutton',{name:'B',exact:true}).press('Tab')
  await expect.poll(()=>latest?.values?.Result?.value).toBe(12)
  await page.getByLabel('Node name').fill('d')
  await expect.poll(async()=>(await load()).graph.nodes.length).toBe(9)
  await page.getByLabel('Node name').fill('Calculation')
  await page.getByRole('button',{name:'Close parameters'}).click()
  await page.getByRole('button',{name:'Edit Inner out',exact:true}).click()
  await page.getByLabel('Node name').fill('Modulation')
  await page.getByLabel('Node name').press('Tab')
  await expect.poll(async()=>(await load()).graph.nodes.find((n:any)=>n.id==='Inner out').label).toBe('Modulation')
  await page.getByRole('button',{name:'Close parameters'}).click()
  await page.getByRole('navigation',{name:'Graph path'}).getByRole('button',{name:'Outer',exact:true}).click()
  await expect(page.locator('.vue-flow__node[data-id="Inner"]')).toContainText('Modulation')
  await page.getByRole('navigation',{name:'Graph path'}).getByRole('button',{name:'Root graph',exact:true}).click()
  await page.locator('.vue-flow__node[data-id="Outer"] .patch-node').click({button:'right'})
  await page.getByRole('menuitem',{name:'Duplicate node D',exact:true}).click()
  await expect.poll(async()=>(await load()).graph.nodes.length).toBe(16)
  await expect.poll(()=>latest?.values?.Result?.value).toBe(12)
  const copy=(await load()).graph.nodes.find((n:any)=>n.kind==='subgraph'&&!n.parent&&n.id!=='Outer')
  await expect(page.getByRole('button',{name:'Undo',exact:true})).toBeEnabled()
  await page.locator(`.vue-flow__node[data-id="${copy.id}"] .patch-node`).press('d')
  await expect.poll(async()=>(await load()).graph.nodes.length).toBe(23)
  await page.getByRole('button',{name:'Undo',exact:true}).click()
  await expect.poll(async()=>(await load()).graph.nodes.length).toBe(16)
  await page.locator(`.vue-flow__node[data-id="${copy.id}"] .patch-node`).click({button:'right'})
  await page.getByRole('menuitem',{name:'Delete node',exact:true}).click()
  await expect.poll(async()=>(await load()).graph.nodes.length).toBe(9)
  expect(latest.running).toBe(true)
  await page.getByRole('button',{name:'Undo',exact:true}).click()
  await expect.poll(async()=>(await load()).graph.nodes.length).toBe(16)
  await page.getByRole('button', { name: 'Disable audio engine', exact: true }).click()
})
