import {test,expect} from '@playwright/test'
test('compact trigger passes input and remains manually clickable without graph edits',async({page})=>{
  const headers={'X-Pr0former':'1'},status=await(await page.request.get('/api/status')).json()
  await page.request.post(`/api/${status.bootstrap?'register':'login'}`,{headers,data:{username:'browser-test',password:'test1234'}})
  let p=await(await page.request.post('/api/projects',{headers,data:{name:'Trigger workspace',mode:'freeform'}})).json()
  const node=(id:string,kind:string,x:number,parameters={})=>({id,kind,label:id,x,y:0,channels:1,parameters})
  p.parts=[];p.graph={nodes:[node('Pulse','trigger',300),node('Source','value',0,{value:0}),node('Count','counter',520)],edges:[{id:'in',source:'Source',source_port:'out',target:'Pulse',target_port:'in'},{id:'count',source:'Pulse',source_port:'out',target:'Count',target_port:'trigger'}]}
  expect((await page.request.put(`/api/projects/${p.id}`,{headers,data:p})).ok()).toBe(true)
  const load=async()=>(await(await page.request.get(`/api/projects/${p.id}`)).json()).project
  const param=async(value:number)=>{const current=await load();expect((await page.request.put(`/api/projects/${p.id}/parameter`,{headers,data:{node:'Source',parameter:'value',value,revision:current.revision}})).ok()).toBe(true)}
  let latest:any;page.on('websocket',s=>s.on('framereceived',({payload})=>{const m=JSON.parse(String(payload));if(m.type==='telemetry')latest=m}))
  await page.goto('/')
  const button=page.getByRole('button',{name:'Trigger Pulse',exact:true})
  await expect(button).toBeDisabled()
  await page.getByRole('button',{name:'Enable audio engine',exact:true}).click()
  await expect(button).toBeEnabled()
  const nodeBox=page.locator('.vue-flow__node[data-id="Pulse"] .patch-node')
  expect(await nodeBox.locator('button').count()).toBe(1)
  expect(await nodeBox.innerText()).toBe('')
  expect(await nodeBox.evaluate(el=>parseFloat(getComputedStyle(el).width))).toBeLessThan(110)
  const revision=(await load()).revision
  await button.click()
  await expect.poll(()=>latest?.values.Count._out).toBe(1)
  await expect.poll(()=>latest?.values.Pulse._out).toBe(0)
  await expect(button).toHaveAttribute('aria-pressed','false')
  expect((await load()).revision).toBe(revision)
  await param(-2)
  await expect.poll(()=>latest?.values.Pulse._out).toBe(-2)
  await expect(button).toHaveAttribute('aria-pressed','true')
  await button.focus();await page.keyboard.press('Space')
  await expect.poll(()=>latest?.values.Count._out).toBe(2)
  await expect.poll(()=>latest?.values.Pulse._out).toBe(-2)
  expect(latest.running).toBe(false)
  await param(1)
  await expect.poll(()=>latest?.values.Pulse._out).toBe(1)
  await expect(button).toHaveAttribute('aria-pressed','true')
  await page.screenshot({path:'test-results/trigger.png'})
  await param(0)
  await expect(button).toHaveAttribute('aria-pressed','false')
  const current=await load()
  expect((await page.request.put(`/api/projects/${p.id}/control`,{headers,data:{node:'Pulse',revision:current.revision,value:1}})).status()).toBe(400)
  expect((await page.request.put(`/api/projects/${p.id}/control`,{data:{node:'Pulse',revision:current.revision}})).ok()).toBe(false)
  await nodeBox.focus();await expect(nodeBox).toBeFocused();await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button',{name:'Close parameters'}).click()
  await page.getByRole('button',{name:'Disable audio engine',exact:true}).click()
  await expect(button).toBeDisabled()
})
