import { test, expect } from '@playwright/test'
const headers = { 'X-Pr0former': '1' }
test('users edit their own profile and avatar from the account menu and change passwords securely', async ({ browser, request, playwright }) => {
  const status = await (await request.get('/api/status')).json()
  await request.post(`/api/${status.bootstrap ? 'register' : 'login'}`, { headers, data: { username: 'browser-test', password: 'test1234' } })
  const username = `profile-${Date.now()}`
  const created = await request.post('/api/admin/users', { headers, data: { username, password: 'password123', is_admin: false, enabled: true, fields: {} } })
  expect(created.ok()).toBeTruthy()
  const context = await browser.newContext({ baseURL: 'http://127.0.0.1:3101' })
  const other = await playwright.request.newContext({ baseURL: 'http://127.0.0.1:3101' })
  try {
    for (const client of [context.request, other]) expect((await client.post('/api/login', { headers, data: { username, password: 'password123' } })).ok()).toBeTruthy()
    const page = await context.newPage()
    await page.goto('/')
    // No performance is required to manage an account.
    await page.locator('.dialog-card').getByRole('button', { name: 'Close', exact: true }).click()
    await page.getByRole('button', { name: 'User menu', exact: true }).click()
    await expect(page.getByRole('menuitem', { name: 'Sign out', exact: true })).toBeEnabled()
    await page.getByRole('menuitem', { name: 'Edit user profile', exact: true }).click()
    const profile = page.getByRole('dialog', { name: 'Edit user profile', exact: true })
    await profile.getByLabel('First name', { exact: true }).fill('Ada')
    await profile.getByLabel('Organization', { exact: true }).fill('Local ensemble')
    await profile.getByRole('button', { name: 'Save profile', exact: true }).click()
    await expect(profile.getByRole('status')).toHaveText('Profile saved.')
    await profile.getByLabel('Upload avatar', { exact: false }).setInputFiles({ name: 'avatar.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAIAAAABCAIAAAB7QOjdAAAAD0lEQVR4nGMIOHFhw4QLAA0PA/m5zYg7AAAAAElFTkSuQmCC', 'base64') })
    await expect(profile.getByRole('status')).toHaveText('Avatar updated.')
    await expect(profile.getByRole('img', { name: 'Your avatar' })).toBeVisible()
    await page.screenshot({ path: 'test-results/user-profile.png' })
    const account = page.getByRole('button', { name: 'User menu', exact: true })
    await expect(account.getByRole('img', { name: 'Your avatar' })).toHaveAttribute('src', /avatar\?v=1/)
    await profile.getByLabel('Current password', { exact: true }).fill('wrong-password')
    await profile.getByLabel('New password', { exact: true }).fill('new-password123')
    await profile.getByLabel('Confirm new password', { exact: true }).fill('new-password123')
    await profile.getByRole('button', { name: 'Save profile', exact: true }).click()
    await expect(profile.getByRole('alert')).toContainText('Current password is incorrect')
    await profile.getByLabel('Current password', { exact: true }).fill('password123')
    await profile.getByRole('button', { name: 'Save profile', exact: true }).click()
    await expect(profile.getByRole('status')).toContainText('Other sessions signed out')
    expect((await other.get('/api/me')).status()).toBe(401)
    const me = await (await context.request.get('/api/me')).json()
    expect(me.first_name).toBe('Ada'); expect(me.organization).toBe('Local ensemble'); expect(me.is_admin).toBe(false)
    expect((await context.request.put('/api/me', { headers, data: { username, revision: me.revision, fields: {}, is_admin: true } })).status()).toBe(422)
    expect((await context.request.put('/api/me', { headers, data: { username, revision: 0, fields: {} } })).status()).toBe(409)
    await profile.getByRole('button', { name: 'Close user profile' }).click()
    await account.click(); await page.getByRole('menuitem', { name: 'Edit user profile' }).click()
    await expect(profile.getByLabel('First name', { exact: true })).toHaveValue('Ada')
    await profile.getByRole('button', { name: 'Close user profile' }).click()
    await account.click(); await page.getByRole('menuitem', { name: 'Sign out', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible()
    expect((await other.post('/api/login', { headers, data: { username, password: 'password123' } })).status()).toBe(401)
    expect((await other.post('/api/login', { headers, data: { username, password: 'new-password123' } })).ok()).toBeTruthy()
  } finally { await context.close(); await other.dispose() }
})
