import { readFile } from 'node:fs/promises'
import { test, expect } from '@playwright/test'

test('create a project, inspect a driven parameter, and edit an unconnected value', async ({ page }) => {
  test.setTimeout(120000)
  page.setDefaultTimeout(10000)
  let latest: any
  page.on('websocket', socket => socket.on('framereceived', ({ payload }) => {
    const message = JSON.parse(String(payload))
    if (message.type === 'telemetry') latest = message
  }))
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.addInitScript(() => {
    const Native = window.RTCPeerConnection
    ;(window as any).__audioPeers = []
    window.RTCPeerConnection = class extends Native { constructor(config?: RTCConfiguration) { super(config); (window as any).__audioPeers.push(this) } }
  })
  await page.goto('/')
  const status = await (await page.request.get('/api/status')).json()
  const username = 'browser-test'
  await page.getByLabel('Username', { exact: true }).fill(username)
  await page.getByLabel('Password', { exact: true }).fill('test1234')
  await page.getByRole('button', { name: status.bootstrap ? 'Create account' : 'Sign in', exact: true }).click()
  if (!status.bootstrap) {
    await page.getByRole('button', { name: 'Choose project' }).click()
    await page.getByRole('button', { name: 'New project', exact: true }).click()
  }
  await page.getByLabel('Project name').fill('Nocturne / signal studies')
  await page.getByRole('button', { name: 'Create performance', exact: true }).click()
  await expect(page.locator('.patch-node')).toHaveCount(6)
  await page.getByRole('button', { name: 'Settings menu', exact: true }).click()
  await page.getByRole('menuitem', { name: 'System settings', exact: true }).click()
  const system = page.getByRole('dialog', { name: 'System settings', exact: true })
  await expect(system.getByRole('tab', {name:'System audio'})).toBeVisible()
  await system.getByLabel('Global sample rate (Hz)').selectOption('44100')
  await system.getByLabel('DSP block size').selectOption('256')
  await system.getByRole('button', {name:'Save system audio'}).click()
  await expect.poll(async()=> (await (await page.request.get('/api/system/audio')).json()).sample_rate).toBe(44100)
  expect((await (await page.request.get('/api/system/audio')).json()).block_size).toBe(256)
  await expect(system.getByRole('button', {name:'Close system settings'})).toBeEnabled()
  await page.screenshot({path:'../docs/system-audio-settings.png',fullPage:true})
  await system.getByRole('button', {name:'Close system settings'}).click()
  await page.getByRole('button', { name: 'Settings menu', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Console', exact: true }).click()
  const consoleDialog = page.getByRole('dialog', {name:'Console',exact:true})
  await expect(consoleDialog.getByText('System sample rate set to 44100 Hz; clip caches ready')).toBeVisible()
  const popupPromise=page.context().waitForEvent('page')
  await consoleDialog.getByRole('button', {name:'Open in new tab'}).click()
  const popup=await popupPromise
  await expect(popup.getByRole('heading',{name:'Console',exact:true})).toBeVisible()
  await expect(popup.getByText('System sample rate set to 44100 Hz; clip caches ready')).toBeVisible()
  await popup.close()
  await consoleDialog.getByRole('button',{name:'Close console'}).click()
  await page.screenshot({ path: '../docs/workspace.png', fullPage: true })
  await page.getByRole('button', { name: 'Edit Modulo', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByText('CONNECTED', { exact: true })).toBeVisible()
  await expect(page.getByRole('dialog').locator('output')).toHaveText('—')
  await page.getByRole('spinbutton', { name: 'B', exact: true }).fill('6')
  await page.getByRole('spinbutton', { name: 'B', exact: true }).press('Tab')
  await expect(page.getByText('Saving…', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Close parameters' }).click()
  const projects = await (await page.request.get('/api/projects')).json()
  const monitorProjectId = projects.find((p: any) => p.name === 'Nocturne / signal studies').id
  const monitorProject = (await (await page.request.get(`/api/projects/${monitorProjectId}`)).json()).project
  monitorProject.graph.nodes.push(
    { id: 'test-browser-input', kind: 'browser_input', label: 'Browser capture', x: 0, y: 650, channels: 2, parameters: {} },
    { id: 'cue-tone', kind: 'oscillator', label: 'Cue tone', x: 300, y: 650, channels: 2, parameters: { frequency: 440, amplitude: 0.1 } },
    { id: 'cue-out', kind: 'monitor_output', label: 'Headphone cue', x: 650, y: 650, channels: 2, parameters: { gain: -12 } },
  )
  monitorProject.graph.edges.push({ id: 'cue-send', source: 'cue-tone', source_port: 'out', target: 'cue-out', target_port: 'in' })
  expect((await page.request.put(`/api/projects/${monitorProjectId}`, { headers: { 'X-Pr0former': '1' }, data: monitorProject })).ok()).toBeTruthy()
  await expect(page.getByRole('button', {name:'Edit Cue tone',exact:true})).toBeVisible()
  await page.locator('.vue-flow__controls-fitview').click()
  await page.getByRole('button', {name:'Edit Cue tone',exact:true}).click()
  await page.getByLabel('Waveform',{exact:true}).selectOption('3')
  await expect.poll(async()=> (await (await page.request.get(`/api/projects/${monitorProjectId}`)).json()).project.graph.nodes.find((n:any)=>n.id==='cue-tone').parameters.waveform).toBe(3)
  await page.getByLabel('Waveform',{exact:true}).selectOption('0')
  await expect.poll(async()=> (await (await page.request.get(`/api/projects/${monitorProjectId}`)).json()).project.graph.nodes.find((n:any)=>n.id==='cue-tone').parameters.waveform).toBe(0)
  await page.getByRole('button',{name:'Close parameters'}).click()
  await page.getByRole('button', { name: 'Activate show' }).click()
  await page.getByRole('button', { name: 'Play', exact: true }).click()
  await expect.poll(()=>latest?.block_size).toBe(256)
  const previewResponse=await page.request.get(`/api/projects/${monitorProjectId}/preview?edge=cue-send`)
  expect(previewResponse.ok()).toBeTruthy()
  const preview=await previewResponse.json()
  expect(preview.channels).toHaveLength(2)
  expect(preview.channels[0]).toHaveLength(256)
  expect(Math.max(...preview.channels[0].map(Math.abs))).toBeGreaterThan(0.09)
  const previewEdge=page.locator('.vue-flow__edge').filter({has:page.locator('#cue-send')}).locator('g[tabindex="0"]')
  await previewEdge.focus()
  await expect(page.getByRole('tooltip').getByRole('img',{name:'Channel 1 waveform'})).toBeVisible()
  await page.screenshot({path:'../docs/audio-waveform-preview.png',fullPage:true})
  await previewEdge.press('Escape')
  await expect(page.getByRole('tooltip')).toHaveCount(0)

  await page.getByRole('button', { name: 'Edit Modulo', exact: true }).click()
  await expect(page.getByRole('dialog').locator('output')).not.toHaveText('—')
  await page.screenshot({ path: '../docs/parameter-modal.png', fullPage: true })
  await page.getByRole('button', { name: 'Close parameters' }).click()
  await page.getByRole('button', { name: 'Monitor', exact: true }).click()
  await page.getByLabel('Monitor feed', { exact: true }).selectOption('cue-out')
  await page.getByRole('button', { name: 'Connect monitor', exact: true }).click()
  await expect(page.locator('.browser-monitor .mode-pill')).toHaveText('CONNECTED', { timeout: 20000 })
  const duplicateAudio = await page.request.post(`/api/projects/${monitorProjectId}/media`, {
    headers: { 'X-Pr0former': '1' }, data: { sdp: 'duplicate must not replace this connection' },
  })
  expect(duplicateAudio.status()).toBe(409)
  await expect(page.locator('.browser-monitor .mode-pill')).toHaveText('CONNECTED')
  await expect.poll(async () => page.evaluate(async () => {
    const peer = (window as any).__audioPeers.at(-1) as RTCPeerConnection
    let energy = 0
    ;(await peer.getStats()).forEach(report => { if (report.type === 'inbound-rtp' && report.kind === 'audio') energy = report.totalAudioEnergy || 0 })
    return energy
  })).toBeGreaterThan(0)
  await page.getByRole('button', { name: 'Performance mode', exact: true }).click()
  await page.getByLabel('Show all parts',{exact:true}).check()
  await expect(page.getByRole('main', { name: 'Performance stage' })).toBeVisible()
  await expect(page.getByLabel('Clef', { exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Stage part status')).toHaveText('Part idle')
  await page.getByRole('button', { name: 'Launch part', exact: true }).click()
  await expect(page.getByLabel('Stage part status')).toHaveText('Part playing')
  await page.getByRole('button', { name: 'Stop part', exact: true }).click()
  await expect(page.getByLabel('Stage part status')).toHaveText('Part idle')
  await page.getByRole('button', { name: 'Monitor controls', exact: true }).click()
  await expect(page.locator('.browser-monitor .mode-pill')).toHaveText('CONNECTED')
  expect(await page.evaluate(() => (window as any).__audioPeers.length)).toBe(1)
  await page.setViewportSize({ width: 768, height: 1024 })
  await expect(page.getByRole('button', { name: 'Exit performance mode', exact: true })).toBeInViewport()
  await page.getByRole('button', { name: 'Monitor controls', exact: true }).click()
  await page.screenshot({ path: '../docs/performance-stage.png' })
  await page.context().setOffline(true)
  await expect(page.getByText('Timing unavailable — score held', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Launch part', exact: true })).toBeDisabled()
  const heldPosition = await page.getByLabel('Stage position', { exact: true }).textContent()
  await page.waitForTimeout(600)
  await expect(page.getByLabel('Stage position', { exact: true })).toHaveText(heldPosition!)
  await page.context().setOffline(false)
  await expect(page.getByText('Transport playing', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Launch part', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Exit performance mode', exact: true }).click()
  await page.setViewportSize({ width: 1440, height: 960 })
  await page.getByRole('button', { name: 'Disconnect', exact: true }).click()
  await page.getByRole('button', { name: 'Score & parts' }).click()
  await expect(page.getByLabel('Part playback status')).toHaveText('Part idle')
  await page.getByRole('button', { name: 'Launch part', exact: true }).click()
  await expect(page.getByLabel('Part playback status')).toHaveText('Part playing')
  const start = latest.parts[0].start
  const projectId = latest.project_id
  const loaded = await (await page.request.get(`/api/projects/${projectId}`)).json()
  loaded.project.graph.nodes.find((n: any) => n.id === 'tone').label = 'Continuing synth'
  const replacement = await page.request.put(`/api/projects/${projectId}`, {
    headers: { 'X-Pr0former': '1' }, data: loaded.project,
  })
  expect(replacement.ok()).toBeTruthy()
  const revision = (await replacement.json()).revision
  await expect.poll(() => latest?.revision).toBe(revision)
  expect(latest.parts[0].playing).toBe(true)
  expect(latest.parts[0].start).toBe(start)
  await expect(page.getByLabel('Part playback status')).toHaveText('Part playing')
  await page.getByRole('button', { name: 'Stop part', exact: true }).click()
  await expect(page.getByLabel('Part playback status')).toHaveText('Part idle')
  await page.getByRole('button', { name: 'Deactivate show' }).click()
  await page.getByRole('button', { name: 'Score & parts' }).click()
  await expect(page.locator('.notation-surface svg')).toBeVisible()
  await page.getByRole('button', { name: 'Piano roll', exact: true }).click()
  await expect(page.locator('.midi-note')).toHaveCount(8)
  await page.locator('.score-settings summary').click()
  await page.getByLabel('Clef', { exact: true }).selectOption('alto')
  await expect(page.getByLabel('Clef', { exact: true })).toHaveValue('alto')
  await page.getByLabel('Key signature', { exact: true }).selectOption('Eb')
  await expect(page.getByLabel('Key signature', { exact: true })).toHaveValue('Eb')
  await page.getByLabel('Time signature', { exact: true }).selectOption('hide')
  await expect(page.getByLabel('Time signature', { exact: true })).toHaveValue('hide')
  await page.getByLabel('Beats per bar').fill('6')
  await page.getByLabel('Beats per bar').press('Tab')
  await expect(page.getByLabel('Beats per bar')).toBeEnabled()
  await expect(page.getByLabel('Beats per bar')).toHaveValue('6')
  await page.getByLabel('Beat unit', { exact: true }).selectOption('8')
  await expect(page.getByLabel('Beat unit', { exact: true })).toBeEnabled()
  await expect(page.getByLabel('Beat unit', { exact: true })).toHaveValue('8')
  await page.getByRole('button', { name: 'Notation', exact: true }).click()
  await expect(page.locator('.notation-surface svg')).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'MusicXML', exact: true }).click()
  const download = await downloadPromise
  const xml = await readFile((await download.path())!, 'utf8')
  expect(xml).toContain('<fifths>-3</fifths>')
  expect(xml).toContain('<sign>C</sign><line>3</line>')
  expect(xml).toContain('<time print-object="no"><beats>6</beats><beat-type>8</beat-type>')
  const importedPromise = page.waitForResponse(r => r.request().method() === 'PUT' && r.url().endsWith(`/api/projects/${projectId}`))
  await page.locator('input[accept=".xml,.musicxml"]').setInputFiles({ name: 'roundtrip.musicxml', mimeType: 'application/xml', buffer: Buffer.from(xml) })
  const imported = await importedPromise
  expect(imported.ok()).toBeTruthy()
  const restored = await imported.json()
  expect(restored.parts[0].key_signature).toBe('Eb')
  expect(restored.parts[0].clef).toBe('alto')
  expect(restored.parts[0].show_time_signature).toBe(false)
  expect(restored.beats_per_bar).toBe(6)
  expect(restored.beat_unit).toBe(8)
  expect(restored.parts[0].notes.map((n: any) => n.beat)).toEqual([0, 1, 2, 3, 4, 5, 6, 7])
  await expect(page.getByLabel('Clef', { exact: true })).toHaveValue('alto')
  await expect(page.getByLabel('Key signature', { exact: true })).toHaveValue('')
  await expect(page.getByLabel('Time signature', { exact: true })).toHaveValue('hide')
  restored.parts[0].notes = restored.parts[0].notes.slice(0, 3).map((n: any, i: number) => ({ ...n, notation: undefined, beat: [0, 0.5, 3][i], duration: 0.25 }))
  const spaced = await page.request.put(`/api/projects/${projectId}`, { headers: { 'X-Pr0former': '1' }, data: restored })
  expect(spaced.ok()).toBeTruthy()
  await expect(page.locator('[data-score-beat]')).toHaveCount(3)
  const positions = await page.locator('[data-score-beat]').evaluateAll(elements => elements.map(el => ({
    beat: Number((el as SVGElement).dataset.scoreBeat),
    x: el.querySelector('.vf-notehead > text')!.getBoundingClientRect().left,
  })).sort((a, b) => a.beat - b.beat))
  expect(positions[1]!.x - positions[0]!.x).toBeCloseTo(48, 0)
  expect(positions[2]!.x - positions[1]!.x).toBeCloseTo(226.5, 0)
  const cursorX = await page.locator('.score-playhead').evaluate(el => el.getBoundingClientRect().left)
  expect(cursorX).toBeCloseTo(positions[0]!.x, 0)
  await page.getByLabel('Follow playback').uncheck()
  await expect(page.getByLabel('Follow playback')).not.toBeChecked()
  await page.getByRole('button',{name:'Settings menu',exact:true}).click()
  await page.getByRole('menuitem',{name:'System settings',exact:true}).click()
  await page.getByRole('tab',{name:'MIDI',exact:true}).click()
  await system.getByLabel('MIDI channel', { exact: true }).selectOption('10')
  await expect(system.getByLabel('MIDI channel',{exact:true})).toBeEnabled()
  await page.getByRole('tab',{name:'OSC',exact:true}).click()
  await system.getByLabel('OSC address', { exact: true }).fill('/touchdesigner/note')
  await system.getByLabel('OSC address', { exact: true }).press('Tab')
  await expect.poll(async () => {
    const saved = (await (await page.request.get(`/api/projects/${projectId}`)).json()).project
    return [saved.parts[0].midi_channel, saved.parts[0].osc_address]
  }).toEqual([10, '/touchdesigner/note'])
  await expect(system.getByLabel('OSC address', { exact: true })).toBeEnabled()
  await page.getByRole('button',{name:'Close system settings',exact:true}).click()
  const rhythms = (await (await page.request.get(`/api/projects/${projectId}`)).json()).project
  rhythms.parts[0].notes = rhythms.parts[0].notes.map((n: any, i: number) => ({ ...n, beat: [0, 1, 3][i], duration: [0.75, 1.25, 0.8][i] }))
  const rhythmResponse = await page.request.put(`/api/projects/${projectId}`, { headers: { 'X-Pr0former': '1' }, data: rhythms })
  expect(rhythmResponse.ok()).toBeTruthy()
  const rhythmSaved = await rhythmResponse.json()
  expect(rhythmSaved.revision).toBeGreaterThan(rhythms.revision)
  await expect(page.locator('.revision')).toHaveText(/Revision \d+ · Unsaved changes/)
  await expect(page.locator('[data-score-beat]')).toHaveCount(4)
  await expect(page.locator('[data-score-beat="0"]')).toHaveAttribute('data-dots', '1')
  await expect(page.locator('[data-score-beat="0"]')).toHaveAttribute('data-duration', '8')
  await expect(page.locator('[data-score-beat="2"]')).toHaveAttribute('data-duration', '16')
  await expect(page.locator('.vf-stavetie')).toHaveCount(1)
  await expect(page.getByText('0.8 beats*', { exact: true })).toBeVisible()
  await expect(page.getByText('1 note duration(s) need custom rhythm notation.', { exact: false })).toBeVisible()
  await page.screenshot({ path: '../docs/notation-durations.png' })
  // Hold an older successful save response while a collaborator publishes a newer revision.
  let releaseSave!: () => void
  const delayedSave = new Promise<void>(resolve => { releaseSave = resolve })
  let savedBeforeRemote: any = null
  await page.route(`**/api/projects/${projectId}`, async route => {
    if (route.request().method() !== 'PUT') { await route.continue(); return }
    const response = await route.fetch()
    savedBeforeRemote = await response.json()
    await delayedSave
    await route.fulfill({ response })
  })
  await page.getByRole('button',{name:'Settings menu',exact:true}).click()
  await page.getByRole('menuitem',{name:'System settings',exact:true}).click()
  await page.getByRole('tab',{name:'MIDI',exact:true}).click()
  await system.getByLabel('MIDI channel', { exact: true }).selectOption('11')
  await expect.poll(() => savedBeforeRemote?.revision).toBeTruthy()
  const newer = { ...savedBeforeRemote, name: 'Latest ensemble revision' }
  const remoteResponse = await page.request.put(`/api/projects/${projectId}`, { headers: { 'X-Pr0former': '1' }, data: newer })
  expect(remoteResponse.ok()).toBeTruthy()
  const remoteSaved = await remoteResponse.json()
  await expect(page.getByRole('button', { name: 'Latest ensemble revision', exact: true })).toBeVisible()
  releaseSave()
  await expect(system.getByLabel('MIDI channel', { exact: true })).toBeEnabled()
  expect(remoteSaved.revision).toBeGreaterThan(savedBeforeRemote.revision)
  await expect(page.locator('.revision')).toHaveText(/Revision \d+ · Unsaved changes/)
  await expect(page.getByRole('button', { name: 'Latest ensemble revision', exact: true })).toBeVisible()
  await page.unroute(`**/api/projects/${projectId}`)
  await page.getByRole('button',{name:'Close system settings',exact:true}).click()
  await page.getByRole('button', { name: 'Performance mode', exact: true }).click()
  await page.getByLabel('Show all parts',{exact:true}).check()
  await page.context().setOffline(true)
  await expect(page.getByText('Connecting', { exact: true })).toBeAttached()
  const offlineProject = (await (await page.request.get(`/api/projects/${projectId}`)).json()).project
  offlineProject.name = 'Reconnected ensemble'
  offlineProject.parts[0].notes = [offlineProject.parts[0].notes[0]]
  const offlineUpdate = await page.request.put(`/api/projects/${projectId}`, { headers: { 'X-Pr0former': '1' }, data: offlineProject })
  expect(offlineUpdate.ok()).toBeTruthy()
  await expect(page.getByRole('heading', { name: 'Latest ensemble revision', exact: true })).toBeVisible()
  await page.context().setOffline(false)
  await expect(page.getByRole('main', { name: 'Performance stage' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Reconnected ensemble', exact: true })).toBeVisible()
  await expect(page.locator('[data-score-beat]')).toHaveCount(1)
  // Drive transport as another client; this browser must observe deactivation.
  const remoteTransport = async (action: string) => {
    const response = await page.request.post(`/api/projects/${projectId}/transport`, { headers: { 'X-Pr0former': '1' }, data: { action } })
    expect(response.ok()).toBeTruthy()
  }
  await remoteTransport('activate')
  await expect(page.getByRole('button', { name: 'Deactivate show', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Monitor controls', exact: true }).click()
  await page.getByRole('button', { name: 'Connect monitor', exact: true }).click()
  await expect(page.locator('.browser-monitor .mode-pill')).toHaveText('CONNECTED')
  await remoteTransport('deactivate')
  // Monitor cleanup now follows disabling the development graph, not show pause/deactivation.
  expect((await page.request.post(`/api/projects/${projectId}/engine`, { headers: { 'X-Pr0former': '1' }, data: { enabled:false } })).ok()).toBeTruthy()
  await expect(page.getByText('Waiting for show activation', { exact: true })).toBeVisible()
  await expect(page.locator('.browser-monitor .mode-pill')).toHaveText('DISCONNECTED')
  await expect(page.getByRole('button', { name: 'Connect monitor', exact: true })).toBeDisabled()
  await remoteTransport('activate')
  await expect(page.getByRole('button', { name: 'Deactivate show', exact: true })).toBeVisible()
  await page.context().setOffline(true)
  await remoteTransport('deactivate')
  // Monitor cleanup now follows disabling the development graph, not show pause/deactivation.
  expect((await page.request.post(`/api/projects/${projectId}/engine`, { headers: { 'X-Pr0former': '1' }, data: { enabled:false } })).ok()).toBeTruthy()
  await page.context().setOffline(false)
  await expect(page.getByText('Waiting for show activation', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Activate show', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Exit performance mode', exact: true }).click()
  await page.getByRole('button', { name: 'Settings menu', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Project settings', exact: true }).click()
  const settings = page.getByRole('dialog', { name: 'Project settings', exact: true })
  await expect(settings).toBeVisible()
  await remoteTransport('activate')
  await expect(settings.getByText('Deactivate the show to change project settings.', { exact: true })).toBeVisible()
  await expect(settings.getByRole('button', { name: 'Save project settings', exact: true })).toBeDisabled()
  await remoteTransport('deactivate')
  // Monitor cleanup now follows disabling the development graph, not show pause/deactivation.
  expect((await page.request.post(`/api/projects/${projectId}/engine`, { headers: { 'X-Pr0former': '1' }, data: { enabled:false } })).ok()).toBeTruthy()
  await expect(settings.getByLabel('Project name', { exact: true })).toBeEnabled()
  await settings.getByLabel('Project name', { exact: true }).fill('Freeform rehearsal')
  await settings.getByLabel('Performance mode', { exact: true }).selectOption('freeform')
  await settings.getByLabel('Initial tempo (quarter-note BPM)', { exact: true }).fill('97.5')
  await settings.getByRole('button', { name: 'Save project settings', exact: true }).click()
  await expect(settings).toHaveCount(0)
  const configured = (await (await page.request.get(`/api/projects/${projectId}`)).json()).project
  expect([configured.name, configured.mode, configured.bpm]).toEqual(['Freeform rehearsal', 'freeform', 97.5])
  await page.getByRole('button', { name: 'Choose project', exact: true }).click()
  await expect(page.locator('.project-popover')).toContainText('Freeform rehearsal')
  await page.getByRole('button', { name: 'Choose project', exact: true }).click()
  await page.getByRole('button', { name: 'Settings menu', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Project settings', exact: true }).click()
  await settings.getByLabel('Project name', { exact: true }).fill('Uncommitted local title')
  configured.name = 'Concurrent rehearsal title'
  expect((await page.request.put(`/api/projects/${projectId}`, { headers: { 'X-Pr0former': '1' }, data: configured })).ok()).toBeTruthy()
  await expect(settings.getByText('The project changed after these settings opened.', { exact: false })).toBeVisible()
  await expect(settings.getByRole('button', { name: 'Save project settings', exact: true })).toBeDisabled()
  await page.keyboard.press('Escape')
  await expect(settings).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Concurrent rehearsal title', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Monitor', exact: true }).click()
  await remoteTransport('activate')
  await expect(page.getByRole('button', { name: 'Connect monitor', exact: true })).toBeEnabled()
  await page.evaluate(() => {
    const context = new AudioContext()
    const stream = context.createMediaStreamDestination().stream
    ;(window as any).__pendingCapture = { context, stream }
    navigator.mediaDevices.getUserMedia = () => new Promise(resolve => { (window as any).__resolveCapture = () => resolve(stream) })
  })
  await page.getByLabel('Send microphone to the graph', { exact: true }).check()
  await page.getByLabel('Browser input node', { exact: true }).selectOption('test-browser-input')
  await page.getByRole('button', { name: 'Connect monitor', exact: true }).click()
  await expect.poll(() => page.evaluate(() => typeof (window as any).__resolveCapture)).toBe('function')
  await remoteTransport('deactivate')
  // Monitor cleanup now follows disabling the development graph, not show pause/deactivation.
  expect((await page.request.post(`/api/projects/${projectId}/engine`, { headers: { 'X-Pr0former': '1' }, data: { enabled:false } })).ok()).toBeTruthy()
  await expect(page.locator('.browser-monitor .mode-pill')).toHaveText('DISCONNECTED')
  await remoteTransport('activate')
  await page.getByLabel('Send microphone to the graph', { exact: true }).uncheck()
  await page.getByRole('button', { name: 'Connect monitor', exact: true }).click()
  await expect(page.locator('.browser-monitor .mode-pill')).toHaveText('CONNECTED')
  await page.evaluate(() => (window as any).__resolveCapture())
  await expect.poll(() => page.evaluate(() => (window as any).__pendingCapture.stream.getTracks()[0].readyState)).toBe('ended')
  await expect(page.locator('.browser-monitor .mode-pill')).toHaveText('CONNECTED')
  await page.evaluate(() => (window as any).__pendingCapture.context.close())
  await page.getByRole('button', { name: 'Disconnect', exact: true }).click()
  await expect(page.locator('.browser-monitor .mode-pill')).toHaveText('DISCONNECTED')
  let releaseOffer!: () => void
  const pendingOffer = new Promise<void>(resolve => { releaseOffer = resolve })
  let offered = false
  await page.route(`**/api/projects/${projectId}/media`, async route => {
    if (route.request().method() !== 'POST') { await route.continue(); return }
    const response = await route.fetch()
    offered = true
    await pendingOffer
    await route.fulfill({ response })
  })
  await page.getByRole('button', { name: 'Connect monitor', exact: true }).click()
  await expect.poll(() => offered).toBe(true)
  await page.getByRole('button', { name: 'Disconnect', exact: true }).click()
  await expect(page.locator('.browser-monitor .mode-pill')).toHaveText('DISCONNECTING')
  await expect(page.getByRole('button', { name: 'Disconnect', exact: true })).toBeDisabled()
  releaseOffer()
  await expect(page.locator('.browser-monitor .mode-pill')).toHaveText('DISCONNECTED')
  await page.unroute(`**/api/projects/${projectId}/media`)
  await page.getByRole('button', { name: 'Connect monitor', exact: true }).click()
  await expect(page.locator('.browser-monitor .mode-pill')).toHaveText('CONNECTED')
  await remoteTransport('deactivate')
  // Monitor cleanup now follows disabling the development graph, not show pause/deactivation.
  expect((await page.request.post(`/api/projects/${projectId}/engine`, { headers: { 'X-Pr0former': '1' }, data: { enabled:false } })).ok()).toBeTruthy()
  await expect(page.locator('.browser-monitor .mode-pill')).toHaveText('DISCONNECTED')
  await page.getByRole('button', { name: 'Score & parts', exact: true }).click()
  if(!await page.locator('.score-settings').evaluate(el=>el.hasAttribute('open')))await page.locator('.score-settings summary').click()
  await page.getByLabel('Part name', { exact: true }).fill('Viola gestures')
  await page.getByLabel('Part name', { exact: true }).press('Tab')
  await expect(page.getByLabel('Part name', { exact: true })).toBeEnabled()
  await page.getByLabel('Loop length (quarter beats)', { exact: true }).fill('0.5')
  await page.getByLabel('Loop length (quarter beats)', { exact: true }).press('Tab')
  await expect(page.getByText('1 note(s) extend beyond the loop.', { exact: false })).toBeVisible()
  await expect(page.getByLabel('Loop length (quarter beats)', { exact: true })).toBeEnabled()
  await page.getByLabel('Loop length (quarter beats)', { exact: true }).fill('2')
  await page.getByLabel('Loop length (quarter beats)', { exact: true }).press('Tab')
  await expect(page.getByLabel('Default display', { exact: true })).toBeEnabled()
  await page.getByLabel('Default display', { exact: true }).selectOption('grid')
  await expect(page.locator('.piano-roll')).toBeVisible()
  await expect(page.getByLabel('Default display', { exact: true })).toBeEnabled()
  const partSetup = (await (await page.request.get(`/api/projects/${projectId}`)).json()).project.parts[0]
  expect([partSetup.name, partSetup.loop_beats, partSetup.view, partSetup.notes[0].duration]).toEqual(['Viola gestures', 2, 'grid', 0.75])
  await page.getByRole('button', { name: 'Add part', exact: true }).click()
  await page.getByRole('button', { name: 'Part 2', exact: true }).click()
  await expect(page.locator('.notation-surface').first()).toBeVisible()
  await page.getByRole('button', { name: 'Viola gestures', exact: true }).click()
  await expect(page.locator(`[data-score-part="${partSetup.id}"] .piano-roll`)).toBeVisible()
  await page.getByRole('button', { name: 'Performance mode', exact: true }).click()
  await page.getByLabel('Show all parts',{exact:true}).check()
  await expect(page.locator('.piano-roll')).toBeVisible()
  await expect(page.getByLabel('Part name', { exact: true })).toHaveCount(0)
  expect((await page.request.put(`/api/projects/${projectId}/system/audio`, {headers:{'X-Pr0former':'1'},data:{sample_rate:48000,interfaces:[]}})).ok()).toBeTruthy()
  expect(errors).toEqual([])
})
