<script setup lang="ts">
import {computed,nextTick,onBeforeUnmount,onMounted,ref} from 'vue'
import {FolderOpen,AudioLines,List,LayoutGrid,Plus,X,Trash2} from '@lucide/vue'
import {api} from '../api'
import {matchesMetadata,matchesProject} from '../projectSearch'
import type {Summary} from '../types'
import type {SampleEntry} from '../samples'
import SampleEditor from './SampleEditor.vue'
const emit=defineEmits<{close:[];open:[id:string];create:[];samples:[]}>()
const dialog=ref<HTMLDialogElement>(),tab=ref<'projects'|'samples'>('projects'),view=ref<'list'|'icons'>('list'),search=ref(''),projects=ref<Summary[]>([]),samples=ref<SampleEntry[]>([]),error=ref(''),busy=ref(false),editing=ref<SampleEntry>(),deleting=ref<SampleEntry>(),impact=ref<any>(),confirmation=ref(''),acknowledge=ref(false),sort=ref<keyof Summary>('name')
const visibleProjects=computed(()=>projects.value.filter(p=>matchesProject(p,search.value)).sort((a,b)=>String(a[sort.value]??'').localeCompare(String(b[sort.value]??''),undefined,{numeric:true,sensitivity:'base'})))
const visibleSamples=computed(()=>samples.value.filter(s=>matchesMetadata(s,search.value)))
const details=(p:Summary)=>`${p.owner||''} · ${p.mode} · ${p.bpm} BPM · ${p.beats_per_bar}/${p.beat_unit} · ${p.parts} parts · ${p.nodes} nodes · ${p.role} · revision ${p.revision}`
async function refresh(){busy.value=true;try{[projects.value,samples.value]=await Promise.all([api<Summary[]>('/projects'),api<SampleEntry[]>('/samples')])}catch(e){error.value=String(e)}finally{busy.value=false}}
let audio:HTMLAudioElement|undefined,timer:ReturnType<typeof setTimeout>|undefined
function stop(){audio?.pause();audio=undefined;clearTimeout(timer)}
async function preview(s:SampleEntry){stop();try{audio=new Audio(`/api/samples/${s.id}/audio`);await audio.play();timer=setTimeout(stop,3000)}catch(e){error.value=String(e)}}
async function review(s:SampleEntry){stop();error.value='';try{impact.value=await api(`/samples/${s.id}/impact`);deleting.value=s;confirmation.value='';acknowledge.value=false;await nextTick();const warning=dialog.value?.querySelector<HTMLElement>('.sample-delete-warning');warning?.scrollIntoView({block:'nearest'});warning?.focus()}catch(e){error.value=String(e)}}
async function remove(){if(!deleting.value)return;busy.value=true;try{const result=await api<any>(`/samples/${deleting.value.id}`,'DELETE',{confirm:confirmation.value,acknowledge:acknowledge.value,revision:deleting.value.revision,usage_token:impact.value.usage_token});deleting.value=undefined;emit('samples');await refresh();if(result.cleanup_errors)error.value='Sample deleted from the catalog, but some files could not be removed from disk. Ask the server administrator to check filesystem permissions.'}catch(e){error.value=String(e)}finally{busy.value=false}}
onMounted(()=>{dialog.value?.showModal();void refresh()});onBeforeUnmount(stop)
</script>
<template>
<dialog ref="dialog" class="parameter-modal project-browser" aria-labelledby="browser-title" @cancel.prevent="!busy&&emit('close')"><header class="modal-header"><div><div class="eyebrow">YOUR WORKSPACE</div><h2 id="browser-title">Project browser</h2></div><button class="icon-button" aria-label="Close project browser" :disabled="busy" @click="emit('close')"><X :size="20"/></button></header>
<div class="browser-content"><nav class="browser-tabs" role="tablist" aria-label="Browser sections"><button role="tab" id="browse-projects" aria-controls="browse-results" :aria-selected="tab==='projects'" @click="tab='projects';search=''">Projects</button><button role="tab" id="browse-samples" aria-controls="browse-results" :aria-selected="tab==='samples'" @click="tab='samples';search=''">Sample organizer</button></nav>
<div class="browser-toolbar"><input v-model="search" autofocus :aria-label="tab==='projects'?'Search project metadata':'Search sample metadata'" placeholder="Search name, mode, tempo, author, metadata…"><button class="icon-button" aria-label="List view" :aria-pressed="view==='list'" @click="view='list'"><List :size="18"/></button><button class="icon-button" aria-label="Icon view" :aria-pressed="view==='icons'" @click="view='icons'"><LayoutGrid :size="18"/></button><button v-if="tab==='projects'" class="button" @click="emit('create')"><Plus :size="16"/> New project</button></div>
<p v-if="error" role="alert" class="field-error">{{error}}</p><p v-if="busy" role="status">Loading…</p>
<div id="browse-results" role="tabpanel" :aria-labelledby="tab==='projects'?'browse-projects':'browse-samples'" class="browser-results">
<template v-if="tab==='projects'"><div v-if="view==='list'" class="table-wrap"><table><thead><tr><th v-for="column in (['name','owner','mode','bpm','role','revision'] as const)" :key="column"><button @click="sort=column">{{column==='bpm'?'Tempo (BPM)':column}}</button></th><th>Meter</th></tr></thead><tbody><tr v-for="p in visibleProjects" :key="p.id" :title="details(p)"><td><button class="text-button" @click="emit('open',p.id)"><FolderOpen :size="15"/> {{p.name}}</button></td><td>{{p.owner}}</td><td>{{p.mode}}</td><td>{{p.bpm}}</td><td>{{p.role}}</td><td>{{p.revision}}</td><td>{{p.beats_per_bar}}/{{p.beat_unit}}</td></tr></tbody></table></div><div v-else class="browser-grid"><button v-for="p in visibleProjects" :key="p.id" class="browser-card" :title="details(p)" @click="emit('open',p.id)"><FolderOpen :size="34"/><strong>{{p.name}}</strong><small>{{p.mode}} · {{p.bpm}} BPM</small><span class="card-details">{{details(p)}}</span></button></div><p v-if="!busy&&!visibleProjects.length">No matching accessible projects.</p></template>
<template v-else><p class="feature-note">Your samples, global samples, and samples shared through your projects. Deletion removes catalog audio and linked project copies.</p><div :class="view==='icons'?'browser-grid':'sample-organizer-list'"><article v-for="s in visibleSamples" :key="s.id" class="sample-organizer-item" :title="`${s.author} · ${s.tags} · ${s.description} · ${s.channels} channels · ${s.sample_rate} Hz`"><AudioLines :size="25"/><div><button class="text-button" @click="stop();editing=s">{{s.name}}</button><small>{{s.author}} · {{s.global?'Global':'Private'}} · {{s.duration.toFixed(1)}} s · {{s.channels}} ch</small></div><button class="button small" :aria-label="`Preview ${s.name}`" @click="preview(s)">Preview</button><button v-if="s.can_delete" class="icon-button" :aria-label="`Delete sample ${s.name}`" @click="review(s)"><Trash2 :size="16"/></button></article></div><p v-if="!busy&&!visibleSamples.length">No matching accessible samples.</p></template>
<div v-if="deleting" class="sample-delete-warning" tabindex="-1" role="alertdialog" aria-label="Confirm sample deletion"><h3>Permanent deletion can break projects</h3><p>Deleting <strong>{{deleting.name}}</strong> removes its original audio and linked copies from {{impact.project_count}} projects. Samplers may become silent and projects may fail to load. Saved revisions do not restore deleted audio. Keep an external backup first.</p><ul><li v-for="p in impact.projects" :key="p.id">{{p.name}}</li></ul><p v-if="impact.projects.length<impact.project_count">Additional affected projects are outside your access.</p><label class="check-label"><input v-model="acknowledge" type="checkbox">I understand this can permanently break projects.</label><label>Type sample name to delete<input v-model="confirmation" autocomplete="off"></label><div class="browser-toolbar"><button class="button" :disabled="busy" @click="deleting=undefined">Cancel deletion</button><button class="button danger" :disabled="busy||!acknowledge||confirmation!==deleting.name" @click="remove">Permanently delete sample</button></div></div>
</div></div><SampleEditor v-if="editing" :key="editing.id" :sample="editing" @close="editing=undefined" @saved="refresh();emit('samples')"/></dialog>
</template>
<style scoped>
.project-browser{width:min(1100px,96vw);height:min(820px,92dvh)}.browser-content{display:flex;flex-direction:column;min-height:0;padding:0 24px 20px;flex:1;overflow:hidden}.browser-tabs,.browser-toolbar{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin-bottom:16px}.browser-tabs button{padding:10px 15px;border-bottom:2px solid transparent}.browser-tabs [aria-selected=true]{color:var(--cyan);border-color:var(--cyan)}.browser-toolbar input{flex:1;min-width:170px}.browser-results{overflow:auto;min-height:0}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:12px}th,td{text-align:left;padding:12px 10px;border-bottom:1px solid var(--line)}th{text-transform:capitalize;color:var(--muted)}td .text-button{display:flex;gap:8px;text-align:left;align-items:center}.browser-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(195px,1fr));gap:14px}.browser-card{position:relative;display:flex;flex-direction:column;align-items:flex-start;gap:14px;padding:22px;border:1px solid var(--line);border-radius:8px;background:var(--panel);text-align:left;min-height:160px}.browser-card svg{color:var(--cyan)}.browser-card strong{overflow-wrap:anywhere}.card-details{display:none;font-size:11px;color:var(--muted)}.browser-card:hover .card-details,.browser-card:focus .card-details{display:block}.browser-card small,small{color:var(--muted)}.sample-organizer-item{display:flex;gap:12px;align-items:center;border-bottom:1px solid var(--line);padding:14px 0}.sample-organizer-item>div{flex:1;min-width:0;overflow-wrap:anywhere}.sample-organizer-item small{display:block;font-size:10px;margin-top:6px}.browser-grid .sample-organizer-item{flex-wrap:wrap;padding:16px;border:1px solid var(--line);border-radius:8px}.sample-delete-warning{padding:20px;margin-top:20px;background:#342320;border:2px solid #d98c78;border-radius:8px}.sample-delete-warning p{line-height:1.6}.sample-delete-warning label{display:flex;gap:10px;margin:15px 0}.sample-delete-warning label:not(.check-label){flex-direction:column}@media(max-width:600px){.browser-content{padding:0 12px 12px}.browser-grid{grid-template-columns:1fr}.sample-organizer-item{flex-wrap:wrap}.project-browser{height:100dvh;width:100%}}
</style>
