<script setup lang="ts">
import {computed,nextTick,onBeforeUnmount,onMounted,ref} from 'vue'
import {FolderOpen,AudioLines,List,LayoutGrid,Plus,X,Trash2,Download,Upload} from '@lucide/vue'
import {api} from '../api'
import {matchesMetadata,matchesProject} from '../projectSearch'
import {readProjectArchive} from '../projectTransfer'
import type {Project,Summary} from '../types'
import {hasTag,parseTags,tagCloud,toggleTag,type SampleEntry} from '../samples'
import SampleEditor from './SampleEditor.vue'
import TagChips from './TagChips.vue'
const emit=defineEmits<{close:[];open:[id:string];create:[];samples:[]}>()
const dialog=ref<HTMLDialogElement>(),importInput=ref<HTMLInputElement>(),tab=ref<'projects'|'samples'>('projects'),view=ref<'list'|'icons'>('list'),search=ref(''),projects=ref<Summary[]>([]),samples=ref<SampleEntry[]>([]),error=ref(''),busy=ref(false),editing=ref<SampleEntry>(),deleting=ref<SampleEntry>(),impact=ref<any>(),confirmation=ref(''),acknowledge=ref(false),sort=ref<keyof Summary>('name')
const incoming=ref<Project>(),conflict=ref<Summary>(),rename=ref(''),focusedProject=ref('')
const incomingBundle=ref<File>()
const activeTags=ref<string[]>([])
const cloud=computed(()=>tagCloud(samples.value)),counts=computed(()=>Object.fromEntries(cloud.value.map(c=>[c.tag.toLowerCase(),c.count])))
const visibleProjects=computed(()=>projects.value.filter(p=>matchesProject(p,search.value)).sort((a,b)=>String(a[sort.value]??'').localeCompare(String(b[sort.value]??''),undefined,{numeric:true,sensitivity:'base'})))
const visibleSamples=computed(()=>samples.value.filter(s=>matchesMetadata(s,search.value)&&activeTags.value.every(tag=>hasTag(s,tag))))
const details=(p:Summary)=>`${p.owner||''} · ${p.mode} · ${p.bpm} BPM · ${p.beats_per_bar}/${p.beat_unit} · ${p.parts} parts · ${p.nodes} nodes · ${p.role} · revision ${p.revision}`
async function refresh(){busy.value=true;try{[projects.value,samples.value]=await Promise.all([api<Summary[]>('/projects'),api<SampleEntry[]>('/samples')])}catch(e){error.value=String(e)}finally{busy.value=false}}
async function exportProject(id:string){busy.value=true;error.value='';try{const response=await fetch(`/api/projects/${id}/export`,{credentials:'same-origin'});if(!response.ok)throw new Error((await response.json()).error||'Export failed');const url=URL.createObjectURL(await response.blob()),link=document.createElement('a');link.href=url;link.download=`${(projects.value.find(p=>p.id===id)?.name||'Project').replace(/[\\/:*?"<>|]/g,'_')}.pr0`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){error.value=String(e)}finally{busy.value=false}}
async function bundleRequest(path:string,file:File,fields:Record<string,string>={}){const form=new FormData();form.append('file',file);for(const [key,value] of Object.entries(fields))form.append(key,value);const response=await fetch(`/api/projects/bundle/${path}`,{method:'POST',credentials:'same-origin',headers:{'X-Pr0former':'1'},body:form});const result=await response.json();if(!response.ok)throw new Error(result.error||'Bundle import failed');return result as Project}
function nameConflict(name:string,ignore?:string){return projects.value.find(p=>p.id!==ignore&&p.name.trim().localeCompare(name.trim(),undefined,{sensitivity:'accent'})===0)}
async function chooseImport(event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0];input.value='';if(!file||busy.value)return;error.value='';busy.value=true;cancelImport();try{if(file.size>256*1024*1024)throw new Error('Project bundles must be at most 256 MiB.');const isZip=new Uint8Array(await file.slice(0,2).arrayBuffer());incomingBundle.value=isZip[0]===80&&isZip[1]===75?file:undefined;const parsed=incomingBundle.value?await bundleRequest('inspect',file):readProjectArchive(JSON.parse(await file.text()));incoming.value=parsed;const existing=nameConflict(parsed.name);if(existing){conflict.value=existing;rename.value=`${parsed.name} (imported)`}else await importNew(parsed,parsed.name)}catch(e){error.value=e instanceof Error?e.message:String(e)}finally{busy.value=false}}
async function importNew(source:Project,name:string){const trimmed=name.trim();if(!trimmed){error.value='Project name must not be empty.';return}if(nameConflict(trimmed)){error.value='That name is already in use. Choose another name.';return}busy.value=true;try{const saved=incomingBundle.value?await bundleRequest('import',incomingBundle.value,{name:trimmed}):await api<Project>('/projects/import','POST',{...source,name:trimmed});cancelImport();await refresh();emit('open',saved.id)}catch(e){error.value=e instanceof Error?e.message:String(e)}finally{busy.value=false}}
async function overwriteImport(){if(!incoming.value||!conflict.value)return;busy.value=true;try{const target=conflict.value;const imported={...incoming.value,id:target.id,revision:target.revision,name:target.name};const saved=incomingBundle.value?await bundleRequest('import',incomingBundle.value,{name:target.name,target:target.id,revision:String(target.revision)}):await api<Project>(`/projects/${target.id}`,'PUT',imported);cancelImport();await refresh();emit('open',saved.id)}catch(e){error.value=e instanceof Error?e.message:String(e)}finally{busy.value=false}}
function cancelImport(){incoming.value=undefined;incomingBundle.value=undefined;conflict.value=undefined;rename.value=''}
let audio:HTMLAudioElement|undefined,timer:ReturnType<typeof setTimeout>|undefined
function stop(){audio?.pause();audio=undefined;clearTimeout(timer)}
async function preview(s:SampleEntry){stop();try{audio=new Audio(`/api/samples/${s.id}/audio`);await audio.play();timer=setTimeout(stop,3000)}catch(e){error.value=String(e)}}
async function review(s:SampleEntry){stop();error.value='';try{impact.value=await api(`/samples/${s.id}/impact`);deleting.value=s;confirmation.value='';acknowledge.value=false;await nextTick();const warning=dialog.value?.querySelector<HTMLElement>('.sample-delete-warning');warning?.scrollIntoView({block:'nearest'});warning?.focus()}catch(e){error.value=String(e)}}
async function remove(){if(!deleting.value)return;busy.value=true;try{const result=await api<any>(`/samples/${deleting.value.id}`,'DELETE',{confirm:confirmation.value,acknowledge:acknowledge.value,revision:deleting.value.revision,usage_token:impact.value.usage_token});deleting.value=undefined;emit('samples');await refresh();if(result.cleanup_errors)error.value='Sample deleted from the catalog, but some files could not be removed from disk. Ask the server administrator to check filesystem permissions.'}catch(e){error.value=String(e)}finally{busy.value=false}}
onMounted(()=>{dialog.value?.showModal();void refresh()});onBeforeUnmount(stop)
</script>
<template>
<dialog ref="dialog" class="parameter-modal project-browser" aria-labelledby="browser-title" @cancel.prevent="!busy&&emit('close')"><header class="modal-header"><div><div class="eyebrow">YOUR WORKSPACE</div><h2 id="browser-title">Project browser</h2></div><button class="icon-button" aria-label="Close project browser" :disabled="busy" @click="emit('close')"><X :size="20"/></button></header>
<div class="browser-content"><nav class="browser-tabs" role="tablist" aria-label="Browser sections"><button role="tab" id="browse-projects" aria-controls="browse-results" :aria-selected="tab==='projects'" @click="tab='projects';search=''">Projects</button><button role="tab" id="browse-samples" aria-controls="browse-results" :aria-selected="tab==='samples'" @click="tab='samples';search=''">Sample organizer</button></nav>
<div class="browser-toolbar"><input v-model="search" autofocus :aria-label="tab==='projects'?'Search project metadata':'Search sample metadata'" placeholder="Search name, mode, tempo, author, metadata…"><button class="icon-button" aria-label="List view" :aria-pressed="view==='list'" @click="view='list'"><List :size="18"/></button><button class="icon-button" aria-label="Icon view" :aria-pressed="view==='icons'" @click="view='icons'"><LayoutGrid :size="18"/></button><template v-if="tab==='projects'"><button class="button" @click="emit('create')"><Plus :size="16"/> New project</button><label class="button"><Upload :size="16"/> Import project<input ref="importInput" type="file" accept="application/zip,.pr0,.zip,application/json,.json" :disabled="busy" hidden @change="chooseImport"></label></template></div>
<p v-if="error" role="alert" class="field-error">{{error}}</p><p v-if="busy" role="status">Loading…</p>
<div id="browse-results" role="tabpanel" :aria-labelledby="tab==='projects'?'browse-projects':'browse-samples'" class="browser-results">
<template v-if="tab==='projects'"><div v-if="view==='list'" class="table-wrap"><table><thead><tr><th v-for="column in (['name','owner','mode','bpm','role','revision'] as const)" :key="column"><button @click="sort=column">{{column==='bpm'?'Tempo (BPM)':column}}</button></th><th>Meter</th><th>Export</th></tr></thead><tbody><tr v-for="p in visibleProjects" :key="p.id" :title="details(p)"><td><button class="text-button" @click="emit('open',p.id)"><FolderOpen :size="15"/> {{p.name}}</button></td><td>{{p.owner}}</td><td>{{p.mode}}</td><td>{{p.bpm}}</td><td>{{p.role}}</td><td>{{p.revision}}</td><td>{{p.beats_per_bar}}/{{p.beat_unit}}</td><td><button class="icon-button" :aria-label="`Export ${p.name}`" @click="exportProject(p.id)"><Download :size="16"/></button></td></tr></tbody></table></div><div v-else class="browser-grid"><article v-for="p in visibleProjects" :key="p.id" class="browser-card" :class="{focused:focusedProject===p.id}" :title="details(p)" tabindex="0" @focus="focusedProject=p.id" @blur="focusedProject=''" @click="emit('open',p.id)" @keydown.enter.prevent="emit('open',p.id)"><div class="browser-card-open"><FolderOpen :size="34"/><strong>{{p.name}}</strong><small>{{p.mode}} · {{p.bpm}} BPM</small><span class="card-details">{{details(p)}}</span></div><button class="icon-button card-export" :aria-label="`Export ${p.name}`" @click.stop="exportProject(p.id)"><Download :size="16"/></button></article></div><p v-if="!busy&&!visibleProjects.length">No matching accessible projects.</p></template>
<template v-else><div class="help-section-title">Sample access<HelpNote label="Sample access">Your samples, global samples, and samples shared through your projects. Deletion removes catalog audio and linked project copies. Click tags to filter; open a sample to edit its tags.</HelpNote></div><TagChips v-if="cloud.length" class="tag-filter" :tags="cloud.map(c=>c.tag)" :active="activeTags" :counts="counts" interactive @toggle="tag=>activeTags=toggleTag(activeTags,tag)" /><div :class="view==='icons'?'browser-grid':'sample-organizer-list'"><article v-for="s in visibleSamples" :key="s.id" class="sample-organizer-item" :title="`${s.author} · ${s.tags} · ${s.description} · ${s.channels} channels · ${s.sample_rate} Hz`"><AudioLines :size="25"/><div><button class="text-button" @click="stop();editing=s">{{s.name}}</button><small>{{s.author}} · {{s.global?'Global':'Private'}} · {{s.duration.toFixed(1)}} s · {{s.channels}} ch{{s.category?` · ${s.category}`:''}}</small><TagChips :tags="parseTags(s.tags)" :active="activeTags" interactive @toggle="tag=>activeTags=toggleTag(activeTags,tag)" /></div><button class="button small" :aria-label="`Preview ${s.name}`" @click="preview(s)">Preview</button><button v-if="s.can_delete" class="icon-button" :aria-label="`Delete sample ${s.name}`" @click="review(s)"><Trash2 :size="16"/></button></article></div><p v-if="!busy&&!visibleSamples.length">No matching accessible samples.</p></template>
<div v-if="deleting" class="sample-delete-warning" tabindex="-1" role="alertdialog" aria-label="Confirm sample deletion"><h3>Permanent deletion can break projects</h3><p>Deleting <strong>{{deleting.name}}</strong> removes its original audio and linked copies from {{impact.project_count}} projects. Samplers may become silent and projects may fail to load. Saved revisions do not restore deleted audio. Keep an external backup first.</p><ul><li v-for="p in impact.projects" :key="p.id">{{p.name}}</li></ul><p v-if="impact.projects.length<impact.project_count">Additional affected projects are outside your access.</p><label class="check-label"><input v-model="acknowledge" type="checkbox">I understand this can permanently break projects.</label><label>Type sample name to delete<input v-model="confirmation" autocomplete="off"></label><div class="browser-toolbar"><button class="button" :disabled="busy" @click="deleting=undefined">Cancel deletion</button><button class="button danger" :disabled="busy||!acknowledge||confirmation!==deleting.name" @click="remove">Permanently delete sample</button></div></div>
<div v-if="conflict&&incoming" class="import-conflict" role="alertdialog" aria-label="Project name conflict"><h3>Project name already in use</h3><p><strong>{{incoming.name}}</strong> already belongs to an accessible project. Import it under a new name, replace the existing project, or cancel.</p><label>Imported project name<input v-model="rename" autocomplete="off"></label><p class="feature-note">Import does not transfer people, local devices, local MIDI bindings, or sample audio.</p><div class="browser-toolbar"><button class="button" :disabled="busy" @click="cancelImport">Cancel</button><button class="button primary" :disabled="busy||!rename.trim()" @click="importNew(incoming,rename)">Rename &amp; import</button><button class="button danger" :disabled="busy||!['owner','editor'].includes(conflict.role)" :title="!['owner','editor'].includes(conflict.role)?'Editor access is required to overwrite this project':undefined" @click="overwriteImport">Overwrite existing</button></div></div>
</div></div><SampleEditor v-if="editing" :key="editing.id" :sample="editing" @close="editing=undefined" @saved="refresh();emit('samples')"/></dialog>
</template>
<style scoped>
.project-browser{width:min(1100px,96vw);height:min(820px,92dvh)}.browser-content{display:flex;flex-direction:column;min-height:0;padding:0 24px 20px;flex:1;overflow:hidden}.browser-tabs,.browser-toolbar{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin-bottom:16px}.browser-tabs button{padding:10px 15px;border-bottom:2px solid transparent}.browser-tabs [aria-selected=true]{color:var(--cyan);border-color:var(--cyan)}.browser-toolbar input{flex:1;min-width:170px}.browser-results{overflow:auto;min-height:0}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:12px}th,td{text-align:left;padding:12px 10px;border-bottom:1px solid var(--line)}th{text-transform:capitalize;color:var(--muted)}td .text-button{display:flex;gap:8px;text-align:left;align-items:center}.browser-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(195px,1fr));gap:14px}.browser-card{position:relative;display:flex;flex-direction:column;align-items:stretch;border:1px solid var(--line);border-radius:8px;background:var(--panel);text-align:left;min-height:160px;cursor:pointer}.browser-card-open{display:flex;flex:1;flex-direction:column;align-items:flex-start;gap:14px;padding:22px;text-align:left}.browser-card svg{color:var(--cyan)}.browser-card strong{overflow-wrap:anywhere}.card-details{display:none;font-size:11px;color:var(--muted)}.browser-card:hover .card-details,.browser-card.focused .card-details,.browser-card:focus .card-details,.browser-card:focus-within .card-details{display:block}.card-export{position:absolute;right:10px;bottom:10px}.browser-card small,small{color:var(--muted)}.sample-organizer-item{display:flex;gap:12px;align-items:center;border-bottom:1px solid var(--line);padding:14px 0}.sample-organizer-item>div{flex:1;min-width:0;overflow-wrap:anywhere}.sample-organizer-item small{display:block;font-size:10px;margin-top:6px}.browser-grid .sample-organizer-item{flex-wrap:wrap;padding:16px;border:1px solid var(--line);border-radius:8px}.sample-delete-warning,.import-conflict{padding:20px;margin-top:20px;background:#342320;border:2px solid #d98c78;border-radius:8px}.sample-delete-warning p,.import-conflict p{line-height:1.6}.sample-delete-warning label,.import-conflict label{display:flex;gap:10px;margin:15px 0}.sample-delete-warning label:not(.check-label),.import-conflict label{flex-direction:column}@media(max-width:600px){.browser-content{padding:0 12px 12px}.browser-grid{grid-template-columns:1fr}.sample-organizer-item{flex-wrap:wrap}.project-browser{height:100dvh;width:100%}}
</style>
