<script setup lang="ts">
defineProps<{ topic: 'quick-start' | 'architecture' | 'init' | 'build' }>()
</script>
<template>
  <article class="help-article setup-guide">
    <div class="eyebrow">GETTING STARTED</div>
    <template v-if="topic === 'quick-start'">
      <h1>Quick start</h1>
      <p class="lead">Choose where the sound engine will run, connect a client, then build and listen to your first patch.</p>
      <section><h2>1. Choose your starting point</h2>
        <ul><li><b>Desktop app:</b> open pr0former. It starts its bundled server and signs you into a private local administrator account. No separate server installation is needed.</li><li><b>Join an existing server:</b> open the host’s performance address in a browser, or use Server → Connect to Server in the desktop app. Use your account or an invitation from the host.</li><li><b>Set up a dedicated server:</b> on that machine, open a terminal in the pr0former source checkout and run <code>./init.sh</code>. Review its dependency and startup prompts, then run <code>./init.sh --start</code>. See the init.sh section for addresses, HTTPS and updates.</li></ul>
        <p>The desktop app can also host its bundled engine for other computers: Server → Host on Local Network…. The Architecture section explains how these choices relate.</p>
      </section>
      <section><h2>2. Sign in and create a project</h2><p>A new standalone server asks you to create its first administrator account. Later registrations require an invitation. The desktop’s bundled account is created automatically and stays signed in until you quit. Projects and users belong to the server you are connected to.</p><p>Create a Freeform project for experimentation, or open an existing project. A project holds its graph, score, memberships, settings and saved revisions. Set a useful tempo, such as 120 BPM.</p></section>
      <section><h2>3. Make a first listening path</h2><p>Add Oscillator, Gain, Meter and Monitor output from the library. Connect <b>Oscillator Out → Gain In → Meter In → Monitor output In</b>. Keep each node at two channels. Open Gain’s gear and set Gain to −18 dB.</p><p>Enable the audio engine in the footer. Open the browser monitor, select your Monitor output feed and connect. A microphone is not needed for this test. Start with a low headphone volume; you should hear a steady tone and see the Meter move.</p><p>For speakers attached to the server, use Audio output instead. An administrator enables its physical output interface in System settings; choose the interface and channel mapping in the output node modal. A dedicated Monitor output never feeds server speakers.</p></section>
      <section><h2>4. Make it playable</h2><p>Add Piano and a Polyphonic synth. Connect their typed MIDI ports, then connect the synth’s audio output through your listening chain. Synth defaults to mono, so set the downstream chain to one channel or change Synth to two. Remove the test oscillator cable before connecting the synth to Gain: an audio input accepts one source.</p><p>Play and release keys with the engine enabled. Typed MIDI carries notes, velocity, releases and pitch bend together. Open the ADSR example in the node reference for a monophonic instrument with a separately patched envelope.</p></section>
      <section><h2>5. Add score playback and save</h2><p>Create a part in Score and choose its instrument, or connect an assigned Part MIDI node to an instrument’s MIDI input. Enter notes, choose a count-in and press Play. Engine enablement runs the graph; Play starts score scheduling. Stop rewinds the show while the development graph keeps running.</p><p>Edits update the working project. Save revision (Cmd/Ctrl+S) creates a history checkpoint; automatic history snapshots coalesce edits once per minute. Export project JSON for a portable project definition. Keep sample audio and recordings in your server backup too.</p></section>
      <section><h2>If there is no sound</h2><ol><li>Check that you are on the intended server and the project’s engine is enabled.</li><li>Check the source: oscillators run continuously; Piano needs a key press; score parts need Play; sample nodes need a selected sample.</li><li>Check that ports and channel widths match. The server rejects invalid graph connections.</li><li>If the graph Meter moves, check the listening destination: connect the selected browser feed, or enable/map the server hardware output.</li><li>For a local microphone, assign the input to your account, allow microphone permission and use HTTPS or localhost. Each user sends one selected local input per project session.</li><li>Open Monitor and Console for connection errors and device status. After an engine reconfiguration, reconnect the monitor if needed.</li></ol></section>
    </template>
    <template v-else-if="topic === 'architecture'">
      <h1>Architecture: server and clients</h1><p class="lead">One server owns the performance engine and project data. Browsers and desktop windows are clients of that server.</p>
      <section><h2>Where each responsibility lives</h2><table><thead><tr><th>Server</th><th>Client</th></tr></thead><tbody><tr><td>Rust DSP engine, graph validation, sample clock, score scheduling</td><td>Graph and score editors, conductor controls, performer stage</td></tr><tr><td>Accounts, project membership, SQLite revisions, samples and recordings</td><td>Local window/view preferences and authenticated editing requests</td></tr><tr><td>Audio/MIDI interfaces attached to the server; OSC send/receive</td><td>Optional microphone uplink, local MIDI input and headphone monitoring</td></tr></tbody></table><p>Edits travel to the server for permission and graph validation. The server broadcasts project revisions and live telemetry to authorized clients. Telemetry is display state and does not become a saved parameter or undo entry.</p><p>Audio is processed on the server. A browser monitor receives a WebRTC/Opus feed; a client microphone sends audio back over WebRTC to its assigned Local audio input node. Network and device buffers add listening latency. Browser timers animate the interface; musical events follow the engine’s sample time.</p></section>
      <section><h2>The desktop app’s local server</h2><p>The macOS/Linux Tauri app bundles the same Rust server, Vue interface and FFmpeg converter. Opening it launches a private server on an automatically chosen localhost port and opens the interface with a private administrator session. Your local projects work without internet after installation.</p><p>The bundled profile is separate from a server run from your source checkout. On macOS it lives in <code>~/Library/Application Support/org.pr0former.desktop/</code>; on Linux it normally lives in <code>~/.local/share/org.pr0former.desktop/</code> (or under XDG_DATA_HOME). It contains data, recordings, a server log and local connection/window settings. App updates preserve that profile.</p><p>Server → Connect to Server switches the client to a remote server and requires that server’s normal sign-in. It does not copy projects, accounts, samples or devices between servers. Server → Bundled Engine returns to the private local session. The bundled process remains owned by the app.</p></section>
      <section><h2>Let the desktop become the host</h2><ol><li>Open Server → Host on Local Network….</li><li>Start HTTPS hosting and share the displayed performance address with clients on the same network. The additional listener exposes the same local engine, accounts and projects.</li><li>Create ordinary accounts or project invitations. The desktop’s private administrator session is rejected on the LAN listener.</li><li>For browser clients, follow the certificate setup instructions shown by the host. On iPad, install the certificate profile and enable full trust in Certificate Trust Settings. Compare the CA fingerprint with the host.</li><li>Use the HTTPS hosting address in invitations; replace any private localhost origin in a copied invitation link.</li></ol><p>Stop Hosting closes LAN access while leaving the private local engine available. Quitting the desktop stops both. Keep the host awake during a performance. LAN discovery helps locate compatible hosts; it does not grant access or certificate trust. Physical iPad trust and audio behavior still require device testing.</p></section>
      <section><h2>Run a dedicated server</h2><p>Use init.sh on a machine that should host independently of a desktop application. It builds the frontend and release server and can configure a user startup service. Open the printed address from clients; use the server’s hostname or IP, not another machine’s localhost.</p><p>The default bind address listens on all IPv4 interfaces, using HTTP port 80 or HTTPS port 443. Choose a loopback host for local-only work or configure an appropriate LAN address. HTTPS is needed for remote browser microphone access. The server supplies local fonts/assets and has no external STUN/TURN dependency; internet/NAT traversal is not automatic.</p></section>
      <section><h2>Engine versus show</h2><p>A server loads one development graph at a time. Enablement prepares that graph; continuous audio and graph clocks run while the show is stopped. Play starts the score and realigns graph timing to it. Pause suspends score progression. Stop rewinds the score; recording nodes keep recording until their own Stop input or engine disablement.</p><p>Graph edits are prepared outside rendering and installed between DSP blocks. Audio device callbacks move samples through bounded buffers. The worker is not yet a dedicated OS-priority realtime engine; software tests do not establish physical-device latency or deadline reliability.</p><p>Closing the last client window for a project unloads its engine after a five-second reconnect grace. Keeping a server process running does not by itself keep an unattended project active.</p></section>
    </template>
    <template v-else-if="topic === 'init'">
      <h1>init.sh: set up a server</h1><p class="lead">The standalone server entry point for macOS and Linux. Run it as your normal user from the source checkout.</p>
      <section><h2>First setup</h2><pre><code>cd /path/to/pr0former
./init.sh
./init.sh --start</code></pre><p>The script checks dependencies, offers to install missing tools, builds the production frontend and release Rust server, and offers startup configuration. It asks before installing dependencies or changing startup services. It creates no administrator password: open the server’s address to create the first account.</p><p>Builds need Rust/Cargo, Node/npm, FFmpeg and the platform’s native build/audio dependencies. The initial dependency download needs internet; serving the built interface uses local assets. Read prompts for your operating system. Use <code>./init.sh --help</code> for the script’s complete command reference.</p></section>
      <section><h2>Choose an address</h2><pre><code>./init.sh --start --host 127.0.0.1 --port 8080 --no-ssl</code></pre><p>This example is HTTP on this machine only. For LAN use, choose the host’s interface address or <code>0.0.0.0</code> and share its actual hostname/IP with clients. The normal defaults are HTTP 80 or HTTPS 443. Linux may require bind-port permission for ports below 1024; use higher ports when appropriate.</p><p>Start reuses <code>.local/start-pr0former.sh</code> when present, otherwise PR0_ environment settings. Host and port flags override the selected portions for this launch only. Start prints the compiled Git revision and checks the tracked remote branch for up to eight seconds. It does not pull or rebuild; a stale-build warning is a reason to review/update the checkout.</p></section>
      <section><h2>Command reference</h2><table><thead><tr><th>Command</th><th>What it does</th></tr></thead><tbody><tr><td><code>--start</code></td><td>Runs the built release server in the foreground. Ctrl-C stops it.</td></tr><tr><td><code>--stop</code></td><td>Stops tracked servers launched by --start from this checkout. It is not the desktop app’s shutdown command.</td></tr><tr><td><code>--update</code></td><td>Rebuilds frontend and release server with locked dependencies. Requires installed tools; does not pull source or restart a running server.</td></tr><tr><td><code>--uas</code></td><td>Fast-forward pulls the current branch’s configured upstream, rebuilds, then starts in the foreground. Pull/build failures prevent startup.</td></tr><tr><td><code>--startup</code></td><td>Interactively enables or disables login startup. macOS uses a current-user LaunchAgent; Linux uses a systemd user service. Choose the unchanged option to leave services as they are.</td></tr><tr><td><code>--setup-ssl</code></td><td>Creates the managed local HTTPS certificate. Restart to apply; trust certs/ca.pem on each client.</td></tr><tr><td><code>--remove-ssl</code></td><td>Removes managed certificates and returns to HTTP after restart.</td></tr><tr><td><code>--no-ssl</code></td><td>Forces HTTP for this --start/--uas launch.</td></tr><tr><td><code>--host HOST --port PORT</code></td><td>Overrides the bind address for --start/--uas. Ports must be 1–65535.</td></tr></tbody></table><p>Select one action at a time. Update/SSL commands do not change startup services. Login startup is a user service; do not assume it starts a show at machine boot.</p></section>
      <section><h2>HTTPS on alternate ports</h2><pre><code>./init.sh --setup-ssl
PR0_HTTP_PORT=8080 ./init.sh --start --port 8443</code></pre><p>After creating certificates and trusting the CA on your clients, open HTTPS on port 8443; the HTTP redirect listener uses 8080. Certificate trust and project invitations are separate: a trusted certificate does not authorize an account.</p></section>
      <section><h2>Data and updates</h2><p>The standalone server normally uses the checkout’s <code>data/</code> and <code>recordings/</code> directories. PR0_DATA and PR0_RECORDINGS_ROOT can choose other locations; saved startup configuration may already set them. Back up the complete data and recordings with the server stopped before moving to another machine. A desktop build does not adopt this database automatically.</p><p>Stop the running instance before restarting an updated build on the same ports. If you enabled login startup, manage that through --startup rather than starting a competing foreground instance. Changes to certificates require a restart too.</p></section>
    </template>
    <template v-else>
      <h1>build.sh: build the desktop app</h1><p class="lead">Package the frontend, Rust server and FFmpeg into a Tauri application for the build machine’s OS and architecture.</p>
      <section><h2>Choose a build</h2><pre><code>./build.sh --help
./build.sh                 # interactive macOS signing choices; Linux defaults
./build.sh --unsigned      # local macOS build, no Developer ID credentials
./build.sh --bundles dmg   # macOS disk image
./build.sh --jobs 8</code></pre><p>Default bundles are a macOS .app or Linux AppImage and .deb. Run on the target OS/architecture; the script does not build a universal Mac binary or an iPad app. It does not launch the app or install startup services.</p></section>
      <section><h2>Prerequisites and build stages</h2><p>Install Rust/Cargo, Node/npm, Python 3, curl, make, a C compiler, and tar/xz. macOS needs Xcode Command Line Tools. Linux additionally needs WebKitGTK 4.1/GTK development packages, ALSA/Opus development packages and GStreamer media plugins. The repository’s docs/DESKTOP.md has platform package details.</p><ol><li>Install locked frontend dependencies and build the production Vue interface.</li><li>Build the release pr0-server executable.</li><li>Download and verify pinned FFmpeg source, compile it, and cache the result under desktop/.build/.</li><li>Stage the server, frontend, FFmpeg and license materials in the Tauri resources.</li><li>Build the platform bundle, then complete requested signing/notarization.</li></ol><p>The first build needs internet and can take several minutes. The completed app uses bundled resources; it does not download FFmpeg at launch.</p></section>
      <section><h2>Find and open the result</h2><p>Bundles are written to <code>desktop/src-tauri/target/release/bundle/</code>. Successful macOS builds also refresh <code>pr0former.app</code> in the project root. Open the app to start its private bundled server. Your project data lives in the application profile, outside the bundle.</p></section>
      <section><h2>Signing and distribution on macOS</h2><table><thead><tr><th>Option</th><th>Use</th></tr></thead><tbody><tr><td><code>--sign</code></td><td>Developer ID signing only.</td></tr><tr><td><code>--notarize</code></td><td>Sign, submit using saved Keychain credentials, and staple the accepted ticket.</td></tr><tr><td><code>--notarize-only</code></td><td>Notarize/staple the existing signed .app without rebuilding.</td></tr><tr><td><code>--unsigned</code></td><td>Local ad-hoc build; ignores Apple signing/notarization credentials.</td></tr><tr><td><code>--no-prompt</code></td><td>Retain Tauri’s APPLE_* environment behavior without interactive prompts.</td></tr><tr><td><code>--unlock-keychain</code></td><td>Securely prompt to unlock the login Keychain; SSH needs an interactive terminal (ssh -t).</td></tr></tbody></table><p>Noninteractive macOS builds require an explicit signing choice. PR0_NOTARY_PROFILE selects the saved credentials profile (default pr0former-notary); PR0_NOTARY_KEYCHAIN selects a Keychain file. See docs/DESKTOP.md for credential setup. Local ad-hoc builds and notarized distribution builds have different installation trust behavior.</p></section>
    </template>
  </article>
</template>
<style scoped>
.setup-guide section{margin:26px 0}.setup-guide p,.setup-guide li{font-size:13px;line-height:1.8;color:#afbec0}.setup-guide p{margin:12px 0}.setup-guide ul,.setup-guide ol{padding-left:24px}.setup-guide li{margin:9px 0}.setup-guide table{border-collapse:collapse;width:100%;font-size:12px;line-height:1.65;margin:16px 0}.setup-guide th,.setup-guide td{text-align:left;vertical-align:top;padding:12px;border:1px solid #3b484b}.setup-guide th{color:var(--cyan);background:#1c292b}.setup-guide td{color:#afbec0}.setup-guide pre{overflow:auto;background:#10191b;padding:18px;border:1px solid #354447;border-radius:6px;line-height:1.8}.setup-guide code{color:#cfdbd9;font-size:12px;overflow-wrap:anywhere}.setup-guide .lead{font-size:16px}
</style>
