<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue'
import { X, AudioLines } from 'lucide-vue-next'
import { api } from '../api'
import TaskProgress from './TaskProgress.vue'
export interface AudioSettings {sample_rate:number;block_size:number;interfaces:{id:number;name:string;enabled:boolean;correct_latency:boolean;latency_ms:number}[]}
const props=defineProps<{projectId:string;editable:boolean;active:boolean}>()
const emit=defineEmits<{close:[];saved:[settings:AudioSettings]}>()
const dialog=ref<HTMLDialogElement>(),settings=ref<AudioSettings>({sample_rate:48000,block_size:128,interfaces:[]}),devices=ref<any>(),error=ref(''),loading=ref(true),testingPending=ref(false),busy=ref(''),testing=ref(false),position=ref(0)
let disposed=false
let stopTimer:ReturnType<typeof setTimeout>|undefined
let socket:WebSocket|undefined,frame=0,last:{sample:number;sample_rate:number;received:number}|undefined
async function refresh(){const [saved,found]=await Promise.all([api<AudioSettings>('/system/audio'),api<any>('/devices')]);devices.value=found;settings.value={...saved,interfaces:[...found.interfaces.map((d:any)=>saved.interfaces.find(i=>i.id===d.id)||{...d,enabled:false,correct_latency:false,latency_ms:0}),...saved.interfaces.filter(i=>!found.interfaces.some((d:any)=>d.id===i.id))]}}
async function save(){busy.value='Preparing audio clips';error.value='';try{await stop();const saved=await api<AudioSettings>(`/projects/${props.projectId}/system/audio`,'PUT',settings.value);settings.value=saved;emit('saved',saved)}catch(e){error.value=String(e)}finally{busy.value=''}}
async function stop(){clearTimeout(stopTimer);if(testing.value){await api(`/projects/${props.projectId}/latency-test`,'POST',{enabled:false});testing.value=false}}
async function test(){if(testingPending.value)return;testingPending.value=true;error.value='';try{if(testing.value){await stop();return}await api(`/projects/${props.projectId}/latency-test`,'POST',{enabled:true});if(disposed){await api(`/projects/${props.projectId}/latency-test`,'POST',{enabled:false});return}testing.value=true;stopTimer=setTimeout(()=>void stop().catch(()=>{}),60000)}catch(e){error.value=String(e)}finally{testingPending.value=false}}
async function input(){try{await api(`/projects/${props.projectId}/audio`,'POST',{enabled:!devices.value?.input_enabled,input:true});devices.value=await api('/devices')}catch(e){error.value=String(e)}}
async function close(){if(testingPending.value)return;try{await stop();emit('close')}catch(e){error.value=String(e)}}
onMounted(async()=>{dialog.value?.showModal();try{await refresh()}catch(e){error.value=String(e)}finally{loading.value=false}if(disposed)return;socket=new WebSocket(`${location.protocol==='https:'?'wss:':'ws:'}//${location.host}/api/projects/${props.projectId}/events`);socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='latency_test')last={...m,received:performance.now()}};const tick=()=>{if(testing.value&&last){const t=last.sample/last.sample_rate+Math.min(0.5,(performance.now()-last.received)/1000);position.value=(1-Math.cos(t*Math.PI*2))/2*100}frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick)})
onBeforeUnmount(()=>{disposed=true;clearTimeout(stopTimer);void stop().catch(()=>{});socket?.close();cancelAnimationFrame(frame)})
</script>
<template>
<dialog ref="dialog" class="parameter-modal system-settings" aria-labelledby="system-title" @cancel.prevent="close"><header class="modal-header"><div><div class="eyebrow">PERFORMANCE SERVER</div><h2 id="system-title">System settings</h2></div><button class="icon-button" aria-label="Close system settings" :disabled="!!busy" @click="close"><X :size="20"/></button></header>
<div class="settings-layout"><nav role="tablist" aria-label="System settings sections"><button class="active" role="tab" aria-selected="true"><AudioLines :size="16"/> System audio</button></nav><section role="tabpanel"><h3>System audio</h3><p>These settings apply to every project on this server.</p><p v-if="active" class="field-error">Deactivate the show before changing audio settings.</p><p v-if="error" role="alert" class="field-error">{{error}}</p><p v-if="devices?.error" class="field-error">{{devices.error}}</p>
<fieldset :disabled="!editable||active||loading||!!busy"><label>Global sample rate (Hz)<select v-model.number="settings.sample_rate"><option :value="44100">44,100 Hz</option><option :value="48000">48,000 Hz</option><option :value="88200">88,200 Hz</option><option :value="96000">96,000 Hz</option></select></label><p class="feature-note">Clips are converted and cached at this rate. Originals are retained. Other projects prepare their clips when opened.</p>
<label>DSP block size<select v-model.number="settings.block_size"><option v-for="size in [32,64,128,256,512,1024]" :key="size" :value="size">{{size}} frames · {{(size/settings.sample_rate*1000).toFixed(2)}} ms</option></select></label><p class="feature-note">Smaller blocks increase scheduling overhead and reduce the target output queue. The device driver chooses its callback buffer separately.</p><h3>Active interfaces</h3><p class="feature-note">Checked outputs are available in Audio output node modals. With none selected, the engine serves browser monitors only.</p><p v-if="!settings.interfaces.length">No audio output interfaces detected.</p>
<article v-for="i in settings.interfaces" :key="i.id" class="interface-card"><label class="check-label"><input v-model="i.enabled" type="checkbox">{{i.name}}<span v-if="!devices?.interfaces.some((d:any)=>d.id===i.id)"> · unavailable</span></label><div class="latency-controls"><label class="check-label"><input v-model="i.correct_latency" :disabled="!i.enabled" type="checkbox">Correct for latency</label><label>Latency (ms)<input v-model.number="i.latency_ms" type="number" min="0" max="1000" step="0.1" :disabled="!i.enabled||!i.correct_latency"></label></div></article>
<p class="feature-note">Correction delays faster checked interfaces to match the largest entered latency. Separate device clocks may drift; an OS aggregate device is preferable for synchronized multichannel output.</p><button class="button primary" @click="save">Save system audio</button></fieldset>
<section class="latency-test"><h3>Latency test</h3><p>Save your interfaces, then compare the server metronome with the bouncing indicator. Enter measured output latencies above. This is manual calibration; browser and network delay affect the visual reference.</p><div class="metronome-track" aria-label="Metronome position"><span :style="{left:`${position}%`}" :class="{testing}"></span></div><button class="button" :disabled="!editable||active||loading||testingPending||!!busy" @click="test">{{testing?'Stop latency test':'Start latency test'}}</button><small>Stops automatically after 60 seconds.</small></section>
<h3>Native input</h3><button class="button" :disabled="!editable||!active" @click="input">{{devices?.input_enabled?'Disable server input':'Enable server input'}}</button><p class="feature-note">Uses the server’s default input at the selected rate while the show is active.</p><h3>MIDI outputs</h3><p v-for="name in devices?.midi_outputs" :key="name">{{name}}</p><p v-if="!devices?.midi_outputs?.length">No MIDI outputs detected.</p>
</section></div></dialog><TaskProgress v-if="busy" :title="busy" detail="Converting and caching this project’s clips. Original files are retained."/>
</template>
