<script setup lang="ts">
import {computed,onMounted,ref,toRaw,nextTick} from 'vue'
import {api} from '../api'
const props=defineProps<{currentUserId:string}>()
const users=ref<any[]>([]),search=ref(''),selected=ref<any>(),busy=ref(false),error=ref(''),notice=ref(''),password=ref(''),deleting=ref(false),confirmation=ref('')
const profileForm=ref<HTMLFormElement>()
const fields=['prefix','first_name','middle_name','last_name','suffix','email','phone','organization','notes'] as const
const label=(key:string)=>key.replaceAll('_',' ').replace(/^./,s=>s.toUpperCase())
const visible=computed(()=>users.value.filter(u=>JSON.stringify(u).toLowerCase().includes(search.value.toLowerCase())))
async function refresh(){try{users.value=await api('/admin/users')}catch(e){error.value=String(e)}}
function edit(user?:any){selected.value=user?structuredClone(toRaw(user)):{username:'',enabled:true,is_admin:false};for(const key of fields)selected.value[key]??='';password.value='';error.value='';notice.value='';deleting.value=false;confirmation.value='';void nextTick(()=>profileForm.value?.querySelector<HTMLInputElement>('input')?.focus())}
async function save(){busy.value=true;error.value='';try{const u=selected.value;const saved=await api<any>(u.id?`/admin/users/${u.id}`:'/admin/users',u.id?'PUT':'POST',{username:u.username,is_admin:u.is_admin,enabled:u.enabled,revision:u.revision,password:password.value||undefined,fields:Object.fromEntries(fields.map(key=>[key,u[key]]))});await refresh();edit(saved);notice.value='User saved. Password, role and activation changes revoke the user’s sessions.'}catch(e){error.value=String(e)}finally{busy.value=false}}
async function revoke(){busy.value=true;try{await api(`/admin/users/${selected.value.id}/sessions`,'DELETE');notice.value='All sessions revoked.'}catch(e){error.value=String(e)}finally{busy.value=false}}
async function remove(){busy.value=true;error.value='';try{await api(`/admin/users/${selected.value.id}`,'DELETE',{confirm:confirmation.value,revision:selected.value.revision});selected.value=undefined;await refresh();notice.value='Account deleted.'}catch(e){error.value=String(e)}finally{busy.value=false}}
onMounted(refresh)
</script>
<template>
<section class="user-admin" aria-label="User administration"><h3>User administration</h3><p>Create accounts, maintain profiles and manage access. System administration is separate from project membership.</p>
<div class="admin-toolbar"><input v-model="search" aria-label="Search users" placeholder="Search users…"><button class="button" :disabled="busy" @click="edit()">Add user</button></div>
<p v-if="error" class="field-error" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p>
<div class="user-table"><table><thead><tr><th>Username</th><th>Name</th><th>Access</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr v-for="u in visible" :key="u.id" :class="{selected:selected?.id===u.id}"><td><button class="text-button" :disabled="busy" @click="edit(u)">{{u.username}}</button></td><td>{{[u.prefix,u.first_name,u.middle_name,u.last_name,u.suffix].filter(Boolean).join(' ')}}</td><td>{{u.is_admin?'Admin':'Regular'}}</td><td>{{u.enabled?'Active':'Disabled'}}</td><td><button class="button" :aria-label="`Edit user ${u.username}`" :disabled="busy" @click="edit(u)">Edit</button></td></tr></tbody></table></div>
<form v-if="selected" ref="profileForm" aria-label="User profile" @submit.prevent="save"><h3>{{selected.id?'Edit user':'New user'}}</h3><fieldset :disabled="busy"><div class="profile-grid"><label>Username<input v-model="selected.username" required minlength="3" maxlength="64" autocomplete="off"></label><label v-for="key in fields" :key="key">{{label(key)}}<textarea v-if="key==='notes'" v-model="selected[key]" maxlength="4096"></textarea><input v-else v-model="selected[key]" :type="key==='email'?'email':'text'" maxlength="256"></label><label>{{selected.id?'New password':'Initial password'}}<input v-model="password" type="password" :required="!selected.id" minlength="8" maxlength="256" autocomplete="new-password"></label></div><label class="check-label"><input v-model="selected.is_admin" type="checkbox">Administrator</label><label class="check-label"><input v-model="selected.enabled" type="checkbox">Account enabled</label><HelpNote>Leave an existing password blank to keep it. Security changes sign this user out on all devices. The last active administrator is protected.</HelpNote><div class="admin-toolbar"><button class="button primary" type="submit">Save user</button><button v-if="selected.id" class="button" type="button" @click="revoke">Revoke sessions</button><button v-if="selected.id" class="button danger" type="button" :disabled="selected.id===currentUserId" @click="deleting=!deleting">Delete user</button></div>
<div v-if="deleting" class="delete-warning"><strong>Delete this account permanently?</strong><p>Profile information and project memberships will be removed. Users who own projects or samples cannot be deleted; disable their account instead.</p><label>Type username to delete<input v-model="confirmation" autocomplete="off"></label><button class="button danger" type="button" :disabled="confirmation!==selected.username" @click="remove">Permanently delete user</button></div></fieldset></form>
</section>
</template>
<style scoped>
.admin-toolbar{display:flex;gap:10px;align-items:center;margin:14px 0;flex-wrap:wrap}.admin-toolbar input{flex:1;min-width:150px}.user-table .selected{background:rgba(83,218,228,.08)}.user-table .button{min-height:44px}.user-table{overflow:auto;max-height:260px}table{width:100%;border-collapse:collapse;font-size:12px}th,td{text-align:left;padding:10px;border-bottom:1px solid var(--line)}th{color:var(--muted)}.profile-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}label{display:flex;flex-direction:column;font-size:12px;gap:6px}.check-label{flex-direction:row;margin-top:12px}.delete-warning{padding:15px;border:1px solid #dd8171;border-radius:6px;margin-top:16px;color:#f3b0a2}.delete-warning .button{margin-top:10px}@media(max-width:600px){.profile-grid{grid-template-columns:1fr}}
</style>
